### ISSUE TITLE
导航抽屉在断点转换时出现异常

### ISSUE THREAD

**Issue by kimdiego2098** [masastack/MASA.Blazor#1000]
**Describe the bug**
如题，下面时模拟设备的gif
![masa导航抽屉](https://user-images.githubusercontent.com/82756760/218257839-fdd08cee-6836-4d6c-aac5-26ed5ee91a6a.gif)

**To Reproduce**
MNavigationDrawer

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by capdiem** [comment]
@kimdiego2098  `F12` 或者突然切换移动端和桌面端时才会出现吧，正常的从缩小到放大应该不会出现此种情况吧。

**Comment by kimdiego2098** [comment]
> @kimdiego2098 或者突然切换移动端和桌面端时才会出现吧，正常的从缩小到放大应该不会出现此种情况吧。`F12`

是的，F12才有

**Comment by capdiem** [comment]
已解决
