### ISSUE TITLE
树形组件数据被重新new了以后之前被打开过的无法打开

### ISSUE THREAD

**Issue by 239573049** [masastack/MASA.Blazor#1006]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by 239573049** [comment]
![image](https://user-images.githubusercontent.com/61819790/218633971-9945b545-99eb-4fda-81f0-80d89957b256.png)

打开子集然后再重新new 再打开子集发现无法打开

**Comment by capdiem** [comment]
@239573049 我尝试在[使用[(https://docs.masastack.com/blazor/components/treeview)的示例上重新new，也能能打开子集的，没有复现你的问题。
```csharp
_data = new List<Data>() { };
```

**Comment by doddgu** [comment]
> ![image](https://user-images.githubusercontent.com/61819790/218633971-9945b545-99eb-4fda-81f0-80d89957b256.png)
> 
> 打开子集然后再重新new 再打开子集发现无法打开

最好有复现demo

**Comment by 239573049** [comment]
> > ![image](https://user-images.githubusercontent.com/61819790/218633971-9945b545-99eb-4fda-81f0-80d89957b256.png)
> > 打开子集然后再重新new 再打开子集发现无法打开
> 
> 最好有复现demo

https://github.com/239573049/Masa.Code

**Comment by capdiem** [comment]
升级到1.0再试试 @239573049
