### ISSUE TITLE
MExpansionPanels组件elevation-0设置失效

### ISSUE THREAD

**Issue by mookeview** [masastack/MASA.Blazor#1026]
<img width="868" alt="error1" src="https://user-images.githubusercontent.com/121916399/220222264-1d87727e-186d-4969-bb60-b6f3bda82751.png">
<img width="348" alt="error2" src="https://user-images.githubusercontent.com/121916399/220222276-fc16e5d1-274f-477c-ae6a-a1b75cbe6176.png">

**Comment by doddgu** [comment]
@capdiem PTAL

**Comment by capdiem** [comment]
和 #955 一样，不是通过 elevation 实现的。你需要重写覆盖 `.m-expansion-panel::before` 的样式：
```css
box-shadow: 0px 0px 2px rgba(0,0,0,.2);
```

**Comment by mookeview** [comment]
非常感谢您回复！我在页面的隔离CSS中写入
.m-expansion-panel::before{
    box-shadow:none;
}
但似乎不起效，本人初学，可否再指点一下？？

**Comment by capdiem** [comment]
@mookeview 隔离CSS需要作用到原生标签上例如 `div` 。你可以试试 `::deep .m-expansion-panel::before`

**Comment by mookeview** [comment]
加::deep编译能不过，我现在直接修改发布后的masa-blazor.min.css文件，暂时解决下。谢谢啦！

**Comment by capdiem** [comment]
@mookeview css不会影响编译吧，可以忽视波浪线。你也可以向 _wwwroot/site.css_ 添加，不建议修改我们发布的css。

**Comment by capdiem** [comment]
使用 `Flat` 属性就可以去除阴影。
