### ISSUE TITLE
MTabs 画面在切换左侧Tab时闪烁

### ISSUE THREAD

**Issue by kimdiego2098** [masastack/MASA.Blazor#1038]
**Describe the bug**
![image](https://user-images.githubusercontent.com/82756760/221346234-8896332a-3ec4-402d-b322-eba21a21df0d.png)
![image](https://user-images.githubusercontent.com/82756760/221346242-af1babaf-3566-489d-a5a8-33f22e8ddf3d.png)
![image](https://user-images.githubusercontent.com/82756760/221346213-9ca268bb-9258-4b38-b5c4-1baad0bcf5dd.png)
![image](https://user-images.githubusercontent.com/82756760/221346281-da328c82-c966-49b5-ba66-a603ddcf89d6.png)
这是按顺序的帧捕捉，按下按钮会有一下白屏，再出现动画切换
下面是完整的gif
![8](https://user-images.githubusercontent.com/82756760/221346309-0550d23a-dfee-479e-9590-8de38e6d9196.gif)
Gif帧率可能太低，看不出来，但是实际肉眼看得很明显
下面补充一下手机录屏

https://user-images.githubusercontent.com/82756760/221346770-d723d17a-a1bf-46b0-bfaa-8c4dbba9503c.mp4

补充：切换右侧Tab没有出现这样的情况
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by doddgu** [comment]
Thanks for feedback.

**Comment by capdiem** [comment]
现在无法复现，可能已经修复了。
