### ISSUE TITLE
MASA.Blazor文档中心合理化建议

### ISSUE THREAD

**Issue by grantcy** [masastack/MASA.Blazor#1040]
MASA Stack 产品线合理化建议
文档中心相关 UI组件 增加组件示例编辑交互功能 方便理解组件运行逻辑
![捕获1](https://user-images.githubusercontent.com/68209170/221455961-52fa1222-f160-4edb-808b-63981d2e3250.PNG)
![捕获2](https://user-images.githubusercontent.com/68209170/221455975-f3959828-8ea4-4346-a329-13d91c8918e9.PNG)
![捕获3](https://user-images.githubusercontent.com/68209170/221455978-65d94347-34fd-4233-8050-02b810aa7018.PNG)

**Comment by capdiem** [comment]
有小伙伴在帮我们做，短期应该不会上，你可以下载源码，在 Masa.Blazor.Playgorud 里测试。

**Comment by doddgu** [comment]
@239573049 hi!

**Comment by 239573049** [comment]
http://blazor.tokengo.top/

**Comment by doddgu** [comment]
@239573049 下周我们对接一下

**Comment by 239573049** [comment]
> @239573049 下周我们对接一下

可以的

**Comment by capdiem** [comment]
https://try.masastack.com 已经上线，关闭此issue。
