### ISSUE TITLE
It is strange when the length of Textarea is longer than the screen when AutoGrow is true

### ISSUE THREAD

**Issue by Yu-Core** [masastack/MASA.Blazor#1059]
The video is from maui blazor, but webassembly too.
This is the case with Windows and Android.

https://user-images.githubusercontent.com/96511239/223275372-4c28d0fc-4511-49a3-b4f0-7503fc504359.mp4

![image](https://user-images.githubusercontent.com/96511239/223275682-03a7a53c-ad0f-4080-8c50-e927520c9385.png)

**Comment by capdiem** [comment]
@Yu-Core v1.6.0 已经修复。

**Comment by Yu-Core** [comment]
感谢
