### ISSUE TITLE
MAUI MASA Blazor APP flashes back after Android 5.1(API 22) is launched

### ISSUE THREAD

**Issue by grantcy** [masastack/MASA.Blazor#1162]
Bug Description:
Java.Lang.NoSuchMethodError: 'no non-static method "Landroid/webkit/WebView;.createWebMessageChannel()[Landroid/webkit/WebMessagePort;"'

.NET MAUI apps can be written for Android 5.0 (API 21) or higher.
Can we increase support for Android 5.1 (API 22) through loading controls and modifying injection methods？

**Comment by sunday866** [comment]
https://learn.microsoft.com/zh-cn/dotnet/maui/supported-platforms?view=net-maui-7.0
