### ISSUE TITLE
[Bug Report]: MDataTable在行选择和紧凑时Ripple被压缩

### ISSUE THREAD

**Issue by devhxj** [masastack/MASA.Blazor#1165]
### Masa.Blazor version

1.0

### Describe the bug

![image](https://user-images.githubusercontent.com/46732776/229000384-b481a8f8-1b10-4993-8334-afe6b5934d1a.png)
![image](https://user-images.githubusercontent.com/46732776/229000412-f6c02b8c-1b72-43da-99e0-006deb94b71a.png)

### Expected Behavior

和vuetify一样，把MSimpleCheckbox的Ripple去掉

### Steps To Reproduce

官网MDataTable 行选择demo，设置紧凑

### What browsers are you seeing the problem on?

Chrome

**Comment by doddgu** [comment]
@capdiem PTAL

**Comment by capdiem** [comment]
@devhxj Vuetify也是这样的呀
![image](https://user-images.githubusercontent.com/16507773/229034753-b003c985-e032-4647-9f1e-9f310212fed0.png)

**Comment by devhxj** [comment]
> @devhxj Vuetify也是这样的呀 ![image](https://user-images.githubusercontent.com/16507773/229034753-b003c985-e032-4647-9f1e-9f310212fed0.png)

我看Vuetify官网的没有Ripple了
![pickerrange3333](https://user-images.githubusercontent.com/46732776/229074545-06f5e5ae-efd2-43af-aade-d26e713210d8.gif)

**Comment by capdiem** [comment]
@devhxj 官网是：https://v2.vuetifyjs.com/
