### ISSUE TITLE
希望添加一个适配移动端导航服务。用来实现移动端先进先出堆栈导航。

### ISSUE THREAD

**Issue by 18639522576** [masastack/MASA.Blazor#1166]
实现服务导航或组件等提供分层导航体验，让用户可以随心所欲地向前或向后导航页面。 类似正常移动端后进先出 (LIFO) 堆栈。

**Comment by capdiem** [comment]
@18639522576 已支持：[PageStack](https://docs.masastack.com/blazor/labs/page-stack)
