### ISSUE TITLE
[Bug Report]: MMenu组件在滚动条获取焦点时不会自动关闭

### ISSUE THREAD

**Issue by devhxj** [masastack/MASA.Blazor#1167]
### Masa.Blazor version

1.0

### Describe the bug

![pickerrange3333](https://user-images.githubusercontent.com/46732776/229003694-763f6eb0-0f23-4bab-ac95-0ccafe588f85.gif)

### Expected Behavior

焦点在滚动条时MMenu自动关闭

### Reproduction code

```razor
焦点时不会自动关闭
```

**Comment by capdiem** [comment]
It will not be fixed until we plan to follow up with [Vueitfy3](https://vuetifyjs.com/en/api/v-menu/#props-scroll-strategy). Until then, you need to listen for scroll events manually.
