### ISSUE TITLE
MAppBarNavIcon自定义图标问题

### ISSUE THREAD

**Issue by MarvelTiter** [masastack/MASA.Blazor#1175]
文档里是这么说的：
专门为与 [MToolbar](https://docs.masastack.com/blazor/components/toolbars) 和 MAppBar 一起使用而创建的样式化图标按钮组件。 在工具栏的左侧显示为汉堡菜单，它通常用于控制导航抽屉的状态。 默认插槽可以用于自定义此组件的图标和功能。

我的代码：
```
<MAppBarNavIcon>        
        <MButton>
            <MIcon>mdi-arrow-left</MIcon>
        </MButton>
    </MAppBarNavIcon>
```

库版本：0.6.0
环境：.Net 6 Maui Blazor

**Comment by capdiem** [comment]
@MarvelTiter 多谢反馈！我们会在1.0里修复它！

**Comment by capdiem** [comment]
@MarvelTiter It would be fixed in `1.0.0-rc.1`.  Usage:
``` razor
<MAppBarNavIcon @onclick="">
  <MIcon>mdi-arrow-left<MIcon>
</MAppBarNavIcon>
```
