### ISSUE TITLE
[Bug Report]: PageTabs 关闭页面时没有实际销毁

### ISSUE THREAD

**Issue by kimdiego2098** [masastack/MASA.Blazor#1183]
### Masa.Blazor version

1.0 preview11

### Describe the bug

![YYT{YPHJQCOFVF6E513EJ8S](https://user-images.githubusercontent.com/82756760/229503406-96212f97-287b-4bbc-a9fd-73b67fa1c796.png)
这个很容易复现，razor @implements IDisposable继承接口，关闭页面时没有进入Dispose方法

### .NET version

net6

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by doddgu** [comment]
@capdiem PTAL
@kimdiego2098 最近公司在组织活动，可能要晚两天回复

**Comment by capdiem** [comment]
@kimdiego2098 我在 [PageTabs1页面](https://github.com/masastack/MASA.Blazor/blob/main/docs/Masa.Blazor.Docs/Pages/PageTabs1.razor) 里实现了 `IDisposable`，关闭之后是会触发Dispose的。

**Comment by kimdiego2098** [comment]
确实是这样，Pro demo也是正常的，找不到原因了，你可以帮我看看吗  https://gitee.com/diego2098/ThingsGateway.git
![image](https://user-images.githubusercontent.com/82756760/229995157-9f33822c-f88e-4847-bd07-eb446b9a0b30.png)
![image](https://user-images.githubusercontent.com/82756760/229995270-369ea521-91e3-4ac3-a125-f344a6f4185b.png)

参考Pro demo写的

**Comment by kimdiego2098** [comment]
> 确实是这样，Pro demo也是正常的，找不到原因了，你可以帮我看看吗 https://gitee.com/diego2098/ThingsGateway.git ![image](https://user-images.githubusercontent.com/82756760/229995157-9f33822c-f88e-4847-bd07-eb446b9a0b30.png) ![image](https://user-images.githubusercontent.com/82756760/229995270-369ea521-91e3-4ac3-a125-f344a6f4185b.png)
> 
> 参考Pro demo写的

@capdiem

**Comment by kimdiego2098** [comment]
![image](https://user-images.githubusercontent.com/82756760/230025517-51178200-a071-409a-b88b-3ef369ef460f.png)
Pro demo可以进入dispose,但是也会报错

**Comment by capdiem** [comment]
@kimdiego2098 控制台报错是echarts组件的问题，你的问题似乎是因为父类已经实现了`IAsyncDisposable`，跟`IDisposable`似乎有冲突。重写Dispose方法就行，在里面dispose就行了。

**Comment by kimdiego2098** [comment]
> @kimdiego2098 控制台报错是echarts组件的问题，你的问题似乎是因为父类已经实现了，跟似乎有冲突。重写Dispose方法就行，在里面dispose就行了。`IAsyncDisposable``IDisposable`

👍是的

**Comment by kimdiego2098** [comment]
已经解决了，感谢
