### ISSUE TITLE
希望添加一个"固钉"组件，在页面滑动的时候，将元素固定在可视范围。

### ISSUE THREAD

**Issue by xiaopanglian** [masastack/MASA.Blazor#1194]
功能需求：
当内容区域比较长，需要滚动页面时，这部分内容对应的操作或者导航需要在滚动范围内始终展现。常用于侧边菜单和按钮组合。

**Comment by doddgu** [comment]
功能可以支持，但如果你现在着急可以参考一下我们文档站点右侧的目录

**Comment by mookeview** [comment]
强烈建议实现这个功能

**Comment by doddgu** [comment]
ok，我们先把它放到2.0，同时也欢迎pr
