### ISSUE TITLE
[Bug Report]: 文档中心代码展示里文字颜色和背景颜色冲突

### ISSUE THREAD

**Issue by wangmin915** [masastack/MASA.Blazor#1208]
### Masa.Blazor version

0.6

### Describe the bug

文档中心代码展示里文字颜色和背景颜色冲突

**Comment by capdiem** [comment]
@wangmin915 文档站点应该是缓存的原因，你可以CTLR+F5去缓存刷新。等 #1207 PR合并以后，会弹出更新通知。
