### ISSUE TITLE
[Bug Report]: MFileInput 上传组件属性里面没有找到设置文件大小的属性

### ISSUE THREAD

**Issue by Jesn** [masastack/MASA.Blazor#1216]
### Masa.Blazor version

1.0.0-preview.13

### Describe the bug

MFileInput 上传组件属性里面没有找到设置文件大小的属性，Blazor默认是限制最大为 500KB，超过该设置在读取文件的时候就抛出异常

### .NET version

net 7.0

**Comment by capdiem** [comment]
@Jesn 你在哪里看到的512KB？之前遇到过的问题是因为[SignalR 消息大小的限制](https://learn.microsoft.com/zh-cn/aspnet/core/blazor/file-uploads?view=aspnetcore-6.0&pivots=server#signalr-message-size-limit)。

**Comment by capdiem** [comment]
@Jesn 那我关闭这个issue了。
