### ISSUE TITLE
[Bug Report]: TreeView开启Selectable后，启动了ValueChanged，bind-Value就不能使用

### ISSUE THREAD

**Issue by Jesn** [masastack/MASA.Blazor#1221]
### Masa.Blazor version

1.0.0-preview.13

### 报错
```
  OrgTreeView.razor(25, 27): [RZ10010] The component parameter 'ValueChanged' is used two or more times for this component. Parameters must be unique (case-insensitive). The component parameter 'ValueChanged' is generated by the '@bind-Value' directive attribute.
```

### 问题描述

   目前我是把`MTreeview`封装成了一个业务组件，通过`ValueChanged`对外传递选中的数据， 这个业务组件是放在一个弹
窗组件里面，每次弹窗打开，`MTreeview`还是会显示上一次选中的节点，我是想每次弹窗显示，就清除`MTreeview`选中的节
点，我看官网的Demo是`MTreeView`上启用`@bind-Value="_selectTreeNode"`，清除的时候执行
`_selectTreeNode.Clear();`，但是我现在启用了`ValueChanged`事件，就会报以上错误，按说 `@bind-Value`和
`ValueChanged`一个是赋值，一个是获取值，他们两个应该不冲突的

![image](https://user-images.githubusercontent.com/5728274/231325600-92655b35-98e6-4854-830b-b1672dcd8dc6.png)

### .NET version

net 7.0

**Comment by capdiem** [comment]
@Jesn @bind-Value是Value和ValueChanged合体的写法，两种写法只能用一个。如果你需要在ValueChanged有额外的逻辑：
``` cs
list<xxx> value;

private void ValueChanged(list<xxx> val) {
    value = val;
} 
```

**Comment by Jesn** [comment]
@capdiem  我按照你的方式处理了下，在`MtreeView`业务组件内部弄一个清除的按钮，调用`value.Clear();`是可行的，但是在`OnParametersSetAsync`里面执行就无效，请问我该如何处理?
```
  protected override Task OnParametersSetAsync()
    {
        if (Clean && ActiveValues.Any())
        {
            value.Clear();
        }

        return base.OnParametersSetAsync();
    }
```

**Comment by capdiem** [comment]
@Jesn 我猜你要把base放在你的逻辑之前执行

**Comment by Jesn** [comment]
@capdiem  试了下，还是不行

**Comment by Jesn** [comment]
那我写个Demo也尝试下，看具体是哪里导致的，谢谢您

**Comment by Jesn** [comment]
@capdiem 
找到问题所在了 `<MTreeview Selectable @bind-Value="_value" />`   应该是`@bind-Value="_value" ` ，我写成了`"Value="_value" `

**Comment by capdiem** [comment]
> @Jesn @bind-Value是Value和ValueChanged合体的写法，两种写法只能用一个。如果你需要在ValueChanged有额外的逻辑：
> 
> ```
> <MTreeview Value="value" ValueChanged="ValueChanged"></MTreeview>
> 
> @code {
>     list<xxx> value;
>     
>     private void ValueChanged(list<xxx> val) {
>         value = val;
>     }
> }
> ```

我不是说了要分开写吗 = =

**Comment by capdiem** [comment]
@Jesn OnParameterSet的那块逻辑有问题呀，你可以说说你的需求。

**Comment by Jesn** [comment]
@capdiem  需求就是：每次打开`PDrawer ` 组件的时候， `MTreeview `的Select处于清空状态。 现在的问题就是我每次打开，还是会显示上一次的选中状态
<img width="1119" alt="image" src="https://user-images.githubusercontent.com/5728274/231421529-61a45fc5-52b7-42bc-b12e-36c29af5c92a.png">

**Comment by capdiem** [comment]
@Jesn MyTree需要复用吗？不复用的最简单的就是直接在你的父组件里写，Drawer的@bind-Value也可以拆开，在Drawer的ValueChanged里判断是false时清空tree的value。

**Comment by Jesn** [comment]
> 最简单的就是直接在你的父组件里写，Drawer的@bind-Value也可以拆开，在Drawer的ValueChanged里判断是false时清空tree的value。

@capdiem   MyTree封装成了一个公用组件，是需要复用的

**Comment by capdiem** [comment]
@Jesn MyTree 内部搞一个public方法用来更新清空value。父组件用MyTree的引用来触发这个方法：
```razor
<MyTree @ref="tree" />

@code {
    public void DrawerValueChanged(bool val) {
        _drawer = val;

        if (val == false) {
            tree.Clear();
        }
    }
}
```

**Comment by Jesn** [comment]
@capdiem  改为在父组件`PDrawer`去触发，`ValueChanged`事件没有任何触发，可能是一个bug，目前调整为`OnCancel`和`OnSave`上调用` tree.Clear()`是可以清除的。

```
<PDrawer Value="Visible"
         FormModel="_model"
         Persistent
         Title="添加用户"
         Width="500"
         OnSave="HandleOnSave"
         OnCancel="HandleOnCancel"
         ValueChanged="HandlerDrawerChanged">
...

</PDrawer>
```

```
    private void HandlerDrawerChanged()
    {
       // PDrawer状态改变，这里没有任何输出
        Console.WriteLine($"HandlerDrawerChanged:{Visible}");
    }
```

**Comment by capdiem** [comment]
@Jesn HandlerDrawerChanged有个bool类型的参数的,需要把这个值赋值给 Visible,我上面写的DrawerValueChanged已经写明了.

**Comment by Jesn** [comment]
> @Jesn HandlerDrawerChanged有个bool类型的参数的,需要把这个值赋值给 Visible,我上面写的DrawerValueChanged已经写明了.

@capdiem `HandlerDrawerChanged` 带参数和不带参数都试过，根本没进这个方法
![image](https://user-images.githubusercontent.com/5728274/231664271-c29939ff-8aff-44e8-90b0-eae8e2f081a3.png)

**Comment by capdiem** [comment]
@Jesn 看了下源码，这块逻辑是如果用了OnCancel就不会走ValueChanged。这块逻辑我考虑下要不要改。

**Comment by Jesn** [comment]
@capdiem  发现masa 有些事件,属性赋值存在互斥的问题，这个问题感觉应该在框架中处理下或者在文档中明确说明下，否则我们在使用的过程中只有采坑了，并且上报给你们才知道事情原委

**Comment by capdiem** [comment]
@Jesn 互斥应该不多吧，可能是当初的设计问题。双向绑定和拆开互斥是blazor的行为，我们控制不了。

**Comment by Jesn** [comment]
@capdiem 目前使用过程中只有个别
