### ISSUE TITLE
[Bug Report]: PageTabs 支持自定义提示框

### ISSUE THREAD

**Issue by differmyth** [masastack/MASA.Blazor#1225]
### Masa.Blazor version

main

### Describe the bug

PageTabs组件
对于可路由组件使用查询参数的情况，不同的查询参数只会显示在同一个标签页中~~

**Comment by capdiem** [comment]
@differmyth 哪个版本，查询参数是哪种？`\order\query`还是 `\order?query=`

**Comment by differmyth** [comment]
版本：main最新分支查询参数：/order/{id}这种没有问题，/order?id=&nbsp; &nbsp;这种参数不同的情况也会显示在同一标签页中


谢谢~~~不知道我这样回复是否清楚，第一次和开源作者沟通。




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月13日(星期四) 中午1:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [masastack/MASA.Blazor] [Bug Report]:  (Issue #1225)





 
@differmyth 哪个版本，查询参数是哪种？\order\query还是 \order?query=

**Comment by capdiem** [comment]
@differmyth 目前只支持匹配路由，不支持查询参数。如果是查询参数有ID这种参数，建议使用 /order/{id} 的形式。像page=1这种感觉意义不大。

**Comment by differmyth** [comment]
嗯，目前我是这路由模板来解决的。
还有个问题，就是标签页关闭时，提示框里的内容不能自定义，会把路由地址都给打印出来，这个感觉不太友好。
非常感谢~~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月13日(星期四) 下午2:06
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [masastack/MASA.Blazor] [Bug Report]:  (Issue #1225)





 
@differmyth 目前只支持匹配路由，不支持查询参数。如果是查询参数有ID这种参数，建议使用 /order/{id} 的形式。像page=1这种感觉意义不大。

**Comment by capdiem** [comment]
@differmyth 嗯 我后面支持下自定义提示框。

**Comment by differmyth** [comment]
谢谢谢谢！！非常感谢！！！！占用您宝贵的时间啦！！



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月13日(星期四) 下午2:14
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [masastack/MASA.Blazor] [Bug Report]:  (Issue #1225)





 
@differmyth 嗯 我后面支持下自定义提示框。

**Comment by protossman** [comment]
PageTabs 能不能增加一个参数来判断是否需要打开提示框来确认关闭

**Comment by protossman** [comment]
我还想请问这个弹出框的中文化是怎么设置的？是要在zh-CN.json里面设置对应的中文吗？


永恒的终结
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "masastack/MASA.Blazor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 下午3:52
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [masastack/MASA.Blazor] [Bug Report]: PageTabs 支持自定义提示框 (Issue #1225)





 从目前我使用的角度来看，不太建议有这个设置，因为如果不弹窗提示，万一是提交数据的窗口，那就直接被关闭了。我现在在用的时候，就很担心会误点到关闭的图标。如果不想增加自定义提示，那是否可以把提示的路由地址改成页标题？这样基本上就够用了~~ 
 我个人看法~~~ 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人: ***@***.***&amp;gt;;  
 发送时间: 2023年4月13日(星期四) 下午3:47 
 收件人: ***@***.***&amp;gt;;  
 抄送: ***@***.***&amp;gt;; ***@***.***&amp;gt;;  
 主题: Re: [masastack/MASA.Blazor] [Bug Report]: PageTabs 支持自定义提示框 (Issue #1225) 
 
 
 
 
 
   
 PageTabs 能不能增加一个参数来判断是否需要打开提示框来确认关闭

**Comment by differmyth** [comment]
@using BlazorComponent.I18n @inject I18n I18n void Example() {    I18n.SetCulture("zh-CN");//将语言切换成zh-CN    var home = I18n.T("Home");//获取键值Home对应语言的值，此方法调用将返回"首页"; }
官网资料有，切换一下语言即可
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "masastack/MASA.Blazor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 下午4:17
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [masastack/MASA.Blazor] [Bug Report]: PageTabs 支持自定义提示框 (Issue #1225)





 我还想请问这个弹出框的中文化是怎么设置的？是要在zh-CN.json里面设置对应的中文吗？ 
 
 
 永恒的终结 
 ***@***.*** 
 
 
 
 &amp;nbsp; 
 
 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "masastack/MASA.Blazor"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年4月13日(星期四) 下午3:52 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [masastack/MASA.Blazor] [Bug Report]: PageTabs 支持自定义提示框 (Issue #1225) 
 
 
 
 
 
  从目前我使用的角度来看，不太建议有这个设置，因为如果不弹窗提示，万一是提交数据的窗口，那就直接被关闭了。我现在在用的时候，就很担心会误点到关闭的图标。如果不想增加自定义提示，那是否可以把提示的路由地址改成页标题？这样基本上就够用了~~  
  我个人看法~~~  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人: ***@***.***&amp;amp;gt;;   
  发送时间: 2023年4月13日(星期四) 下午3:47  
  收件人: ***@***.***&amp;amp;gt;;   
  抄送: ***@***.***&amp;amp;gt;; ***@***.***&amp;amp;gt;;   
  主题: Re: [masastack/MASA.Blazor] [Bug Report]: PageTabs 支持自定义提示框 (Issue #1225)  
   
   
   
   
   
     
  PageTabs 能不能增加一个参数来判断是否需要打开提示框来确认关闭

**Comment by protossman** [comment]
感谢回复，我还想问一下每次我启动项目后，页面导航栏都会直接出现一个路径为 "/" 的空页面出来，请问一下应该怎么解决这个问题？




永恒的终结
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "masastack/MASA.Blazor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月13日(星期四) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [masastack/MASA.Blazor] [Bug Report]: PageTabs 支持自定义提示框 (Issue #1225)





 @using BlazorComponent.I18n @inject I18n I18n void Example() {    I18n.SetCulture("zh-CN");//将语言切换成zh-CN    var home = I18n.T("Home");//获取键值Home对应语言的值，此方法调用将返回"首页"; } 
 官网资料有，切换一下语言即可 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "masastack/MASA.Blazor"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2023年4月13日(星期四) 下午4:17 
 ***@***.***&amp;gt;; 
 ***@***.******@***.***&amp;gt;; 
 主题:&amp;nbsp;Re: [masastack/MASA.Blazor] [Bug Report]: PageTabs 支持自定义提示框 (Issue #1225) 
 
 
 
 
 
  我还想请问这个弹出框的中文化是怎么设置的？是要在zh-CN.json里面设置对应的中文吗？  
   
   
  永恒的终结  
  ***@***.***  
   
   
   
  &amp;amp;nbsp;  
   
   
   
   
  ------------------&amp;amp;nbsp;原始邮件&amp;amp;nbsp;------------------  
  发件人:                                                                                                                        "masastack/MASA.Blazor"                                                                                    ***@***.***&amp;amp;gt;;  
  发送时间:&amp;amp;nbsp;2023年4月13日(星期四) 下午3:52  
  ***@***.***&amp;amp;gt;;  
  ***@***.******@***.***&amp;amp;gt;;  
  主题:&amp;amp;nbsp;Re: [masastack/MASA.Blazor] [Bug Report]: PageTabs 支持自定义提示框 (Issue #1225)  
   
   
   
   
   
   从目前我使用的角度来看，不太建议有这个设置，因为如果不弹窗提示，万一是提交数据的窗口，那就直接被关闭了。我现在在用的时候，就很担心会误点到关闭的图标。如果不想增加自定义提示，那是否可以把提示的路由地址改成页标题？这样基本上就够用了~~   
   我个人看法~~~   
     
     
     
     
   ------------------&amp;amp;amp;nbsp;原始邮件&amp;amp;amp;nbsp;------------------   
   发件人: ***@***.***&amp;amp;amp;gt;;    
   发送时间: 2023年4月13日(星期四) 下午3:47   
   收件人: ***@***.***&amp;amp;amp;gt;;    
   抄送: ***@***.***&amp;amp;amp;gt;; ***@***.***&amp;amp;amp;gt;;    
   主题: Re: [masastack/MASA.Blazor] [Bug Report]: PageTabs 支持自定义提示框 (Issue #1225)   
     
     
     
     
     
       
   PageTabs 能不能增加一个参数来判断是否需要打开提示框来确认关闭
