### ISSUE TITLE
DataTable组件不支持Row的双击事件吗？

### ISSUE THREAD

**Issue by differmyth** [masastack/MASA.Blazor#1236]
DataTable组件不支持Row的双击事件吗？

**Comment by capdiem** [comment]
@differmyth 抱歉，应该是缺失了，近期补一下。

**Comment by differmyth** [comment]
辛苦了~~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月15日(星期六) 晚上7:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [masastack/MASA.Blazor] DataTable组件不支持Row的双击事件吗？ (Issue #1236)





 
@differmyth 抱歉，应该是缺失了，近期补一下。

**Comment by differmyth** [comment]
thanks very much~~~~~~
