### ISSUE TITLE
MSelect component adds property controller to enable Newline

### ISSUE THREAD

**Issue by MapleWithoutWords** [masastack/MASA.Blazor#1239]
当我的宽度比较小的时候，MSelect选择完数据则会出现换行。如果MSelect作为搜索放入到搜索栏的话，宽度比较小的时候，换行会导致布局有问题。例如：
![image](https://user-images.githubusercontent.com/38368335/232374406-236e7f9f-abfc-47c8-9e4d-7c9d85f15cee.png)
我在想能否加个属性控制，我这个时候不启动换行，超出就隐藏掉，不然我可能需要额外增加样式去控制它

**Comment by capdiem** [comment]
设置MinHeight就能解决你的问题了吧，如果是简单的样式我不建议用增加新的属性来控制。

**Comment by doddgu** [comment]
我觉得这个是宽度过小本身的问题
