### ISSUE TITLE
[Bug Report]: 鼠标在Ratings组件上触发hover时的cpu占用接近100%

### ISSUE THREAD

**Issue by choby** [masastack/MASA.Blazor#1253]
### Masa.Blazor version

0.6.0

### Describe the bug

进入组件官网demo页面：[https://docs.masastack.com/blazor/components/ratings#usage](https://docs.masastack.com/blazor/components/ratings#usage)后，在demo展示的红框区域移动鼠标并进行性能监听：
![image](https://user-images.githubusercontent.com/13461239/233287340-f6a14637-6ddf-4cbf-97eb-f4c234c4e314.png)

将鼠标在红框内左右持续移动，此时观察CPU占用率飙升到接近100%，并随鼠标移动时间持续：
![image](https://user-images.githubusercontent.com/13461239/233287720-6b09077a-0e0e-4be1-8781-88b0f30e65fe.png)

测试硬件: macbook pro m2 max
测试操作系统：macos 13.3.1 
测试浏览器：microsoft edge 112.0.1722.48

**Comment by capdiem** [comment]
@choby 感谢联系我们，它将在`1.0.0-rc.3`中修复。

之前未启用`Hover`属性时也会不断的触发渲染，这个问题可以解决。但开启`Hover`之后，从技术角度上说，很难完全解决cpu占比高的问题，因为鼠标移动后需要判断并渲染，渲染就会消耗cpu。目前只能通过对mousemove事件节流(16ms)来优化。
