### ISSUE TITLE
[Bug Report]: markdown-upload 上传文件错误

### ISSUE THREAD

**Issue by MaybeEleven** [masastack/MASA.Blazor#1258]
### Masa.Blazor version

1.0.0-preview.16

### Describe the bug

markdown 上传文件错误；
![QQ截图20230421140851](https://user-images.githubusercontent.com/69737443/233553894-f934ddb7-eb2f-41c3-a265-5ae8c262bacf.png)

下边是我的配置：
![image](https://user-images.githubusercontent.com/69737443/233554158-a2fc0d50-cf7c-4888-bef8-deae3be33a96.png)

### .NET version

.net6

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by capdiem** [comment]
@wzh425 Please take a look

**Comment by doddgu** [comment]
![image](https://user-images.githubusercontent.com/7299249/233588668-b784120c-2e9f-4725-8286-71c1c95a48d7.png)
这个options跳的地址不对，应该是 https://ld246.com/article/1549638745630#options-upload

然后看这里,input accept
![image](https://user-images.githubusercontent.com/7299249/233588806-0c572c57-1209-4f3c-ba15-0bb8fae53492.png)

再看 w3schools 的定义

![image](https://user-images.githubusercontent.com/7299249/233588900-8bb63b78-f57a-40e6-886f-b01431adc7ab.png)

**Comment by capdiem** [comment]
@doddgu 只要更新文档就可以关闭此issue了吗？

**Comment by doddgu** [comment]
@capdiem  是的
