### ISSUE TITLE
MDataTable 组件，当DataTableHeader 设置Align= DataTableHeaderAlign.End 时，会出现2个排序箭头

### ISSUE THREAD

**Issue by byg168** [masastack/MASA.Blazor#1264]
### Masa.Blazor version

1.0.16

### Describe the bug

MDataTable 组件，当DataTableHeader 设置Align= DataTableHeaderAlign.End 时，会出现2个排序箭头
![image](https://user-images.githubusercontent.com/68424303/233763916-12ccf800-16fd-49cd-a4ee-d23eb0dc37b1.png)
![image](https://user-images.githubusercontent.com/68424303/233763925-77a028bc-2398-4502-a83e-52927715b834.png)

**Comment by capdiem** [comment]
Thanks for contacting us, it would be fixed in `1.0.0-rc.3`.
