### ISSUE TITLE
[Bug Report]: MAUI Blazor中，窗口宽度改变时，MTabs闪烁

### ISSUE THREAD

**Issue by Yu-Core** [masastack/MASA.Blazor#1265]
### Masa.Blazor version

1.0.0-preview.16

### Describe the bug

只存在MAUI Blazor中，Blazor Wasm正常。
窗口宽度改变时，MTabs闪烁，疑似是出现了分页符

https://user-images.githubusercontent.com/96511239/233808057-fcbaf304-f325-4507-b87e-0ffd585cb671.mp4

### Expected Behavior

MTabs能正常工作，窗口宽度改变时，不再闪烁。

### Steps To Reproduce

VS 17.5.4
创建MAUI Blazor项目
选择.NET 7
安装Masa Blazor

```
<MTabs>
        <MTab>
            All
        </MTab>
        <MTab>
            Tag
        </MTab>
    </MTabs>
```

[https://github.com/Yu-Core/MTabsBug](https://github.com/Yu-Core/MTabsBug)

### .NET version

.NET 7

当我把这个注释掉时，它不会闪烁
![image](https://user-images.githubusercontent.com/96511239/233808408-5e4e03fd-521a-498c-acc3-56ec26f70409.png)

**Comment by capdiem** [comment]
@Yu-Core Please upgrade to 1.0.0-rc.2 and try again

**Comment by Yu-Core** [comment]
OK，The problem has been resolved
