### ISSUE TITLE
【UI组件】Application - 无障碍模块缺失 

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Blazor#127]
UI组件 - Application ；无障碍模块缺失
![应用程序 - 无障碍模块缺失](https://user-images.githubusercontent.com/95004531/146482459-570c600d-d241-4407-8395-9c0bfb0ad944.png)

**Comment by wangzengxing** [comment]
we don't supported this feature now.

**Comment by doddgu** [comment]
#194

**Comment by capdiem** [comment]
未来会统一处理。
