### ISSUE TITLE
[Bug Report]: MDataTable  设定Height 值   和  ItemsPerPage  较大值（100） 运行后用鼠标来回滚动记录，点击“Action”菜单 卡死几秒钟。可以在工程模板的UserList界面复现

### ISSUE THREAD

**Issue by Joezhang1980** [masastack/MASA.Blazor#1270]
### Masa.Blazor version

0.6.0

### Describe the bug

[Bug Report]: MDataTable  设定Height 值   和  ItemsPerPage  较大值（100） 运行后用鼠标来回滚动记录，点击“Action”菜单 卡死几秒钟。可以在工程模板的UserList界面复现

**Comment by capdiem** [comment]
Duplicate of #1075
