### ISSUE TITLE
[Bug Report]: MAUI中BackgroundColor无效

### ISSUE THREAD

**Issue by sunday866** [masastack/MASA.Blazor#1273]
### Masa.Blazor version

1.0.0 p17

### Describe the bug

从0.6.0升级到1.0.0之后，发现TextField、和Tab的BackgroundColor设置无效

**Comment by sunday866** [comment]
m-avatar 背景图颜色无效

**Comment by capdiem** [comment]
@sunday866 Avatar用Color设置背景颜色。
