### ISSUE TITLE
I hope Masa can provide the search bar component which can intergrate scanning event.

### ISSUE THREAD

**Issue by grantcy** [masastack/MASA.Blazor#1287]
I hope Masa can provide the search bar component which can intergrate scanning event.

The optional scanning event which can be support description as follows:
1. WeChat QR code scanning
2. Local camera (decoded through third-party libraries)
3. PDA Scan Broadcast (by Android)

PDA Scan Code Broadcast Example Code:

//定义事件
    public class ScannerReceiver
    {
        public static ScannerReceiver scannerReceiver { get; set; }
        public Action<string> OnScanReceive { get; set; }
    }

//注册广播
namespace xxx.Platforms.Android
{
    [BroadcastReceiver(Enabled = true)]
    [IntentFilter(new[] { "com.android.server.scannerservice.broadcast" })]
    public class ScannerBroadcastReceiver : BroadcastReceiver 
    {
        public override void OnReceive(Context context, Intent intent)
        {
            if(intent.Action.Equals("com.android.server.scannerservice.broadcast"))
                scannerReceiver.OnScanReceive(intent.GetStringExtra("scannerdata"));
        }
    }
}

//活动页面实现
public class MainActivity : MauiAppCompatActivity
    {
        
        ScannerBroadcastReceiver receiver;

        protected override void OnCreate(Bundle savedInstanceState)
        {
            base.OnCreate(savedInstanceState);
            receiver = new ScannerBroadcastReceiver();
        }

        protected override void OnResume()
        {
            base.OnResume();
            RegisterReceiver(receiver, new IntentFilter("com.android.server.scannerservice.broadcast"));
        }

        protected override void OnPause()
        {
            UnregisterReceiver(receiver);
            base.OnPause();
        }
    }

**Comment by sunday866** [comment]
可以更详细的说一下吗，Android pda的那种激光扫码是可以支持的，摄像头的扫码也是可以支持

**Comment by grantcy** [comment]
做一个搜索组件 内容输入方式 支持扫描录入 可选使用 摄像头、微信扫码、PDA扫码

**Comment by grantcy** [comment]
具体 扫码的实现我们自己写代码 能绑定到搜索组件 有按钮或事件交互即可

**Comment by capdiem** [comment]
@grantcy 那不难呀，你结合Toolbar组件和TextField组件就能做到，可选扫描如果是移动端，可以用BottomSheet组件里面套个List来渲染哪种扫描。
