### ISSUE TITLE
关于资源引用问题

### ISSUE THREAD

**Issue by mysolisoft** [masastack/MASA.Blazor#1294]
如何实现不用CDN资源，而用本地资源。

**Comment by capdiem** [comment]
@mysolisoft 模板提供了本地资源，安装后_wwwroot/css_里有。
``` shell
dotnet new install Masa.Template::1.0.0-rc.1
dotnet new masablazor-server -o BlazorApp
```

或者在 [Masa.Template](https://github.com/masastack/MASA.Template/tree/main/src/Content/BlazorServer/wwwroot/css) 仓库下载。

**Comment by doddgu** [comment]
或许可以像masa blazor pro一样增加 cdn 参数

**Comment by capdiem** [comment]
@doddgu 提供了

**Comment by doddgu** [comment]
那直接回复例如 `dotnet new masablazor-server cdn:false -o Blazor App` 这种就好了。当然我这个是伪代码。

**Comment by capdiem** [comment]
@doddgu 默认模板就引用本地资源的

**Comment by doddgu** [comment]
ok，那先关闭了，有问题可以在reopen
