### ISSUE TITLE
[Bug Report]: 富文本编辑器特别文本冲突时，最终内容显示不全。

### ISSUE THREAD

**Issue by justmine66** [masastack/MASA.Blazor#1298]
### Masa.Blazor version

0.6.2

### Describe the bug

有问题的文本：
\n\n1. 将原子核中的质子和中子分离，这一步可以通过核裂变或核聚变来实现。\n\n2. 将分离出来的质子和中子组装成原子核，这一步可以通过核合成反应来实现。\n\n3. 将原子核与电子结合，形成原子，这一步可以通过电离反应来实现。

由于包含 . 只识别出了一个 <li> 标签，效果如图：
![image](https://user-images.githubusercontent.com/23122801/236411348-fd9c67f9-5db2-4572-8531-f7b1d60b13a9.png)

**Comment by capdiem** [comment]
@wzh425 Please take a look

**Comment by wzh425** [comment]
<img width="938" alt="企业微信截图_16832763213783" src="https://user-images.githubusercontent.com/13762077/236415837-3333e9cc-23ad-47a6-91e0-acea9720f8a1.png">
 @justmine66  1.0.0上没有复现 如果可以请升级到1.0.0-rc.1看看

**Comment by doddgu** [comment]
> <img alt="企业微信截图_16832763213783" width="938" src="https://user-images.githubusercontent.com/13762077/236415837-3333e9cc-23ad-47a6-91e0-acea9720f8a1.png">
> 
> @justmine66 1.0.0上没有复现 如果可以请升级到1.0.0-rc.1看看

他是把换行给转义了吧？但你的是把换行符原样输出了

**Comment by wzh425** [comment]
![image](https://user-images.githubusercontent.com/13762077/236600103-fc75ef28-8e98-45b4-9239-a8619c909486.png)
 @justmine66  能否提供下能复现的代码
