### ISSUE TITLE
[Bug Report]: MInfiniteScroll 的 Parent 属性设置到布局元素时出错

### ISSUE THREAD

**Issue by Asttear** [masastack/MASA.Blazor#1301]
### Masa.Blazor version

1.0.0-rc.1

### Describe the bug

在布局中定义的容器不能作为 MInfiniteScroll 的 Parent，否则会在切换页面时报错，无限滚动同时失效。

### Steps To Reproduce

布局组件中：
```razor
...
<MRow Class="overflow-y-auto" Style="height: 100%" @ref="_container">
    @Body
</MRow>
...
@code {
    MRow? _container;

    internal ElementReference ContainerRef => _container!.Ref;
    ...
}
```
页面中：
```razor
<MInfiniteScroll Parent="Layout.ContainerRef" ... />
```

### .NET version

7

### What browsers are you seeing the problem on?

Microsoft Edge

### Additional context

原因可能是 BInfiniteScroll 没有在销毁时删除监听事件。

**Comment by capdiem** [comment]
@Asttear 感谢反馈，原因是增加监听事件时父元素还没有渲染完成，导致监听事件没有添加成功。RC2会修复此问题。
