### ISSUE TITLE
Popup service 增加Dialogs弹出

### ISSUE THREAD

**Issue by aa126324** [masastack/MASA.Blazor#1332]
Popup service 增加Dialogs弹出,目的是在http时弹出loading ,目前Timeout设置也不生效，设置了还是默认的5秒

**Comment by capdiem** [comment]
@aa126324 你是想让我们提供一个全局loading的service吗？你目前是如何做的？

另一种途径是在MainLayout埋点，放一个Loading的Dialog。请求前把dialog显示出来，请求结束或异常后把dialog隐藏。

**Comment by aa126324** [comment]
目前还没做，正在搭建架子，就是需要个全局的loading 就是vue那种挂在上去的&nbsp; 任何地方都可以用,这个loading&nbsp; &nbsp;dailogs 全局很实用，建议弄一个

王成
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "masastack/MASA.Blazor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 下午2:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [masastack/MASA.Blazor] Popup service 增加Dialogs弹出 (Issue #1332)





 
@aa126324 你是想让我们提供一个全局loading的service吗？你目前是如何做的？
 
另一种途径是在MainLayout埋点，放一个Loading的Dialog。请求前把dialog显示出来，请求结束或异常后把dialog隐藏。

**Comment by capdiem** [comment]
@aa126324 可以提供vue使用全局loading的例子吗？

**Comment by aa126324** [comment]
王成
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "masastack/MASA.Blazor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月24日(星期三) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [masastack/MASA.Blazor] Popup service 增加Dialogs弹出 (Issue #1332)





 
@aa126324 可以提供vue使用全局loading的例子吗？

**Comment by capdiem** [comment]
@aa126324 没看到附件，找个链接也行。

**Comment by aa126324** [comment]
https://blog.csdn.net/weixin_46547740/article/details/119569842




---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月24日(周三) 下午2:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [masastack/MASA.Blazor] Popup service 增加Dialogs弹出 (Issue #1332)




 
@aa126324 可以提供vue使用全局loading的例子吗？
