### ISSUE TITLE
[Bug Report]: 主界面跳转到新界面MTextField组件输入值，失去焦点后问题出现

### ISSUE THREAD

**Issue by buaishi** [masastack/MASA.Blazor#1336]
### Masa.Blazor version

rc2

### Describe the bug

目标界面：
![8b47233d06dac05865fbda7e436cbe1](https://github.com/masastack/MASA.Blazor/assets/44238502/36ac4e39-1833-4257-a588-3a81c88dc882)
![image](https://github.com/masastack/MASA.Blazor/assets/44238502/6ac2c757-4090-4605-9615-52821edd1a0b)

绑定的值也取不到
（主界面：
![image](https://github.com/masastack/MASA.Blazor/assets/44238502/414d1a52-a2e8-4bde-8c30-42fd5b62f46d)
）
切换到稳定版0.6.2正常显示值也能取到值

### Steps To Reproduce

主界面跳转到新界面MTextField组件输入值，失去焦点后问题出现

### .NET version

6

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by capdiem** [comment]
@buaishi 我用了一下简单的代码，没办法复现，你能提供更详细的代码结构吗？

``` razor
<button @onclick="OnClick">button</button>
@code {
    private void OnClick()
    {
        NavigationManager.NavigateTo("/test", true);
    }
}
```

```razor
<MTextField Label="QQ" @bind-Value="value"></MTextField>

@code {
    private string value;
}
```

**Comment by buaishi** [comment]
- 默认根目录跳转首页

![image](https://github.com/masastack/MASA.Blazor/assets/44238502/dfbaae57-c04a-4d51-bec7-ca8e681d3ddf)

- 首页界面

![image](https://github.com/masastack/MASA.Blazor/assets/44238502/9986e301-5705-4390-abb2-55a88df2d827)


- 首页跳转子页

![image](https://github.com/masastack/MASA.Blazor/assets/44238502/a2eaf99f-9f7f-44f4-84f4-b8a0bc513332)

- 子页界面

![image](https://github.com/masastack/MASA.Blazor/assets/44238502/2b72d698-7435-4b6c-babb-2daf371dabf1)

**Comment by capdiem** [comment]
@buaishi 没看出来会是什么问题。必现的吗？Server还是WebAssembly？线上还是本地开发？根据以往的经验，还有可能是网络太慢的原因。

**Comment by buaishi** [comment]
必现 wasm 本地 必现的话网络原因可能就小了，不知道是不是和硬件设备有关，要不就先这样吧如果后面有人遇到了再说

**Comment by capdiem** [comment]
@buaishi Wasm下仍然没有复现
