### ISSUE TITLE
建议增加多一点基于移动端的组件

### ISSUE THREAD

**Issue by sagavov** [masastack/MASA.Blazor#1349]
近期在使用Masa基于MAUI Blazor做一个APP。
整体使用下来感觉MASA很不错。就是移动端的组件稍微少了点。
建议增加一些移动端组件。

以前基于Vue写H5的时候用过一个Vant的移动端组件库，感觉里面的组件可以参考下。

**Comment by capdiem** [comment]
@sagavov 你可以把缺少的组件和链接也列在此issue下。

**Comment by capdiem** [comment]
@sagavov 目前已经添加了可以在移动端使用的 InfiniteScroll、PullRefresh、Swiper、MobileCascader、MobilePickers等等。如果有具体的需求请提新的issue，此issue先关闭了。
