### ISSUE TITLE
This Will Make Package Better

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1356]
Your Tabs And Expansion Is To Slow Cause There Animations And It Load All Once I Want Like Viruiztion When Dom Does Not Take Big Big Objects Cause I Have 8 Tabs In My App And I Wait For Page 10 seconds For It To Load Cause Each Tab Has Big Content I Think You Have To Make Somthing Like {LoadAllTab = false or DontLoadAllTab} For Package And

Auto MCol To Make MInput Takes Cols ,Sm and Md And Make It As Class In Object And Make AutoTranslate For Label And This Will Make 1.0.0 rc-4 Better Version And It Will Save 2 Lines For Every TextField And Thanks

**Comment by capdiem** [comment]
> Your Tabs And Expansion Is To Slow ...

Do you mean the `MTab` component? It's just a title, and it doesn't usually contain much logic. 
The `MExpansions` component does not use delayed loading, so it does have an optimization direction.

> Auto MCol To Make MInput Takes Cols ,Sm and Md And Make It As Class In Object And Make AutoTranslate For Label ...

I don't quite understand. Maybe you can do it yourself with a secondary encapsulation.

```cs
public class TextField: MTextFIeld {
    protected override void OnParametersSet() {
        Label = ...
    }
}
```

**Comment by wisamidris7** [comment]
Tab Item

**Comment by capdiem** [comment]
@wisamidris7  MTabsItems is already lazy to load and does not load all the DOM at once

**Comment by wisamidris7** [comment]
How to make this scrollable Cause Like This Is Not Right Specially In Mobile

![Screenshot 2023-06-06 154634](https://github.com/masastack/MASA.Blazor/assets/104096256/199692d8-309d-4c09-9c69-08a1083750f5)

![Screenshot 2023-06-06 154722](https://github.com/masastack/MASA.Blazor/assets/104096256/1af15928-eeb3-4638-b1cc-3de0fbaa31da)

The Same Template In Yours Modal Docs Form

**Comment by wisamidris7** [comment]
I Want Some thing Like Make It Scrollable I Tried To Make It But I Did't Get Result

**Comment by wisamidris7** [comment]
I Mean You Can Also Provide Me A CSS Code

**Comment by capdiem** [comment]
There are some problems with Autocomplete in Dialog... Thanks for your feedback.

If you just want the content scrollable:

```razor
@inject MasaBlazor MasaBlazor

<MAutocomplete MenuProps="MenuProps">
</Autocomplete>

@code {
    private void MenuProps(BMenuProps props) {
        if (MasaBlazor.Breakpoint.SmAndDown) {
           props.MaxHeight = 150;
        }
    }
}
```

**Comment by wisamidris7** [comment]
But About Lazy Loading Is I Used Expansion 
And It Load All Once

![Screenshot 2023-06-07 150828](https://github.com/masastack/MASA.Blazor/assets/104096256/ce611e69-0a90-4abd-afa0-b3d7c3e99b1c)

If There Some Option You Can Provide Me With It

**Comment by wisamidris7** [comment]
MTextField Is Call ValueChanged For Every Character I Wrote

And When I Make It On OnParameterSet It's Render In Just 4 Chars

Somtimes 27 to 47 Cause For Every Char I Wrote The Parameter Change Cause
ValueChanged Set Value And When Value Set The OnParameterSet Got Called

And What I Think Of That I Might Make It On OnInit...
And Also Did't Cause Label Will Set Every Time Cause He Compair The CurruntValue And SettedValue

And I Maked Name Prop
And I Make It Like This {Name="firstname"}
And I Tired To Change All App From Label To Name
Cause If I CHange Label I Have Some Components That Like Modal
I Have Label In Top Like This So I Don't Know What I Do
And When I Run It Webassebly It Laggggged So Much
I Click At TextField And I Wrote A Char And I Wait One Second

You Should See What Makes Webassembly Laggged Cause
The Browser Not So Powerfully To Get From 100 to 200 Item To Translate One Word

**Comment by capdiem** [comment]
@wisamidris7 **ExpansionPanelContent** will support for lazy loading in `1.0.0-rc.4`.

**Comment by capdiem** [comment]
> MTextField Is Call ValueChanged For Every Character I Wrote
> 
> And When I Make It On OnParameterSet It's Render In Just 4 Chars
> 
> Somtimes 27 to 47 Cause For Every Char I Wrote The Parameter Change Cause ValueChanged Set Value And When Value Set The OnParameterSet Got Called
> 
> And What I Think Of That I Might Make It On OnInit... And Also Did't Cause Label Will Set Every Time Cause He Compair The CurruntValue And SettedValue
> 
> And I Maked Name Prop And I Make It Like This {Name="firstname"} And I Tired To Change All App From Label To Name Cause If I CHange Label I Have Some Components That Like Modal I Have Label In Top Like This So I Don't Know What I Do And When I Run It Webassebly It Laggggged So Much I Click At TextField And I Wrote A Char And I Wait One Second
> 
> You Should See What Makes Webassembly Laggged Cause The Browser Not So Powerfully To Get From 100 to 200 Item To Translate One Word

Sorry, I only understand a little bit. Is MTextField Slow? Maybe provide the TEST code?

If you want to know how to automatically generate Label, you refer to the following code:

```cs
public class TextField : MTextField<string>
{
    protected override void OnParametersSet()
    {
        base.OnParametersSet();

        if (Label is null && ValueExpression is not null)
        {
            var accessorBody = ValueExpression.Body;

            if (accessorBody is UnaryExpression unaryExpression
                && unaryExpression.NodeType == ExpressionType.Convert
                && unaryExpression.Type == typeof(object))
            {
                accessorBody = unaryExpression.Operand;
            }

            var fieldName = (accessorBody as MemberExpression)!.Member.Name;
            Label = fieldName;
        }
    }
}
```

**Comment by wisamidris7** [comment]
About TextField I Mean That It Slow When I Make This
`
1 public class TextField: MTextFIeld {
2     protected override void OnParametersSet() {
3        Label = i18n.T(Label); // This Line It Lagged Cause He Search In Directory About This Word 
4     }
5 }
`
I Readed You i18n code i found that you make all words in Dictionary And This Good
But Every Word I Wrote It Load From Dictionary 2 times and this make textfield slow in webassembly
but in server-side my server will be also slow or attacked as i name it

You MTextFIeld Is Good
But New TextField Is Bad Becuase Line 3

**Comment by capdiem** [comment]
@wisamidris7 I seem to have reproduced the problem, I will investigate this tomorrow. Thanks!

**Comment by wisamidris7** [comment]
ok thanks

**Comment by wisamidris7** [comment]
I Just Want To Tell You To Not Use Many Dicentory
Here Example
![WSM](https://github.com/masastack/MASA.Blazor/assets/104096256/28eb3e12-565c-4f5a-b9b2-38698f22861a)

![sScreenshot 2023-06-07 121223](https://github.com/masastack/MASA.Blazor/assets/104096256/2c12da23-8297-4d09-8257-fb85d5ac9569)

**Comment by capdiem** [comment]
@wisamidris7 Twice for every word you type? I guess there are two TextFields on your page. 

There seems to be no way to improve the performance of `I18n.T`. I do not feel slow when using it. Avoid to search from dictionary when you type:
```cs
private string? _i18nLabel;
private string? _prevLabel;

protected override void OnParametersSet()
{
    base.OnParametersSet();

    if (_prevLabel != Label)
    {
        _prevLabel = Label;
        _i18nLabel = I18n.T(Label);
    }

    Label = _i18nLabel;
}
```

**Comment by capdiem** [comment]
```razor
<TextField @bind-Value="value1" />
<TextField @bind-Value="value2" />
<TextField Value="value3" />
```

when input the first TextField, a `StateHasChanged` would be invoked, so the secondary TextField will re-render and it's OnParametersSet will be invoked. `@bind-Value` contains a `ValueChanged` parameter, it's not a value type, so secondary textfield will be rendered. The third TextField would not re-render.

**Comment by wisamidris7** [comment]
Thanks 👍

In Any Date 1.0.0-rc4 Will Reaslse

**Comment by capdiem** [comment]
@wisamidris7 next week

**Comment by wisamidris7** [comment]
Can You Make Helper Or Vaildation Text Doesn't Take Space In Form
Just When Message Are Not Empty

You Can Make IsPopup For Popup For Vaildation Text To Be position: absoulte

Or You Can Show Helper Text Or Vaildation Text If There Text

And Now What I Maked HideDetails For Message But 

And This Is My Suggestion Cause I Want Users Know What Problem

**Comment by wisamidris7** [comment]
![Screenshot 2023-06-11 100921](https://github.com/masastack/MASA.Blazor/assets/104096256/f1357288-6ab7-4096-a79f-54610ae9f5ba)

This What Now Looks Like And This Not Good

**Comment by wisamidris7** [comment]
Also Can You Provide Me Code To Make Page Tabs or Page Contaniner Know That

localhost:5001/example This Page
localhost:5001/example?name=123 Also This In Sprit Page

What PageTabs Or PageContaniner Is Not Know If 'localhost:5001/example?name=123' is other page
Cause I Think There StartsWith

So Give Me A Code I Can Make It And I Want In Logout To Clear Pages Or Tabs I Can't Cause Tabs or pages in private or internal I Can't Access Make Me A pageTabs.ClearTabs() Or pageContainer.ClearPages()

![code](https://github.com/masastack/MASA.Blazor/assets/104096256/dd981cfc-e9ce-4a9f-ae98-ad3608fd20f9)

![Screenshot 2023-06-11 150901](https://github.com/masastack/MASA.Blazor/assets/104096256/6304d788-a987-484f-8913-73eef81a849c)

Are Self Pattern Has Any Relation With This Cause Self Pattern Is Empty. I Mean Null

**Comment by wisamidris7** [comment]
Also Here Bug When Closing Tab The Data Not Be Deleted Or When I Open Again I See Same Data When I Closed

**Comment by capdiem** [comment]
@wisamidris7 

> Can You Make Helper Or Vaildation Text Doesn't Take Space In Form

`HideDetails` accept a bool value and a string value **auto**.  Use `HideDetails="@("auto")"`. You can use [DefaultsProvider](https://docs.masastack.com/blazor/components/defaults-providers) make **auto** as default.

> What PageTabs Or PageContaniner Is Not Know If 'localhost:5001/example?name=123' is other page

_/example_ and _/example?name=123_ would be recognized as the same page, because the query parameters are ignored. _/example/{name?}_ is recommend to use.

> So Give Me A Code I Can Make It And I Want In Logout To Clear Pages Or Tabs I Can't Cause Tabs or pages in private or internal I Can't Access Make Me A pageTabs.ClearTabs() Or pageContainer.ClearPages()

Good point. I will expose a public method `ClearAll` from PageTabs.

> Also Here Bug When Closing Tab The Data Not Be Deleted Or When I Open Again I See Same Data When I Closed

How to repro?

**Comment by wisamidris7** [comment]
I Mean By When I Close Page The Page Not Reset When I Open Again

When I Open /example Page I Write 123 In Input And When I Click Close And Open Again 123 Been Writed in TextField

**Comment by wisamidris7** [comment]
And Make PageTabs.???
Make Custom Cause Sometimes I Want To Make Button Quit In Page And I Don't Know What To Make In OnCLick

RemoveByPattern
RemoveAll

Thanks

**Comment by capdiem** [comment]
> When I Open /example Page I Write 123 In Input And When I Click Close And Open Again 123 Been Writed in TextField

please check to see if the DOM(`.m-window-item`) was deleted after close was clicked.

> Make Custom Cause Sometimes I Want To Make Button Quit In Page And I Don't Know What To Make In OnCLick

Do you mean the ref of PageTabs should provide some public methods, such as `ClearAll`? Do you try to right click on the tab?

**Comment by wisamidris7** [comment]
Yes Also The Animation In MTabs Are Not Good With RTL

**Comment by wisamidris7** [comment]
> Sometimes

What I Do To Make Page Reset On Close

**Comment by wisamidris7** [comment]
> Do you mean the ref of PageTabs should provide some public methods, such as ClearAll?

Also I Want Two Methods Cause This So Important For Me

<code>
public void RemoveAllTabs() { }
public void RemoveCurruntTab() { } // This You Can Replace It By RemoveByPattern
public void RemoveByPattern(??? route) { }
</code>

This Important

**Comment by capdiem** [comment]
@wisamidris7 
> Yes Also The Animation In MTabs Are Not Good With RTL

You may be our first RTL user and I need to check that RTL is fully supported.

> What I Do To Make Page Reset On Close

The html DOM of page should be deleted after closing tab. Could you check to see if it has been deleted, please?
![image](https://github.com/masastack/MASA.Blazor/assets/16507773/1c7dbe27-7f2a-4a8f-8945-6cc48bc8e40f)

> Also See Here I Wrote Here The Translations Of Words

You can pull request to us for your language. For example the [en-US](https://github.com/masastack/BlazorComponent/blob/main/src/Component/BlazorComponent/I18n/Locales/en-US.json#L79 )

**Comment by capdiem** [comment]
RTL #1369

**Comment by wisamidris7** [comment]
In Tooltip Or Menu You Can Make Some Action

```c#
public Action OpenMenu { get; set; } // Cause I Want To Use Just On Focus I Just Have Attr
```
Cause Here I Want Just When I Hover Not In Focus
```razor
<MTooltip Bottom>
        <ActivatorContent>
            <MTextField
                   @bind-Value="someValue"
                   @attributes="context.Attrs"
                   Label="Example" />
        </ActivatorContent>
        <ChildContent>
            @* Some Code *@
        </ChildContent>
    </MTooltip>
```
In Here
> @attributes="context.Attrs"
I Can't Said Just In Hover
Also I Needed This In Other Places

**Comment by wisamidris7** [comment]
I Know There

```razor
<MTooltip Bottom OpenOnFocus=false>
```

But I Needed By Other Causes

**Comment by wisamidris7** [comment]
> The html DOM of page should be deleted after closing tab. Could you check to see if it has been deleted, please?

I Checked It And I Fix It Thanks

**Comment by capdiem** [comment]
@wisamidris7 you can use `@bind-Value` to control the tooltip and menu.  https://docs.masastack.com/blazor/components/tooltips#visibility

**Comment by wisamidris7** [comment]
![Screenshot 2023-06-14 082357](https://github.com/masastack/MASA.Blazor/assets/104096256/1987460c-eced-4d81-af53-e0deb3047122)

Are There Eager Loading For MTabs
Try It With Your Self https://github.com/wisamidris7/MasaTestProject

> https://github.com/wisamidris7/MasaTestProject

This Template To Test

**Comment by wisamidris7** [comment]
Can You Tell Me How I Can Make Snackbar At Left Using PopupService

**Comment by wisamidris7** [comment]
When Closing Popup The Animation Of Dialog Close Not End
So The ClosePopupAsync Or ClosePopup Has To 
```c#
Visible = false;
Task.Delay(100);
???
```
At Least 100 millisecond to make animation end

**Comment by wisamidris7** [comment]
You Can Make Me Branch Of Masa To 'This Will Make Package Better'
And You Can Merge It To Main If You Liked Changes

**Comment by capdiem** [comment]
> Can You Tell Me How I Can Make Snackbar At Left Using PopupService

https://docs.masastack.com/blazor/components/popup-service#snackbar

![image](https://github.com/masastack/MASA.Blazor/assets/16507773/012d8090-99d9-4504-baba-70b7eb9a802b)

**Comment by capdiem** [comment]
> Also Can You Make MHighlter For Text

Reference a new issue #1373. But this component will not be developed right away, and perhaps it will be developed some day.

**Comment by capdiem** [comment]
> When Closing Popup The Animation Of Dialog Close Not End
> So The ClosePopupAsync Or ClosePopup Has To

@wisamidris7 Which demo?

**Comment by wisamidris7** [comment]
Drawer In My Computer Is Closed When I Using Computer My Screen Size Down

1366x768

Screen Width: 1366 pixels
Screen Height: 768 pixels

When Computer The Drawer Should Not Be Closed All Time The App Looks Like In Mobile

**Comment by wisamidris7** [comment]
NavigationDrawer.razor: error CS1503: Argument 2: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback<bool>' to 'Microsoft.AspNetCore.Components.EventCallback'


```razor
<MNavigationDrawer Value="Visible" ValueChanged="VisibleChanged"
                   Class="@($"navigation {ComputedNavigationClass}")"
                   Width=300
                   MiniVariantWidth=80
                   Floating>
```

Here Is Parameters
```c#
    [Parameter]
    public bool Visible { get; set; } = true;
    [Parameter]
    public EventCallback<bool> VisibleChanged { get; set; }
```

**Comment by wisamidris7** [comment]
> Which demo?

I Mean When I Call ClosePopupAsync()
From PopupBaseComponent

animation cuts and the dialog closed fast
you has to make in ClosePopupAsync()

```c#
protected async Task ClosePopupAsync()
{
Visible = false; // This First
await Task.Delay(200); // Or 100 milliseconds
await ?????; // And Here Make Discred Or Like This
}
```

**Comment by wisamidris7** [comment]
On Here https://github.com/masastack/MASA.Blazor/issues/1356#issuecomment-1579561996

There No MenuProps In MSelect
Also This Happen On Computer I Want To Make MaxHeghit For All Devices

**Comment by capdiem** [comment]
> Drawer In My Computer Is Closed When I Using Computer My Screen Size Down

Do you mean that drawers close automatically when the browser widths narrow? I tried the [demo](https://docs.masastack.com/blazor/components/drawers) of the document and it didn't work. But I found another bug: When on the mobile side, the width of the Drawer is too long, exceeding the width of the screen.

> NavigationDrawer.razor: error CS1503: Argument 2: cannot convert from 'Microsoft.AspNetCore.Components.EventCallback' to 'Microsoft.AspNetCore.Components.EventCallback'

It's a [breaking change](https://docs.masastack.com/blazor/getting-started/upgrade-guide#mnavigationdrawer) of 1.0.0-rc.4.

> animation cuts and the dialog closed fast

It's been 256 ms: https://github.com/masastack/MASA.Blazor/blob/514ca10c19065f3b3f2881e0026a5a248d6cb244/src/Masa.Blazor/Popup/Components/PopupComponentBase.cs#L33-L40

> There No MenuProps In MSelect

![image](https://github.com/masastack/MASA.Blazor/assets/16507773/f488e954-ecea-4f5a-97c5-fd6c701afc26)

> Also This Happen On Computer I Want To Make MaxHeghit For All Devices

Use **DefaultsProvider** or use global CSS

**Comment by wisamidris7** [comment]
> It's been 256 ms:

```c#
// Here You Have To Make This
 if (PopupItem != null) 
     { 
Visible = false;
         await Task.Delay(256); 
         PopupItem.Discard(returnVal); 
     } 
```
Or
```c#
// Here You Have To Make This
 if (PopupItem != null) 
     { 
         Visible = false;
         InvokeAsync(StateHasChanged);
         await Task.Delay(256); 
         PopupItem.Discard(returnVal); 
     } 
```

**Comment by wisamidris7** [comment]
```c#
 Visible = false;
```
It's Change

**Comment by wisamidris7** [comment]
Also Check RTL Issue There I Maked Somthings

https://github.com/masastack/MASA.Blazor/issues/1369

**Comment by wisamidris7** [comment]
Also Can You Make Virtuize For DataTable

**Comment by capdiem** [comment]
> ```cs
>  Visible = false;
> ```
> 
> It's Change

https://github.com/masastack/MASA.Blazor/blob/514ca10c19065f3b3f2881e0026a5a248d6cb244/src/Masa.Blazor/Popup/Components/Prompt/Prompt.razor.cs#L75-L79

I see, you want the method **ClosePopupAsync** to set `Visible = false` internally. It's a good idea, I will change it. But the `StateHasChanged` doesn't seem to require an explicit call.

**Comment by capdiem** [comment]
> Also Can You Make Virtuize For DataTable

We received the same request #1075.

**Comment by wisamidris7** [comment]
In Select You Can Write '8 Items Selected'

And Make It With i18n Don't Forgot Also When There Just 2 Or You Can Make Max Items

Like Radzen DropDown
When There Two Names Displayed
When There Many Names '8 Items Selected'
This Will Be Soultion For That Cause This

![Screenshot 2023-06-21 150853](https://github.com/masastack/MASA.Blazor/assets/104096256/7b915dc8-ca75-4875-8ad5-03be840ffe32)
![Screenshot 2023-06-21 151521](https://github.com/masastack/MASA.Blazor/assets/104096256/bfcfcca5-fd7b-4e5c-8f7a-96732bdb3508)

**Comment by capdiem** [comment]
@wisamidris7 You can use `SelectionContent` slot to implement it. There is a [demo](https://docs.masastack.com/blazor/components/selects#selection).

**Comment by wisamidris7** [comment]
I Want To Make This On Masa Table Or MDataTable

![Screenshot 2023-06-24 093341](https://github.com/masastack/MASA.Blazor/assets/104096256/db5f7895-2f2b-431f-b32f-452b1ec802e8)

What I Want To Do Some Details Has Details
And Who Not Has Details There Not Expand Button

Cause I Has Products
And This Products Are Normal
And There One Product That Has Many Products Inside
Or You Can Name It Aggregate Product Or Assembly Product

**Comment by wisamidris7** [comment]
In The White Row There No Expand Button Cause There No Children For Him

**Comment by capdiem** [comment]
@wisamidris7 https://docs.masastack.com/blazor/components/data-tables#expandablerow Check out this demo. The point is that there is a predefined col (`new () { Text="", Value="data-table-expand" }`) in headers.

**Comment by wisamidris7** [comment]
can you make me branch name it packagebetterissue and make me as countribter for just branch 'packagebetterissue' 
and i will create pull request and you merge

**Comment by capdiem** [comment]
> can you make me branch name it packagebetterissue and make me as countribter for just branch 'packagebetterissue' and i will create pull request and you merge
> 
> this will save lot of time for me cause somethings or some features i want to add it but i can't so this will be so great

Sorry, I don't have permission to do it. You have to [fork and PR](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request-from-a-fork).

**Comment by wisamidris7** [comment]
can your masa library contain menustrip as the winform

![download](https://github.com/masastack/MASA.Blazor/assets/104096256/05b40e99-3583-403e-bf8c-2bb7bc12f94c)
 
and make it fixed as appbar do or you can make it part of the appbar cause i needed in this week

it's very important for me

**Comment by wisamidris7** [comment]
in blazor masa.blazor library

**Comment by wisamidris7** [comment]
also don't forgot Required Field For Vaildation

Cause I Want Field To Be Required When COnditional Be
Like Auto Create Somthing CheckBox When True Disible Requrired
But Else The Somthing Be Required

**Comment by capdiem** [comment]
> can your masa library contain menustrip as the winform

I think you can do the same thing with **MMenu** and **MList**.

**Comment by wisamidris7** [comment]
also in ar-EG or arabic language why not say 'save' - 'انفذ'

why say for 'save' - 'حفظ'

**Comment by wisamidris7** [comment]
wrongly you make it in past 'saved'

![Screenshot 2023-07-18 043743](https://github.com/masastack/MASA.Blazor/assets/104096256/0d1cda8b-d543-4541-8ac1-8ff60e8c63e9)
![Screenshot 2023-07-18 043807](https://github.com/masastack/MASA.Blazor/assets/104096256/baf95704-4fd1-4914-a38e-512590863648)

**Comment by capdiem** [comment]
> wrongly you make it in past 'saved'

@wisamidris7 I got it

**Comment by capdiem** [comment]
> MenuStrip example

@wisamidris7 
MenuStrip
```razor
@typeparam TItem
@typeparam TValue

<MMenu @bind-Value="@_menuValue"
       CloseOnContentClick="false"
       OffsetY
       ActivatorContent="@ActivatorContent">
    <ChildContent>
        <div class="m-cascader__columns">
            <MCascaderColumn Dense
                             Items="@Items"
                             ItemValue="@ItemValue"
                             ItemText="@ItemText"
                             ItemChildren="@ItemChildren"
                             TItem="TItem"
                             TValue="TValue"
                             OnSelect="(u) => HandleOnSelect(u.item)">
            </MCascaderColumn>
        </div>
    </ChildContent>
</MMenu>

@code {

    [Parameter]
    public RenderFragment<ActivatorProps>? ActivatorContent { get; set; }

    [Parameter]
    [EditorRequired]
    public IList<TItem> Items { get; set; } = null!;

    [Parameter]
    [EditorRequired]
    public Func<TItem, string> ItemText { get; set; } = null!;

    [Parameter]
    public Func<TItem, TValue>? ItemValue { get; set; }

    [Parameter]
    [EditorRequired]
    public Func<TItem, List<TItem>?> ItemChildren { get; set; } = null!;

    [Parameter]
    public EventCallback<TItem> OnSelect { get; set; }

    private bool _menuValue;

    private async Task HandleOnSelect(TItem item)
    {
        if (ItemChildren?.Invoke(item)?.Any() is true)
        {
            return;
        }

        if (OnSelect.HasDelegate)
        {
            await OnSelect.InvokeAsync(item);
        }

        _menuValue = false;
    }

}
```

Use:
```razor
<MenuStrip Items="_items"
          ItemText="u => u.Name"
          ItemValue="u => u.Code"
          ItemChildren="u => u.Children"
          TItem="Item"
          TValue="string"
          OnSelect="HandleOnSelect">
    <ActivatorContent>
        <span @attributes="@context.Attrs">File</span>
    </ActivatorContent>
</MenuStrip>

@code {

    record Item(string Name, string Code, List<Item>? Children = null);

    private List<Item> _items = new()
    {
        new("Item 1", "1"),
        new("Item 2", "2"),
        new("Item 3", "3"),
        new("Item 4", "4", new List<Item>()
        {
            new Item("Sub item 1", "s-1"),
            new Item("Sub item 2", "s-2"),
            new Item("Sub item 3", "s-3"),
        }),
        new("Item 5", "5"),
    };

    private void HandleOnSelect(Item item)
    {
        Console.WriteLine($"Selected item: {item.Name} ({item.Code})");
    }

}
```

**Comment by wisamidris7** [comment]
ar-EG Is RTL Why you don't Make If ar-EG Is Currunt Make It RTL

Also I Want To Make ar-EG default rather than english so provide me code

```c#
// somthing like this
config.DefaultLanguage = "ar-EG";
```

and make if drawer is app make it in right auto

**Comment by capdiem** [comment]
@wisamidris7 
```cs
@using BlazorComponent

services.AddMasaBlazor(options => {
    // new Locale(current, fallback);
    options.Locale = new Locale("ar-EG", "en-US");
    options.RTL = true;
})
```

**Comment by wisamidris7** [comment]
I Mean My App Is Mulilanguage But Arabic Is Default Cause Who Will Use Is Arab

Also When RTL Is Supported This Mean To Make Drawer Right
Also It Have Be A Auto To Check Just Arabic What Is RTL

**Comment by capdiem** [comment]
@wisamidris7 Do you mean changing RTL automatically when the language changes to Arabic? This is a good idea, but not a high priority. You can inject MasaBlazor and set MasaBlazor.RTL = true/false when you update language. https://github.com/masastack/MASA.Blazor/blob/e1dc00aadb79d0631850d7bebdb8693ee577bb98/docs/Masa.Docs.Shared/Shared/Settings.razor#L98-L108

**Comment by wisamidris7** [comment]
end story
