### ISSUE TITLE
[Bug Report]: MIcon标签配置fontawesome图标字体无效

### ISSUE THREAD

**Issue by CACerts** [masastack/MASA.Blazor#1386]
### Masa.Blazor version

1.0.0-rc4

### Describe the bug

升级1.0.0-rc4之后，MIcon标签会在class自动加入mdi，mdi是Material Design Icons的样式，导致配置fontawesome图标字体无效。采用的是模板MasaBlazorProApp的样例
```html
<MIcon>fas fa-ellipsis-v</MIcon>
````
最终生成的class如下
```html
<i class="m-icon mdi fas fa-ellipsis-v theme--light " style=";" _bl_a7f769f8-a172-4993-b51f-caf71f0336b8=""></i>
```
界面上看不到图标，尝试在浏览器DevTools去掉mdi就可以显示出来图标

### .NET version

8.0.100-preview.5.23303.2

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by capdiem** [comment]
@CACerts https://docs.masastack.com/blazor/getting-started/upgrade-guide#micon
