### ISSUE TITLE
[Bug Report]: ECharts  API Formatter  不能被正确加载

### ISSUE THREAD

**Issue by Gainlos** [masastack/MASA.Blazor#1401]
### Masa.Blazor version

1.0.0-rc4

### Describe the bug

在网页样例(https://blazor.masastack.com/blazor/components/echarts ) 中的**配置中使用 function**部分，对ECharts Formmater是这样使用的
```
AxisLabel = 
new
{ 
Formatter = "function(value, index) { return value.toUpperCase(); }"
}
```
针对EChart的scatte（散点图）格式的SymbolSize数据，我编写了如下的Formatter
```
SymbolSize=
new
{
     Formatter = "function(data) {return 100; }"
}
```
然而在实际的Blazor 界面中，这个元素却无法显示——也即，散点图只有背景没有散点
如果设置为
```
SymbolSize=  100
```
Blazor网页界面就可以正常显示SymbolSize，即有很多直径为100的散点
初步锚定是Formatter实现的问题。
我的疑问包括但不限于——
- Blazor中对EChart Formatter 的实现过程 ，比如是否直接用JS解析Formatter字符串
- Blazor元素与EChart API的对应规则，我的初步观察是将JS中的API的第一个字大写，如（appBag --> AppBag)，但网页样例并未完全说明，请问我解惑

# 另：
网页样例(https://blazor.masastack.com/blazor/components/echarts )每个样例右下角的运行按钮无法正确加载页面，请修复

### Expected Behavior

1. 完成对Formatter适配Bug的修复，或者阐述正确的Formatter写法
2. 对网页样例的运行按钮进行修复

### Steps To Reproduce

1. 部署一个新的Masa-- WebAssembly 项目
2. 在wwwroot/index.html，添加echart.min.js，这一步可以参照MasaBlazor网页样例
3. 在@code{ 之前的页面，添加

`<div class="d-flex align-center justify-center">`
    `<MECharts Option="_option" Width="@("100%")" Height="800"` `IncludeFunctionsInOption>`
    `</MECharts>`
`</div>`
 
 抱歉GitHub对Html格式的代码会报错，所以以这种格式传输
4. 在@code{之后定义option
 ```c#

private static object SeriesData = new[] {
    new [] {203,200,109,280},
    new [] {165,170,150,220},
    new [] {150,130,120,180},
    new [] {98,110,95,130},
    new [] {21,30,45,60},
    new [] {10,15,20,30},
    new [] {123,125,110,150},
    new [] {98,100,95,110},
    new [] {21,25,27,30},
    new [] {10,12,13,15},
    new [] {123,125,110,150},
    new [] {98,100,95,110},
    new [] {21,25,27,30},
    new [] {10,12,13,15},
    new [] {123,125,110,150},
    new [] {98,100,95,110},
    new [] {21,25,27,30},
    new [] {10,12,13,15},
    new [] {123,125,110,150},
};
//理想情况下，想以第三列作为散点图的SymbolSize

private object[] _option = new
        {
            Title = new
            {
                Left = "center",
                Text = "Getting started"
            },
            Tooltip = new { },
            XAxis = new
            {
                Scale = "true",
            },
            YAxis = new
            {
                Scale = "true",

            },
            DataZoom = new[]
            {
                    new
                    {
                        Type = "inside",
                        Start = "50",
                        End = "100",
                    },

    },
            Series = new[]
         {
            new
            {
                Name = "sales",
                Type= "scatter",
                Data= SeriesData ,
                /*
                SymbolSize = "20",
                 */
                SymbolSize=
                new
                {
                     Formatter = "function(data) {return 100; }"
                }
            }
        }
        };
```
在此基础上运行项目并通过对SymbolSize两种组合的注释和热重载重现该Bug。

### .NET version

8.0.100-preview.5.23303.2

### What browsers are you seeing the problem on?

Chrome

**Comment by capdiem** [comment]
@Gainlos https://echarts.apache.org/zh/option.html#series-scatter.symbolSize symbolSize不包含formatter属性，直接 `SymbolSize = "function(data) { return 100; }"` 就行了。

**Comment by capdiem** [comment]
@Gainlos 运行示例报错的问题我会修复一下。

**Comment by Gainlos** [comment]
@capdiem 万分感谢！！！ orz 萌新哭泣。 ,,Ծ‸Ծ,,

**Comment by capdiem** [comment]
当我修复 Masa Try 的问题后会关掉此issue。
