### ISSUE TITLE
[Bug Report]: MGridstack  get wrong element' size in wpf 

### ISSUE THREAD

**Issue by jishufangui** [masastack/MASA.Blazor#1402]
### Masa.Blazor version

1.0.0-rc.5

### Describe the bug

MGridstack  get wrong element' size in wpf 

### .NET version

7.0.202

### Additional context

wpf

**Comment by capdiem** [comment]
@jishufangui Sorry, a CSS reference is missing from the document.
``` html
<link href="https://cdn.masastack.com/npm/gridstack.js/7.2.1/gridstack.min.css" rel="stylesheet">
```

**Comment by jishufangui** [comment]
Thank you for you quick reply
