### ISSUE TITLE
[Bug Report]: 不同tab页内容会有概率堆积到同一个tab页

### ISSUE THREAD

**Issue by limei7** [masastack/MASA.Blazor#1416]
### Masa.Blazor version

1.0-Preview1

### Describe the bug

![image](https://github.com/masastack/MASA.Blazor/assets/93168234/47861c97-653f-4e1d-8517-9fa26f5d1519)

**Comment by capdiem** [comment]
@limei7 1.2.1可能已经修复了此问题，先关闭了，有问题再打开。
