### ISSUE TITLE
[Bug Report] Tabs: tab slider error in MToolbar on mobile

### ISSUE THREAD

**Issue by capdiem** [masastack/MASA.Blazor#1431]
### Masa.Blazor version

1.0.0

### Describe the bug

![image](https://github.com/masastack/MASA.Blazor/assets/16507773/4db737ad-49d7-41e2-a9cd-1456fb4e09c5)

**Comment by wisamidris7** [comment]
Yes I Faced That Bug

Also In Drawer The Left Padding In Main Not Taken

**Comment by capdiem** [comment]
Maybe fxied by #2202
