### ISSUE TITLE
[Bug Report]: MMenu Right Bottom无法执行打开抽屉

### ISSUE THREAD

**Issue by 394988736** [masastack/MASA.Blazor#1432]
### Masa.Blazor version

1.0

### Describe the bug

表格中rowbuttons <MMenu Right Bottom>执行打开抽屉拉出层失败
![image](https://github.com/masastack/MASA.Blazor/assets/81234257/987d0e4a-2e0e-428c-92b3-3ca7f24ea905)

**Comment by capdiem** [comment]
@394988736 menu跟抽屉没有直接的关系，请先升级到正式版试试。
