### ISSUE TITLE
给文本框添加自动补全选项

### ISSUE THREAD

**Issue by zms9110750** [masastack/MASA.Blazor#1435]
想要一种浏览器搜索框的功能。
在输入的时候同时会在后台进行搜索，并列出可能的选项。
和自动补全组件不同的是，不强制必须是候选项之一。
并且浏览器搜索框用方向键切换候选项时，会直接出现在文本框里。

最好是自动补全作为附加功能，分别内置于文本框和下拉框中，而不是单独做出一个组件。

**Comment by capdiem** [comment]
@zms9110750  不就是 Autocomplete 吗？

**Comment by zms9110750** [comment]
> @zms9110750 不就是 Autocomplete 吗？

那玩意是下拉框的变体，要求值必须是某一个候选项，不然不给保存

**Comment by capdiem** [comment]
@zms9110750 https://v2.vuetifyjs.com/zh-Hans/components/combobox/ 这种？

**Comment by zms9110750** [comment]
> @zms9110750 https://v2.vuetifyjs.com/zh-Hans/components/combobox/ 这种？

倒是可以。不过我想说的是这种东西
![Snipaste_2023-07-21_13-01-12](https://github.com/masastack/MASA.Blazor/assets/101843125/865efd1e-bab6-4932-a299-36c5b580ddd7)

**Comment by capdiem** [comment]
@zms9110750  搜索不就是autocomplete吗？
