### ISSUE TITLE
DateTime Picker

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1443]
When I Want DateTime Picker Like TextBox I Can't

I Used The Long Way From Your Docs And It's Hard
And I Can't Use It There

```razor
<MDateTimeField @bind-Value="date" Label="Date"/>
<MTextField @bind-Value="sometext" Label="Text"/>
```

**Comment by wisamidris7** [comment]
Also Do not forgot the format for dateTime

also if you can make it also for mtextfield
```razor
<MTextField @bind-Value="number" Format="c"/>
<MTextField @bind-Value="number" Format="#:##"/>
```

And In Any date masa 1.1.0 or 1.0.1 will realse

**Comment by capdiem** [comment]
@wisamidris7 https://docs.masastack.com/blazor/components/date-pickers#dialogandmenu

This is an example of using a date selector with an input box, but without the time. At 1.1.0 we can add a new preset component with time.

**Comment by wisamidris7** [comment]
In Any Date MASA.Blazor Will Make Anathor Version

Cause On Change Is Not Working And I Want To Publish My App Tomarrow And It's Filled With Errors

**Comment by capdiem** [comment]
> In Any Date MASA.Blazor Will Make Anathor Version

@wisamidris7 [1.0.1](https://github.com/masastack/MASA.Blazor/releases/tag/1.0.1) has released.

**Comment by capdiem** [comment]
Complete with #1472
