### ISSUE TITLE
[Bug Report]: Vaildation Error When Defaults

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1450]
### Masa.Blazor version

1.0.0

### Describe the bug

see video bottom

https://github.com/masastack/MASA.Blazor/assets/104096256/3ab77c38-4ddb-4ff6-8d51-03ac12fe8f5d

also make new version cause it's very very important because this bug

### .NET version

7.0.0

**Comment by wisamidris7** [comment]
Also Step In Number TextField Should Be StringNumber To Enter "any"

```
options => options.Step = "any"
```

**Comment by capdiem** [comment]
@wisamidris7 "any"? Why? It must be an exact number.
