### ISSUE TITLE
Virtualization For List And DataTable

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1459]
Virtualization Is Important Cause When Having Thounds Or Millons Of Records There Should Be Virtualization

```razor
<MList EnableVirtualization>
...
</MList>
<MDataTable> @* It's Not Important To Include It With Server Side Pagination *@
...
</MDataTable>
```

**Comment by wisamidris7** [comment]
Also If You Can Do That Is Optional

1. Resizing --> Resize Columns
2. Virtualization --> For Millons Of Records
3. Reordering --> For Dragging Columns And Reordering It
4. ColumnPicking --> Picking Columns Like Hide Or Show Columns

**Comment by capdiem** [comment]
@wisamidris7 
- Blazor official Virtualize component: https://learn.microsoft.com/en-us/aspnet/core/blazor/components/virtualization?view=aspnetcore-7.0
- MASA Blazor Virtualize component: https://docs.masastack.com/blazor/components/virtual-scroll

The DataTable does not currently support virtualization.

**Comment by capdiem** [comment]
duplicate #1075

**Comment by wisamidris7** [comment]
> Blazor official Virtualize component

How To Use

```razor
<MDataTable>
<LoopContent>
@foreach (var item in context.Rows)
{
@context.Content(item)
}
</LoopContent>
</MDataTable>
<MDataTable>
<LoopContent>
<Viruzie>
@context.Content(item)
</Virruaize>
</LoopContent>
</MDataTable>

**Comment by capdiem** [comment]
@wisamidris7 The DataTable does not currently support virtualization.
