### ISSUE TITLE
[Bug Report]: Expansion Panel Is Slow

### ISSUE THREAD

**Issue by IdrisQashan** [masastack/MASA.Blazor#1460]
### Masa.Blazor version

1.0.1

### Describe the bug

When Opening Exapinsion Or Close Are Having Big Lag Can You Imporve Speed Or Making Something Named NoAnimations
Cause I Think Animations What Make Exapinsion Slower.

I Click At It And Wait 1.4s and after it load animation also animation have lagging for app.

**Comment by capdiem** [comment]
@IdrisQashan Are you using Blazor Server App? Possible points for this problem: 
- high network latency. 
- there is a lot of content in ExpansionPanel to render, such as foreach the ListItem components.

**Comment by wisamidris7** [comment]
In Debug In Offline Mode

**Comment by wisamidris7** [comment]
I Can Fix Slow Expansion And Make Package Better But Something Not Make Me Work That Things In MASA.Blazor nuget.org
Not Exisit In MASA.Blazor Github Cause When I Fork And Start Working But I Haved Many Many Problems Or Compile Errors

So I Want To Fork And Make Pull Request And Everything Done
