### ISSUE TITLE
[Bug Report]: MASA.Blazor nuget.org vsMASA.Blazor Github

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1463]
### Masa.Blazor version

aboutanything

### Describe the bug

when i want to fork and make pull request for masa.blazor i can't cause the library in nuget.org
is deffrent of the github one

i want to fix things in masa or add to make pull request for you
but i can't so can you fix this

when i open visual studio i have 48 compile errors also there things other

**Comment by capdiem** [comment]
@wisamidris7 I guess the source code downloaded by nuget contains only MASA.Blazor, not BlazorComponent and MASA.Docs repositories. You can download the source code using the [following command](https://github.com/masastack/MASA.Blazor#-local-development):
```shell
git clone --recursive https://github.com/masastack/Masa.Blazor.git
cd Masa.Blazor
git submodule foreach git checkout main
```
