### ISSUE TITLE
Improve Autocomplete Component to process many items

### ISSUE THREAD

**Issue by OmidAtaei1984** [masastack/MASA.Blazor#1467]
In the example of "Api Search" related to the AutoComplete component, it is stated in the description that "We can't process too many items now". My suggestion is that when typing in the component, if the length of the input string is more than 3 characters, the search for the items will be done. In this case, more than 1000 items can be processed in this component.

I would also be grateful if you checked the codes in this address and if they are useful, they will be used in this component.
https://www.codeproject.com/Articles/5351256/Building-a-Blazor-Autocomplete-Control
https://github.com/ShaunCurtis/Blazr.Demo.TypeAhead

**Comment by capdiem** [comment]
Starting from v1.6.0, Autocomplete now uses virtualization to handle items.
