### ISSUE TITLE
[Bug Report]: PCron 控件 在 PopupService.OpenAsync 中 打开时，无法通过参数赋初始始值

### ISSUE THREAD

**Issue by eudeman** [masastack/MASA.Blazor#1470]
### Masa.Blazor version

1.0

### Describe the bug

把PCron控件放在 PopupComponentBase 里，使用 PopupService.OpenAsync 开启设置对话框。通过 参数传初始值给 CronValue，Popup 在给PCron控件初始值后，会执行PCron控件的 AfterRender，ConValue 会被更新回"*****?"。

### .NET version

.net6.0

**Comment by capdiem** [comment]
@eudeman  我尝试复现你的问题，但没有成功。你传入的CronValue被什么改了？OnAfterRender里也只是改了 _cronValue，没有改 CronValue。
