### ISSUE TITLE
PopupService prompt cannot set a default value 弹窗确认服务无法给输入框一个默认值

### ISSUE THREAD

**Issue by TAnsz** [masastack/MASA.Blazor#1471]
**Is your feature request related to a problem? Please describe.**
yes

**Describe the solution you'd like**
PopupService.Prompt 增加一个默认值，这样一些简单的弹窗编辑功能就可以直接用这个代替，类似于这样。

![image](https://github.com/masastack/MASA.Blazor/assets/15372314/c3e999b1-b905-49bd-9f4d-d8ecebdb9ae8)

**Comment by capdiem** [comment]
@TAnsz Prompt是输入确认或者叫二次确认用的，你的需求不符合这个组件的要求，你可以COPY Prompt的源码，直接OpenAsync自己的编辑框组件。
