### ISSUE TITLE
hMdatatable 支持时间等格式的属性统一格式化

### ISSUE THREAD

**Issue by Lee-Lily-Lea** [masastack/MASA.Blazor#1495]
如题 

为MDatatable提供一个属性 Func<object,string>
object就是对应列对应行的值 string就是显示的值
根据这个属性就可以实现 如datetime等类型的属性的格式化
再根据masa现有的默认值代理来设置所有的Mdatatable都能够自动"转义"特殊类型

**Comment by capdiem** [comment]
@Lee-Lily-Lea 不提PR吗 😭

**Comment by Lee-Lily-Lea** [comment]
> @Lee-Lily-Lea 不提PR吗 😭

我礼拜一搞搞看

**Comment by capdiem** [comment]
@Lee-Lily-Lea 假设新加一个 `Func<object,string>` 属性，会与当前的 `ItemColContent` 插槽和 v1.5.0 开始支持的 `CellRender` 功能重叠，所以不打算支持。
