### ISSUE TITLE
Animation Disible

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1504]
Can Your Package Contains Disible Animation Cause When I Tryed You Should Make

TranslationElementBase.cs
```c#
159: _transitionJsInvoker = new TransitionJsInvoker(Js);
```

This Should Be Depency Injection Cause I Will Replace Him With My Own Code Like Disaibling Or Custom Animations

```c#
builer.Services.Replace<ITransitionJsInvoker, CustomTransitionJsInvoker>();
```

**Comment by capdiem** [comment]
@wisamidris7 I don't think a custom transitionJsInvoker will work as you expect. The only way to ban the transition is `Transition=""`. I will refactor the implement of transition in future.

**Comment by wisamidris7** [comment]
>  I don't think a custom transitionJsInvoker will work as you expect. The only way to ban the

Cause Some Or Most Of The Components Are Not Having Transition=""
So I Want To Make Custom translation.js

And I Planed And Tryed With MASA.Blazor.Demo And It Work
I Disibled Ripple Animation From blazor-components.js
By Making Ripple Animation A Empty Thing And I Maked It With translation.js

I Maked Custom blazor-components.js but I can't Do translation.js

Or Make A Global DisibleTranslation Property For All

**Comment by wisamidris7** [comment]
from masa.blazor 1.0.1 is being animtions is fast
