### ISSUE TITLE
[Question]: Dark Mode Not Working

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1518]
### Masa.Blazor version

1.0.3

### Describe the bug

The Primary Color Should Be Same Cause When Switch To Dark It Going White The App Not Looking Cool

**Comment by wisamidris7** [comment]
There No Choice Named Ask Question There Should Be In Github Issue Named Ask Quesion To See If This Really Bug
This Not Bug But I Chosed Bug

**Comment by capdiem** [comment]
@wisamidris7 You mean the dark themes of the document site? The color scheme is really not good. I'll Take a chance to redesign it. If the primary color with a bright theme is too dark to read on a black background. Another day I'll get a chance to add a question issue template.

**Comment by wisamidris7** [comment]
thanks
