### ISSUE TITLE
[Bug Report]: MExpansionPanels无法通过设置MExpansionPanel的IsActive属性来控制模板默认展开

### ISSUE THREAD

**Issue by VleaStwo** [masastack/MASA.Blazor#1534]
### Masa.Blazor version

1.0.3

### Describe the bug

1. 如题 如果要实现默认展开需要 MExpansionPanels设置 @bind-Value/Values 并且创建 配套的字段或属性 比较繁琐
2. 文档apis的MExpansionPanel的IsActive的描述写成了 **受否激活。** 应当为 **是否激活**
3. 缺少Color/ActiveColor属性 需要通过style或class设置

### .NET version

net 7.0

**Comment by capdiem** [comment]
@VleaStwo ExpansionPanel需要配合ExpansionPanels一起使用，而且单选多选和每个Panel的IsActive有冲突，所以不打算支持IsActive属性。
