### ISSUE TITLE
[Bug Report]: PPageContainer回到之前缓存的页面，页面状态被重置

### ISSUE THREAD

**Issue by Yu-Core** [masastack/MASA.Blazor#1535]
### Masa.Blazor version

1.0.3

### Describe the bug

PPageContainer回到之前缓存的页面，页面状态被重置（页面数据是正常的）

在1.0.1时是正常的。

在开发者工具里看到dom发生了改变，不是原来的dom了

1.0.3

https://github.com/masastack/MASA.Blazor/assets/96511239/0f19ab15-026e-4881-80af-f1fba4dc8125

1.0.1

https://github.com/masastack/MASA.Blazor/assets/96511239/a8e33843-a19a-4b25-9e3a-353b20127d42

MainLayout.razor

![image](https://github.com/masastack/MASA.Blazor/assets/96511239/97f27eee-7043-41a8-bd67-7cac4e7944a7)

PageTabs2.razor

![image](https://github.com/masastack/MASA.Blazor/assets/96511239/ffc0800e-60e5-495f-88a9-b56600ea07d7)

### Steps To Reproduce

https://github.com/Yu-Core/MasaBlazorPPageContainerBug

### .NET version

.NET 7

**Comment by capdiem** [comment]
新版加了一个淘汰策略的功能，导致页面列表的顺序每次都会变化，即使加了@key，dom在blazor的世界里没变，但在html里是变了。应该能修复。
