### ISSUE TITLE
请问下 进度条 动态渲染进度怎么弄

### ISSUE THREAD

**Issue by liujian1368928** [masastack/MASA.Blazor#1540]
进度条总是结束渲染 ，请问下是有什么操作没做到位，进度 组件能帮我计算一下吗
![image](https://github.com/masastack/MASA.Blazor/assets/23169722/afa8e3ed-63b0-400d-a6b5-9d4a2ac7e142)
![image](https://github.com/masastack/MASA.Blazor/assets/23169722/5d3b7760-cac3-493f-ae87-593d99fc2b81)

**Comment by capdiem** [comment]
@liujian1368928 不太明白你想做什么效果

**Comment by liujian1368928** [comment]
已经解决了

**Comment by liujian1368928** [comment]
> 

解决了已经

**Comment by liujian1368928** [comment]
> @liujian1368928 不太明白你想做什么效果

解决了已经
