### ISSUE TITLE
Ask Question -> How To Fetch And Pull

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1544]
You Add Package Named BimIt
This Is The Result What Command I Use For Fetch And Pull

![Screenshot 2023-09-11 010256](https://github.com/masastack/MASA.Blazor/assets/104096256/87c71a98-9b9d-44b5-be66-34cb1a27b149)
![Screenshot 2023-09-11 010311](https://github.com/masastack/MASA.Blazor/assets/104096256/0f4add09-e540-42f4-80a1-af25d256831c)
![Screenshot 2023-09-11 010321](https://github.com/masastack/MASA.Blazor/assets/104096256/42e6833d-91ef-44d1-8ccb-f9e27c5f37b9)

**Comment by capdiem** [comment]
@wisamidris7 Your BlazorComponent repository is old. Try:
```shell
cd MASA.Blazor\src\BlazorComponent
git pull
```
