### ISSUE TITLE
[Bug Report]: masa winform  部署服务器 报错

### ISSUE THREAD

**Issue by liujian1368928** [masastack/MASA.Blazor#1545]
### Masa.Blazor version

1.0.1

### Describe the bug

直接创建  blazor winform程序发布，未做修改，部署到 winserver 2012  服务器 启动报错
![image](https://github.com/masastack/MASA.Blazor/assets/23169722/a0517cc1-9f88-4b2c-9ed6-c020a33419e0)

![image](https://github.com/masastack/MASA.Blazor/assets/23169722/3e1961ee-dc7f-498f-a912-57d47942dcd7)
已安装运行时
![image](https://github.com/masastack/MASA.Blazor/assets/23169722/1946d50c-698c-4bd3-bf6e-43a9ccab26c2)

### Expected Behavior

能启动

### .NET version

7

**Comment by capdiem** [comment]
@liujian1368928 部署的问题应该与组件库没有什么关系。blazor hybrid 有最低支持的系统要求，它依赖 WebView2， https://learn.microsoft.com/zh-cn/deployedge/microsoft-edge-supported-operating-systems 。如果发布到本地，例如windows10可用的话，这个问题需要你自己去排查了。

**Comment by SmallPotY** [comment]
@liujian1368928  大佬你找到原因了吗? 我被这个折磨半天了... 本地没问题,  发到其他电脑就报这个错误
