### ISSUE TITLE
[Bug Report]: MBottomSheet启用OpenOnHover时抽风

### ISSUE THREAD

**Issue by Lee-Lily-Lea** [masastack/MASA.Blazor#1550]
### Masa.Blazor version

1.0.3

### Describe the bug

https://github.com/masastack/MASA.Blazor/assets/78075553/6d266998-2b09-4688-982a-8da5a5cdb712

如视频里 启用OpenOnHover的时候 估计是遮盖层干扰Hover 容易抽风

然后OpenOnFocus 也有类似的问题
OpenOnXXX更像是 HoldOpenWhereXXX
建议修改逻辑 Open变成持久的而不是 where hold

或者直接删除了

### .NET version

net 7.0

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by capdiem** [comment]
@Lee-Lily-Lea 没有使用场景 :)
