### ISSUE TITLE
[Bug Report]: The 'Contained' property of the MOverlay widget is missing

### ISSUE THREAD

**Issue by shihuixian** [masastack/MASA.Blazor#1557]
### Masa.Blazor version

1.0.4

### Describe the bug

in the api document, 'contained' property still exists.but can not use in 1.0.4 version,Version 1.0.3 functions properly.

**Comment by capdiem** [comment]
@shihuixian `Contained` property is not deleted.

**Comment by shihuixian** [comment]
> @shihuixian `Contained` property is not deleted.
thanks.It might be an issue with VS2022's IntelliSense. In version 1.0.4, the 'Contained' property couldn't be used, but it worked when downgrading to version 1.0.3. Interestingly, after upgrading to version 1.0.4 again, it started working, so it shouldn't be a bug.
