### ISSUE TITLE
[Bug Report]: Slider Value is Opposite of Mouse Movement

### ISSUE THREAD

**Issue by OmidAtaei1984** [masastack/MASA.Blazor#1574]
### Masa.Blazor version

1.0.4

### Describe the bug

Hello. When the RTL option is active, the direction of the mouse movement in the Slider control is opposite to its normal state, that is, when the mouse moves to the right, the Slider moves to the left and increases the value, and when it moves to the left, the Slider moves to the right and decreases the value. moves

### Expected Behavior

Slider control when RTL is active should decrease the value by moving the mouse to the right and increase the value by moving the mouse to the left

### Steps To Reproduce

In adding the service, set the rtl value to True and place a Slider control on the page. Change the value of the slider by moving the mouse

### .NET version

7.0.401

**Comment by capdiem** [comment]
@OmidAtaei1984 Thanks for contacting us, it will be fixed in next version
