### ISSUE TITLE
[Feature Request]: Treeview🔍搜索缺少无结果插槽

### ISSUE THREAD

**Issue by Lee-Lily-Lea** [masastack/MASA.Blazor#1599]
### Masa.Blazor version

1.0.4

### Describe the bug

![image](https://github.com/masastack/MASA.Blazor/assets/78075553/378d6c3e-97a2-4f94-96c4-6948d084d30e)

Treeview🔍搜索无满足条件情况下 没有显示类似于"没有满足条件的内容"  缺少"NoResultsText"插槽

另外,希望增加一个bool属性 用来控制搜索结果是否展开

**Comment by capdiem** [comment]
@Lee-Lily-Lea
-  `ChildContent` 可以用来作为无结果显式的内容。
-  搜索结果可以做到展开，但如果还要清除Search后，还原原来的展开状态就比较麻烦了。
