### ISSUE TITLE
TreeView Third Type

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1604]
I Have Tree View
But The Selection Is Permissions Tree Here Is Example

https://github.com/masastack/MASA.Blazor/assets/104096256/890621cf-7948-4a0f-8fb2-d40a50cf9abc

When Select Parent Children Are Being All Selected
But When Uncheck All Children Parent Does Not Being Beا Unselected The Parent

**Comment by capdiem** [comment]
@wisamidris7 Because you used the `SelectionType.Independent`, right?

**Comment by IdrisQashan** [comment]
No He Mean He Want Third Type For Permissions And This Is Looks Like Abp
