### ISSUE TITLE
How Or Can Masa.Blazor Use Spiltter In Drawer

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1614]
Can Masa.Blazor Or You Give Me Code I Can Use Spitter In Drawer To Resize And Main div Will Take Padding Automatacly
And Thanks 🙂

**Comment by capdiem** [comment]
@wisamidris7 Splitter has no plans to use with navigation drawer. If you don't care about mobile, maybe: 
``` razor
<MApp>
  <MSplitter>
     <MSpliiterPane>
       <MNavigationDrawer Width="@("100%")" Permanent>
    </MSpliiterPane>
    <MSpliiterPane>
        <MMain>
    </MSpliiterPane>
  </MSplitter>
</MApp>
```
