### ISSUE TITLE
MCascader 值绑定问题 @bind-Value="_value"

### ISSUE THREAD

**Issue by anan1213095357** [masastack/MASA.Blazor#1623]
### Masa.Blazor version

最新的

### Describe the bug

@bind-Value="_value"  我是只能使用 这种方式吗？  我可以分开写吗  Value=“”  ValueChanged=“”

**Comment by capdiem** [comment]
@anan1213095357 你可以拆开，只是需要把泛型写全：
```razor
<MCascader Value="_value"
           ValueChanged="ValueChanged"
           TValue="string"
           TItem="CascaderNode"
           TItemValue="string"
           ...>
</MCascader>
```

**Comment by anan1213095357** [comment]
不是的，值为什么类型我才可以一级和二级都正常显示呢？我设置value 福建/厦门 这样只会显示一个福建，

**Comment by capdiem** [comment]
@anan1213095357 value的值只要是厦门的key就行了

**Comment by anan1213095357** [comment]
那我如果有一个福建A一个福建B，怎么办？

**Comment by capdiem** [comment]
@anan1213095357 你只要保证key唯一就行。

**Comment by anan1213095357** [comment]
现在的问题就是key并不是唯一的，我有两个福建两个厦门。
