### ISSUE TITLE
Can You Make This Method Virual

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1637]
![image](https://github.com/masastack/MASA.Blazor/assets/104096256/3d57fd17-0dea-45c5-84b1-b1bb9e28c1d4)

Cause Here
https://github.com/masastack/MASA.Blazor/issues/1604

Then I Said I Will Make It But I Need This Method To Override This Method To Make This

![image](https://github.com/masastack/MASA.Blazor/assets/104096256/c623cad1-8c51-49c9-a7fb-9f4cbe5d05e9)

And Thanks And Tell Me In Any Day You Will Publish New Version

**Comment by wisamidris7** [comment]
I Tried To Copy Tree Folder And To Copy BTreeView Component But It Disappear When Coping It Or Sometimes Throws InvalidOpertion

**Comment by capdiem** [comment]
@wisamidris7 v1.3.0-beta.2 was published, this issue should be closed?
