### ISSUE TITLE
能不能给分页组件增加一个SEO的功能？

### ISSUE THREAD

**Issue by bloodxia** [masastack/MASA.Blazor#1640]
目前分页组件SEO不友好，能不能加一个href的显示的功能？让页面被搜索引擎抓取后可以在source中看到分页的链接，自己指定url的格式后，让分页可以带一个url。blazor中当前页href是不跳转的，还是要用事件去处理，但是对于SEO是友好的。

**Comment by capdiem** [comment]
@bloodxia 具体实现有什么建议吗？分页的每个button用Href去做吗？

**Comment by bloodxia** [comment]
> @bloodxia 具体实现有什么建议吗？分页的每个button用Href去做吗？

只是带个href就可以了，让source中的page有href，可以让搜索引擎索引，鼠标移上去有网址就可以了。像button增加href属性，也是一样的效果，操作用onclick事件实现，href只是给一个链接让人能看到，让爬虫能看到链接就行。

**Comment by bloodxia** [comment]
> @bloodxia 具体实现有什么建议吗？分页的每个button用Href去做吗？

现有的东西其实都不需要改动，只要给button增加个href，增加2个新的一个，一个enabledUrl，一个给个urlbase就可以了，Url规则用baseurl{0}去填充就可以了，实际的事件依然还是onvaluechanged事件去处理的。

**Comment by capdiem** [comment]
@bloodxia 这样的API可以吗？
``` razor
    <MPagination @bind-Value="_page" Length="6" HrefFormat="/list?page={0}"></MPagination>
    <MPagination @bind-Value="_page" Length="6" HrefFormat="https://www.bing.com/list?page={0}"></MPagination>
```

**Comment by bloodxia** [comment]
> @bloodxia 这样的API可以吗？
> 
> ```
>     <MPagination @bind-Value="_page" Length="6" HrefFormat="/list?page={0}"></MPagination>
>     <MPagination @bind-Value="_page" Length="6" HrefFormat="https://www.bing.com/list?page={0}"></MPagination>
> ```

完全可以。没有任何问题。只要能支持SEO，让搜索引擎能见到这个link就可以了
