### ISSUE TITLE
提个建议，能不能抄一个时间组件？

### ISSUE THREAD

**Issue by bloodxia** [masastack/MASA.Blazor#1650]
https://demos.devexpress.com/blazor/DateEdit
这是devexpress的时间组件，PC和移动端都很完美，该有的功能都有，适配完美，操作也没有任何bug，比现在的PDateDigitalClockPicker好太多了。PDateDigitalClockPicker在移动端bug太多了，非常难用。能把他们的这个给抄过来吗？

**Comment by capdiem** [comment]
@bloodxia 不打算再做个时间组件，有BUG提BUG。
