### ISSUE TITLE
[Bug Report]: MFileInput，Value无法绑定 IBrowserFile 对象

### ISSUE THREAD

**Issue by shshshdy** [masastack/MASA.Blazor#1660]
### Masa.Blazor version

1.0.2

### Describe the bug

![image](https://github.com/masastack/MASA.Blazor/assets/6049451/718bbf96-0eb1-4996-99c5-42c070324cc2)

选择文件报错如下：
`The type 'System.Collections.Generic.List ``1[[Microsoft.AspNetCore.Components.Forms.IBrowserFile, Microsoft.AspNetCore.Components.Web, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60]]' does not have an associated TypeConverter that supports conversion from a string. Apply 'TypeConverterAttribute' to the type to register a converter.`

### .NET version

.net 8.0

**Comment by capdiem** [comment]
@shshshdy 用 `@bind-Value="_file"`。至于控制台的TypeConverterAttribute错误升级到最新版即可解决。

**Comment by shshshdy** [comment]
解决了，谢谢
