### ISSUE TITLE
[Bug Report]: MFileInput component: can not read file data

### ISSUE THREAD

**Issue by shihuixian** [masastack/MASA.Blazor#1662]
### Masa.Blazor version

1.2.2

### Describe the bug

After selecting the file, calling OpenReadStream() obtains the file stream, at this point, the position of the file stream is at the end of the file. At the same time, this file stream only supports read operations and cannot reset the position to the beginning of the file, resulting in being unable to read the content of the file.
code as below:
```
private async Task OnUploadFile(IBrowserFile file)
{
    var fs = file.OpenReadStream();
    //fs.Seek(0, SeekOrigin.Begin); this will cause not support method exception
    var buffer = new Byte[1024 * 4];
    var readSize = await fs.ReadAsync(buffer, 0, buffer.Length);//readSize is 0
...
}
```

### Steps To Reproduce

1. select a file
2. call OpenReadStream to get file stream
3. use ReadAsync to read file content from the beginning,only 0 bytes will be readed

### .NET version

7.0

### What browsers are you seeing the problem on?

Chrome

**Comment by capdiem** [comment]
@shihuixian https://learn.microsoft.com/zh-cn/aspnet/core/blazor/file-uploads?view=aspnetcore-8.0

**Comment by shihuixian** [comment]
> @shihuixian https://learn.microsoft.com/zh-cn/aspnet/core/blazor/file-uploads?view=aspnetcore-8.0

thanks
