### ISSUE TITLE
Overflow Scroll For Tabs

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1668]
Why The Tabs Not Contains Overflow Scroll 

Reason:
Cause Arrows Are Slow Sometimes And Some Times Bugs Appears But I Don't Know From Where And Why The Bugs Come 

Solution:
So Can Tabs And PageTabs Contains A Overflow Scroll To Be Scroll 

Cause:
In Mobile Users Won't Click The Buttons They Will Scroll With Mobile From Left To Right So It Will Be Awesome To Make Overflow For Tabs Scrolling

And Thanks!

**Comment by capdiem** [comment]
@wisamidris7 Tabs does lack the ability to touch and scroll on the mobile.

**Comment by capdiem** [comment]
@wisamidris7 If you want to display the scroll bar:
```css
.m-slide-group__wrapper {
  overflow-x: auto;
}
```

**Comment by wisamidris7** [comment]
Thanks
