### ISSUE TITLE
PPageTabs 希望能加入一个onclick的事件

### ISSUE THREAD

**Issue by shusongLu** [masastack/MASA.Blazor#1676]
在鼠标中键点击标签时会弹出跳转到新页面,正常逻辑应为关闭此标签页.

但在masa中PPageTabs添加此事件无法触发.

现在暂时无任何解决方案

**Comment by capdiem** [comment]
@shusongLu 多谢反馈，中键关闭是个不错的特性，后续会加上。

**Comment by shusongLu** [comment]
@capdiem 或许有些组件上都加上中键点击处理好像会好点 例如MNavigationDrawer,如果我用鼠标中键点击会直接去跳转到新标签页加载这个页面,但是我是用Blazor WPF Hybrid,鼠标中键点击到跳转到网页有些太割裂了

**Comment by capdiem** [comment]
NavigationDrawer的导航上应该没有人会点击中键，没有必要处理
