### ISSUE TITLE
[Bug Report]: MSwitch 在MAUI Blazor 中不会失去焦点

### ISSUE THREAD

**Issue by 18639522576** [masastack/MASA.Blazor#1677]
### Masa.Blazor version

1.2.2

### Describe the bug

![image](https://github.com/masastack/MASA.Blazor/assets/60860618/efd3690c-7b2e-4a72-8537-51cf0dd15d0c)
这个MSwitch 在Maui blazor 中 切换状态时存在问题，他的阴影不会消失（不会主动失去焦点）

**Comment by capdiem** [comment]
v1.7 之后的UI有优化，焦点的颜色不会这么深了。
