### ISSUE TITLE
现在支持最新的Blazor Web App模板了吗？

### ISSUE THREAD

**Issue by yangsenss** [masastack/MASA.Blazor#1678]
我使用最新的Blazor Web App模板，发现无法正确使用MASA.Blazor。
请问下MASA.Blazor支持最新的Blazor Web App模板吗？或者有计划支持Blazor Web App模板吗？

**Comment by capdiem** [comment]
@yangsenss 新的模板的还在路上，MASA Blazor组件库也在做一些改变来支持SSR，预计下周会发布。

**Comment by capdiem** [comment]
@yangsenss 模板已经更新。
