### ISSUE TITLE
我如何将我子组件的  MCard    显示在我 父组件上.   就是类似实现一种  点击某一项子组件  ,    把子组件里面的 <mcard>   渲染到父组件上

### ISSUE THREAD

**Issue by anan1213095357** [masastack/MASA.Blazor#1681]
### Masa.Blazor version

最新的

### Describe the bug

我如何将我子组件的  MCard    显示在我 父组件上.   就是类似实现一种  点击某一项子组件  ,    把子组件里面的 <mcard>   渲染到父组件上

**Comment by capdiem** [comment]
@anan1213095357 .NET 8 的SectionOutlet和SectionContent应该可以轻松做到。

**Comment by anan1213095357** [comment]
> @anan1213095357 .NET 8 的SectionOutlet和SectionContent应该可以轻松做到。

我在想有没有一种写法是类似jsx的，就是我用html语法把dom渲染写出来，但是渲染的时候先不会被加载，等到需要的时候再按需加载？

**Comment by anan1213095357** [comment]
> @anan1213095357 渲染的时候除非ifelse一般都会加载吧，你需要什么时候去加载？组件与视图相交时加载可以用IntersectJSModule。

因为我写的是一个低代码平台，我拖拽控件进来主界面的时候，需要弹出该组件的属性设置。问题就出在这里，因为我一个页面有几百个组件也就导致了他会把几百个组件的属性设置元素全部渲染出来我整个dom会非常的卡。

**Comment by anan1213095357** [comment]
> @anan1213095357 渲染的时候除非ifelse一般都会加载吧，你需要什么时候去加载？组件与视图相交时加载可以用IntersectJSModule。

对了另外再问你一个问题，关于blazor server的，这个问题困扰我挺久了，我目前这个低代码的做法是通过数据库保存每个组件的位置信息属性设置等数据。然后页面加载的时候会for出来界面上，问题就出现了，当我dom在for元素过多的时候，如果我这时候比如改变这个for的数据，比如删除掉某一部分的组件。界面重新渲染就会乱七八糟。组件的位置也是乱七八糟，这时候我页面刷新后才会正常。

**Comment by capdiem** [comment]
> 因为我写的是一个低代码平台，我拖拽控件进来主界面的时候，需要弹出该组件的属性设置。问题就出在这里，因为我一个页面有几百个组件也就导致了他会把几百个组件的属性设置元素全部渲染出来我整个dom会非常的卡。

你说的几百个组件是已经拖出来的组件吗？那一次性加载是会卡的，可以用InteresctJSModule懒加载。如果只是控件列表的几百个组件，你放个控件名就行了吧，那应该不卡吧。

> 对了另外再问你一个问题，关于blazor server的，这个问题困扰我挺久了，我目前这个低代码的做法是通过数据库保存每个组件的位置信息属性设置等数据。然后页面加载的时候会for出来界面上，问题就出现了，当我dom在for元素过多的时候，如果我这时候比如改变这个for的数据，比如删除掉某一部分的组件。界面重新渲染就会乱七八糟。组件的位置也是乱七八糟，这时候我页面刷新后才会正常。

位置信息记录的话，你应该用的是绝对定位吧，那删除了某个组件应该不会影响其他元素吧。如果你记录的位置信息只是顺序的意思，用flex布局或查一下瀑布式布局。

**Comment by anan1213095357** [comment]
> @anan1213095357
> 
> > 因为我写的是一个低代码平台，我拖拽控件进来主界面的时候，需要弹出该组件的属性设置。问题就出在这里，因为我一个页面有几百个组件也就导致了他会把几百个组件的属性设置元素全部渲染出来我整个dom会非常的卡。
> 
> 你说的几百个组件是已经拖出来的组件吗？那一次性加载是会卡的，可以用InteresctJSModule懒加载。如果只是控件列表的几百个组件，你放个控件名就行了吧，那应该不卡吧。
> 
> > 对了另外再问你一个问题，关于blazor server的，这个问题困扰我挺久了，我目前这个低代码的做法是通过数据库保存每个组件的位置信息属性设置等数据。然后页面加载的时候会for出来界面上，问题就出现了，当我dom在for元素过多的时候，如果我这时候比如改变这个for的数据，比如删除掉某一部分的组件。界面重新渲染就会乱七八糟。组件的位置也是乱七八糟，这时候我页面刷新后才会正常。
> 
> 位置信息记录的话，你应该用的是绝对定位吧，那删除了某个组件应该不会影响其他元素吧。如果你记录的位置信息只是顺序的意思，用flex布局或查一下瀑布式布局。

你说的懒加载我去看看，我是用的绝对定位，每个组件数据都有x,y字段，比如我这个for里面删除某一个字段后，我可能名字为title得标签组件就会跑下去别的组件的位置，有时候比如我整个list=new()清空，让他重新渲染，也会出现页面上还有元素没删干净，我用的是渲染委托，不是直接写的html语法

**Comment by capdiem** [comment]
@anan1213095357 绝对定位下不是很明白为什么会影响其他组件。你也许可以看看Gridstack组件适不适合你。渲染委托保证每个区块的sequence正确。

**Comment by anan1213095357** [comment]
> @anan1213095357 绝对定位下不是很明白为什么会影响其他组件。你也许可以看看Gridstack组件适不适合你。渲染委托保证每个区块的sequence正确。

是的，我也很奇怪。我觉得应该不会出现这个问题才对。但就是出现了。所以我束手无策

**Comment by anan1213095357** [comment]
yes
