### ISSUE TITLE
[Bug Report]: Autocomplete Many Renders

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1691]
### Masa.Blazor version

latest

### Describe the bug

Render Comes To 7 Renders In FirstRender
And When I Click Any Key 2 Renders This Is Not Normal At All

In DeepClone In InternalValue The Renders For Every Autocomplete It Comes 17 and sometimes 12 as minumum in Select When Having Many Autocompletes
I Maked I Report Page And Report Contains Up To 8 Autocompletes

**Comment by capdiem** [comment]
@wisamidris7 Where is the first-render called seven times?

**Comment by wisamidris7** [comment]
> Where is the firstrender called seven times?

I mean without toching the autocomplete just when he loads
And I'm Waiting For Masa.Blazor To Get Better And Move On
Cause The App I'm Using Is Uses A Lot Of Autocompletes So When You Use It It's Becomes Very Very Slow And After Aot It Become Also Slow But Not The Same As Non AOT

And Thanks!

**Comment by capdiem** [comment]
@wisamidris7  Can you provide a simple example? So I can find the problem easily.

**Comment by capdiem** [comment]
Starting from v1.6.0, Autocomplete now utilizes virtualization to handle items. This significantly improves rendering speed in scenarios with large amounts of data. Therefore, this issue can be closed.
