### ISSUE TITLE
[Bug Report]: Font Awesome Icons Not Set

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1701]
### Masa.Blazor version

i updated it just yesterday

### Describe the bug

Font Awsome Icons Not Working And What You See Is mdi Icons When I Aleardy Maked Font Awesome Icons
This Is Bug And In Old Version And Still Until Now The Pro Font Awesome Duotone New Icons That Only The Before Who Appears
And The After Not Shown Yet

And Thanks !

**Comment by wisamidris7** [comment]
It Was Because The Configure Method Was Above AddMasaBlazor I Think In New MasaBlazor It Create New Config

**Comment by capdiem** [comment]
@wisamidris7 I'm sorry about that. 
Currently, only v5 is the latest version of font awesome supported by masa blazor. 
v6 changed `fas fa-house` to `fa-solid fa-house`.

**Comment by capdiem** [comment]
@wisamidris7 So for now you need use v5 instead of v6 version font awesome.

**Comment by capdiem** [comment]
@wisamidris7 font awesome 6 has been supported in `v1.3.1`.
``` razor
<MIcon>fa6:fa-solid fa-house</MIcon>
```

More information see https://docs.masastack.com/blazor/features/icon-fonts#multiple-icon-sets

**Comment by wisamidris7** [comment]
ok forgot about the new icons of font awesome

in the latest masa before upgrade to new masa it was okay but after upgrade
all icons not visible and when i click inspect for example the appbarmenu icon is 'mdi-menu'
and i want to only use fontawesome

**Comment by wisamidris7** [comment]
ok thanks!
