### ISSUE TITLE
管理大大 你的微信群邀请二维码过期了 我该如何入群 可以拉我一下不

### ISSUE THREAD

**Issue by W2426566602** [masastack/MASA.Blazor#1702]
管理大大 你的微信群邀请二维码过期了 我该如何入群 可以拉我一下不

**Comment by capdiem** [comment]
@W2426566602 哪里的过期了？你可以加微信 MasaStackTechOps，叫他拉你进群。

**Comment by W2426566602** [comment]
@capdiem github里面的vx群邀请二维码过期了
