### ISSUE TITLE
Set custom font for application

### ISSUE THREAD

**Issue by OmidAtaei1984** [masastack/MASA.Blazor#1711]
Hello. good day. There is no guidance on the site regarding how to use web fonts, font-face and how to set the font for the application globally. It can be done for components such as mcontainer when adding the service, using the command:

options.Defaults = new Dictionary<string, IDictionary<string, object?>?>()
     {
         { nameof(Mcontainer), new Dictionary<string, object?>() { { nameof(Mcontainer.Style), "font-family: ''CustomeFontName"} } },
     }

The font can be set, but in components such as MCard, the above command must be added again for that component, or in "popupService.EnqueueSnackbarAsync", the displayed text font is independent of the set font.

**Comment by capdiem** [comment]
@OmidAtaei1984 Why not use global CSS(wwwroot/app.css) to set `font-family`?

**Comment by OmidAtaei1984** [comment]
> @OmidAtaei1984 Why not use global CSS(wwwroot/app.css) to set `font-family`?

Hello. As you can see in the picture, setting font-family in Body has no effect, but after setting Style in Program.cs, the desired font is applied.
![1](https://github.com/masastack/MASA.Blazor/assets/141127716/15004679-44dd-42e0-bc27-39401140dad5)
![2](https://github.com/masastack/MASA.Blazor/assets/141127716/5f9c8ece-6d75-4d50-aa6a-f15ba52e4c14)
![3](https://github.com/masastack/MASA.Blazor/assets/141127716/3ae03eab-5573-4d5b-8b0d-fd77cd85cbc7)
![4](https://github.com/masastack/MASA.Blazor/assets/141127716/e28aa367-6ab7-4092-98f8-05fd54aac596)

**Comment by capdiem** [comment]
@OmidAtaei1984 
![image](https://github.com/masastack/MASA.Blazor/assets/16507773/e9214f28-cb60-4917-9a19-2cbae1fd964a)

app.css: 
```css
.m-application {
  font-family: TheBlackList, ...
}
```

**Comment by OmidAtaei1984** [comment]
Hello. I made the settings, but there was no change in the font of the program. If I am wrong, please guide me.

![2024-01-06 (1)](https://github.com/masastack/MASA.Blazor/assets/141127716/39b1a82b-cbde-498d-938c-4aa9a78df468)
![2024-01-06 (2)](https://github.com/masastack/MASA.Blazor/assets/141127716/68799716-3cb5-47e7-9d5e-a9c306567703)

**Comment by capdiem** [comment]
@OmidAtaei1984 You should check the `font-family` of the text "Hello world" instead of `body`.

From your screenshot, it seems that the program did not restart successfully, causing app.css not to be reapplied.
