### ISSUE TITLE
[Bug Report]: MSimpleTable的Width并不是常规的宽度

### ISSUE THREAD

**Issue by Lee-Lily-Lea** [masastack/MASA.Blazor#1741]
### Masa.Blazor version

1.3.4

### Describe the bug

<img width="980" alt="b942ed81cc215d0024c23d01302b83c" src="https://github.com/masastack/MASA.Blazor/assets/78075553/f3221eb3-b133-4447-b6b5-d101e796bf72">
<img width="283" alt="a8202263a96b72e55d3c4eab8fc2c7d" src="https://github.com/masastack/MASA.Blazor/assets/78075553/1afc984f-a26a-4989-aa30-6a1ec8c60d9f">

见上图  Width更像是 容器内部的宽度而不是组件的宽度

### .NET version

net 8.0

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by capdiem** [comment]
@Lee-Lily-Lea 只能用Style去设置根元素的宽度。
