### ISSUE TITLE
[Bug Report]: MEditor ReadOnly API

### ISSUE THREAD

**Issue by enoughless** [masastack/MASA.Blazor#1742]
### Masa.Blazor version

1.0.0

### Describe the bug

MEditor ReadOnly属性不支持响应式，<MEditor @ref="@_editor" @bind-Value="_editorContent" Placeholder="请输入内容"  ReadOnly="flag"> flag值由true变false后，MEditor还是只读

**Comment by capdiem** [comment]
@enoughless 多谢反馈，目前你通过以下方式设置禁用或编辑模式：
```razor
<MEditor @ref="editor">...</MEditor>

@code {
  private MEditor editor;

  private void DisableEditor() {
    _ = editor.DisableAsync();
  }

  private void EnableEditor() {
    _ = editor.EnableAsync();
  }
}
```

后续我会等 quill 出了 v2 后重构一版，那时就不需要这么复杂了。

**Comment by capdiem** [comment]
@enoughless 1.4.0 会先支持readonly的响应。
