### ISSUE TITLE
MDataTable组件使用ItemDataTableExpandContent插槽无法实现替换图标

### ISSUE THREAD

**Issue by XGG33** [masastack/MASA.Blazor#1752]
### Masa.Blazor version

1.3.2

### Describe the bug

MDataTable组件使用ItemDataTableExpandContent插槽无法实现替换表格行展开图标
![de0a710428eb747dac0f75f01eb6bb3](https://github.com/masastack/MASA.Blazor/assets/91835837/721c7ae3-69af-42f3-810b-19f50c5bc274)
![0805bd9b60bf6661c50aab2ba4153f0](https://github.com/masastack/MASA.Blazor/assets/91835837/759fc5c5-f89c-4b40-8f6f-557cecb9255a)

**Comment by capdiem** [comment]
@XGG33 1.3.3 可以使用。你只是想自定义图标还是要自定义逻辑？如果自定义了这个插槽，很多逻辑要自己写。

**Comment by XGG33** [comment]
我需要的是把图标换成按钮并且有点击后展开的效果







------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月5日(星期一) 下午3:59
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [masastack/MASA.Blazor] MDataTable组件使用ItemDataTableExpandContent插槽无法实现替换图标 (Issue #1752)





 
@XGG33 1.3.3 可以使用。你只是想自定义图标还是要自定义逻辑？如果自定义了这个插槽，很多逻辑要自己写。

**Comment by capdiem** [comment]
默认的插槽是：
```razor
var expanded = IsExpanded(item);

<MIcon Class="@($"m-data-table__expand-icon {(expanded ? "m-data-table__expand-icon--active" : "")}")"
       OnClick="@(() => Expand(item, !expanded))"
       OnClickStopPropagation>
    @ExpandIcon
</MIcon>
```

你参照这个自定义就行。

**Comment by XGG33** [comment]
已解决，之前是我没有更新nuget 包导致自定义后默认的三角标没有被替换掉，谢谢





------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年2月5日(星期一) 下午4:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [masastack/MASA.Blazor] MDataTable组件使用ItemDataTableExpandContent插槽无法实现替换图标 (Issue #1752)





 
默认的插槽是：
 var expanded = IsExpanded(item); <MIcon Class="@($"m-data-table__expand-icon {(expanded ? "m-data-table__expand-icon--active" : "")}")"        OnClick="@(() =&gt; Expand(item, !expanded))"        OnClickStopPropagation&gt;     @ExpandIcon </MIcon&gt;
 
你参照这个自定义就行。
