### ISSUE TITLE
希望可用增加手动控制打开某个Page tab页的功能

### ISSUE THREAD

**Issue by g123413927** [masastack/MASA.Blazor#1753]
这个控件：component/PageTabs

目前的功能，只能跟随打开记录开启Tab，过滤功能也比较鸡肋，只能初始化的时候设置SelfPatterns，比如中途我想控制某个URL可用打开Page tab，是不行的。

类似的功能场景描述：

大部分功能，都是在默认tab页上打开的，然后想右键新tab页打开，类似浏览器的功能。现在这种功能，是无法实现的。

**Comment by capdiem** [comment]
抱歉，这需求不是这个组件的目的。
