### ISSUE TITLE
[Bug Report]: MSelect 无法正常工作

### ISSUE THREAD

**Issue by yingpanwang** [masastack/MASA.Blazor#1758]
### Masa.Blazor version

latest

### Describe the bug

绑定MSelect 无法工作
![image](https://github.com/masastack/MASA.Blazor/assets/49632937/a7ea38eb-202d-46d4-859d-dca0f9613690)

![image](https://github.com/masastack/MASA.Blazor/assets/49632937/12f22a17-f495-4202-b34a-af5e1d639d95)

### Expected Behavior

正常显示绑定项

### .NET version

.NET 8

**Comment by capdiem** [comment]
@yingpanwang 开启交互了吗？

**Comment by yingpanwang** [comment]
> @yingpanwang 开启交互了吗？

是需要配置什么属性吗 ? 我只绑定了如图的属性,运行后表现为 鼠标挪上去没有反应,没有预期选项的展示点击也没有反应.

**Comment by capdiem** [comment]
@yingpanwang 关于交互的内容去翻Blazor文档吧，一句话说不清楚。简单来说推荐你使用全局交互的模板，可以通过我们的CLI来创建：
```bash
dotnet new install MASA.Template
dotnet new masablazor -o MasaBlazorApp -ai
```

**Comment by yingpanwang** [comment]
> @yingpanwang 关于交互的内容去翻Blazor文档吧，一句话说不清楚。简单来说推荐你使用全局交互的模板，可以通过我们的CLI来创建：
> 
> ```shell
> dotnet new install MASA.Template
> dotnet new masablazor -o MasaBlazorApp -ai
> ```

我用的是这个模板

**Comment by yingpanwang** [comment]
> > @yingpanwang 关于交互的内容去翻Blazor文档吧，一句话说不清楚。简单来说推荐你使用全局交互的模板，可以通过我们的CLI来创建：
> > ```shell
> > dotnet new install MASA.Template
> > dotnet new masablazor -o MasaBlazorApp -ai
> > ```
> 
> 我用的是这个模板

@capdiem

**Comment by capdiem** [comment]
@yingpanwang 测试没啥问题

![image](https://github.com/masastack/MASA.Blazor/assets/16507773/06a15fcc-4a03-474b-a18e-344a995b98c3)

**Comment by yingpanwang** [comment]
@capdiem 这里是我的sln的 git https://github.com/yingpanwang/HNSelf-StudyExamination , 可以请您帮我看下吗?

**Comment by capdiem** [comment]
@yingpanwang 你用的不是全局交互。全局交互的App.razor里的 HeadOutlet 和 Routes 都要加 `@rendermode="交互模式"`。

**Comment by yingpanwang** [comment]
@capdiem  加上就好了,不好意思麻烦了.
