### ISSUE TITLE
[Bug Report]: MDataTable OutOfMemoryException

### ISSUE THREAD

**Issue by LeeCY-C** [masastack/MASA.Blazor#1785]
### Masa.Blazor version

1.3.4

### Describe the bug

列表通过ItemColContent指定Column显示内容时当放入一个img，且通过Base64传递Src时抛出内存溢出异常，不清楚是不是Base64字符串太长了导致的（我测试时Base64字符大概3M）
`                        <div style="display:flex;justify-content:center;">
                            <MTooltip Left>
                                <ActivatorContent>
                                    <MImage Src="@tableContext.Item.ImageDataOfBase64" Height="20" @attributes="@context.Attrs" />
                                </ActivatorContent>
                                <ChildContent>
                                    <span>Tooltip</span>
                                </ChildContent>
                            </MTooltip>
                        </div>`

### .NET version

.NET6

**Comment by capdiem** [comment]
@LeeCY-C 你可以把Image组件改成 `img` 标签试试，如果还发生那就不是组件的问题。请测试一下。

**Comment by LeeCY-C** [comment]
一开始就是Img，但是只要我不向Table的Items里面添加项就不会溢出，目前还不清楚原因

**Comment by capdiem** [comment]
@LeeCY-C “不向Table的Items里面添加项” 意思是只有动态添加才会异常吗？items一开始有数据，就不会异常？

**Comment by LeeCY-C** [comment]
Table一开始是空的，当我动态添加一个很长的Base64码后就异常了
