### ISSUE TITLE
PModal的关闭行为很诡异。

### ISSUE THREAD

**Issue by yangf85** [masastack/MASA.Blazor#1787]
为什么关闭的时候会清空Model的所有属性？

**Comment by capdiem** [comment]
@yangf85 你用了form表单模式吧，表单模式是这样的。

**Comment by yangf85** [comment]
> @yangf85 你用了form表单模式吧，表单模式是这样的。

是的

**Comment by capdiem** [comment]
@yangf85 就是这么设计的。提交完清空数据并关闭弹窗，关闭也会清空数据。

**Comment by yangf85** [comment]
> @yangf85 就是这么设计的。提交完清空数据并关闭弹窗，关闭也会清空数据。

为什么要这么设计呢，这样每次显示之前和保存之前都要创建一个新的对象

**Comment by capdiem** [comment]
@yangf85 我假设你的场景是表格行编辑，编辑时会对行的对象进行编辑，因为是引用类型，只要你编辑了，就算没保存，表格的那行数据也会被修改。文档的示例EditModel方法里会用ShallowCopy来克隆一个新对象，从而避免这个问题。

**Comment by yangf85** [comment]
> @yangf85 我假设你的场景是表格行编辑，编辑时会对行的对象进行编辑，因为是引用类型，只要你编辑了，就算没保存，表格的那行数据也会被修改。文档的示例EditModel方法里会用ShallowCopy来克隆一个新对象，从而避免这个问题。

哦，明白了

**Comment by yangf85** [comment]
> @yangf85 我假设你的场景是表格行编辑，编辑时会对行的对象进行编辑，因为是引用类型，只要你编辑了，就算没保存，表格的那行数据也会被修改。文档的示例EditModel方法里会用ShallowCopy来克隆一个新对象，从而避免这个问题。

![image](https://github.com/masastack/MASA.Blazor/assets/42733580/8dcdb13e-d866-4120-8817-78490ee202e2)

那框架自带的这个深拷贝工具，为什么老是出现这个异常？ 下面添加的的深拷贝方法没问题，编辑的深拷贝方法就报错

**Comment by capdiem** [comment]
@yangf85 具体我不清楚，你自己排查吧 https://github.com/force-net/DeepCloner
