### ISSUE TITLE
希望能对DataTable的自定义列也能进行排序

### ISSUE THREAD

**Issue by yangf85** [masastack/MASA.Blazor#1791]
![eb9d8f5a43a1ed0196c52f3791edb076](https://github.com/masastack/MASA.Blazor/assets/42733580/ddc6879a-29ce-433b-af1a-c6b5e30f6009)

![3ccc9955ff7c676bf202b40a4c47b05b](https://github.com/masastack/MASA.Blazor/assets/42733580/50a56766-a1ac-4158-bdaf-b6f39c538205)

实现了比较器
![ccc1f93bf164fcd6bbc4a7fb9946a0f6](https://github.com/masastack/MASA.Blazor/assets/42733580/19da39eb-d6b7-4d05-a3b0-04a91a618ece)

报错了
![008bf5cf0904268701166b0766c07909](https://github.com/masastack/MASA.Blazor/assets/42733580/3ec88fa9-117c-4e46-9e5b-05fc6e19d591)

**Comment by capdiem** [comment]
@yangf85 https://github.com/masastack/MASA.Blazor/blob/c55f832ee8a4549dc43ee271c5ded1d3365da866/src/Masa.Blazor/Components/Data/ItemValue.cs#L26

你需要实现 IComparable 接口。
