### ISSUE TITLE
DatePick能够默认提供一个在Form中使用的样式吗？

### ISSUE THREAD

**Issue by yangf85** [masastack/MASA.Blazor#1792]
![image](https://github.com/masastack/MASA.Blazor/assets/42733580/d6b79a98-e4f3-4860-93cb-a5c9c7e84469)

不然用textfield 的type=date ，风格不是很协调

**Comment by capdiem** [comment]
@yangf85 示例有，或者 https://docs.masastack.com/blazor/labs/date-time-pickers#

**Comment by yangf85** [comment]
> @yangf85 示例有，或者 https://docs.masastack.com/blazor/labs/date-time-pickers#

![image](https://github.com/masastack/MASA.Blazor/assets/42733580/b362fd35-5420-481b-b187-e7b397aa70ec)
这是什么原因？

**Comment by yangf85** [comment]
希望增加对datetime格式化的支持  
![image](https://github.com/masastack/MASA.Blazor/assets/42733580/afefb9c0-0057-436a-8fe3-b90eaebbd1a8)
现在直接使用datetime 作为绑定值，会出现时间显示

**Comment by capdiem** [comment]
@yangf85 把TextField的Value格式化就行了。
