### ISSUE TITLE
[Bug Report]: TreeView开启可选时有一些问题

### ISSUE THREAD

**Issue by Lee-Lily-Lea** [masastack/MASA.Blazor#1799]
### Masa.Blazor version

1.3.4

### Describe the bug

当key为Guid时

1. 不允许出现guid.Empty.
   本意是打算在一级上面做一个顶级 用于加载一级以及全选一级,随后发现这个问题, 目前采用Guid.NewGuid()一个处理
2. ValueChanged不能使用 async Task
   准确来说时 方法内部不能调用写task(我写的 Task.Delay预留处理时间)
3. 带有分步加载时 选择情况有误
   当有分布加载时, 勾选某一项时 他的次一级项会自动加载,但是次次一级(第三级)未加载,导致选择项会是次一级而不是第三级,这个不知道算不算bug, 逻辑上也正确 但是不符合预期

### .NET version

net 7.0

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by Lee-Lily-Lea** [comment]
新发现的bug
1. OnInput和ValueChanged冲突,导致要么拿不到实体 要么无法控制Value清空, 建议两者分开
2. Value清空时(SelectionType=Leaf) 会导致末端清空但上级✔勾选仍在
![image](https://github.com/masastack/MASA.Blazor/assets/78075553/7cf104de-5a44-4619-ae03-ae256e298581)
3. 初始化Items为空时 (new()) 后续重新赋值为有长度的值时 需要强刷页面(StateHasChanged)才能显示

**Comment by capdiem** [comment]
@Lee-Lily-Lea 
> 异步加载选择的问题，评论的第二个问题和第三个问题

应该是合并 masastack/BlazorComponent#555 之后出现的问题，计划暂时撤销此PR提交的代码。

> 不允许出现 guid.empty

不太清楚用法，能否提供Demo。

> ValueChanged 不能使用 async task

内部逻辑如此，你有什么业务需要这么做？

> OnInput和ValueChanged 冲突问题

下周会修复。

**Comment by Lee-Lily-Lea** [comment]
@capdiem 
Q:
> *异步加载选择的问题，评论的第二个问题和第三个问题*
> 
> 应该是合并 https://github.com/masastack/BlazorComponent/pull/555 之后出现的问题，计划暂时撤销此PR提交的代码。

A: 好的

---
Q:
> *不允许出现 guid.empty*
> 
> 不太清楚用法，能否提供Demo

A: 
你指的业务意义还是说例子就行?
- 例子: 
```CSharp
Items = new List<Item>()
{
    new Item()
    {
        Id = Guid.Empty
    }
};
```
- 意义: 打算在把所有的Items套在一个Item里 这个Item是无效数据 仅仅当作全选用 效果如下
- [x] 我是全选
  - [ ] 我是真的Item1 
  - [ ] 我是真的Item2
  - [ ] 我是真的Item3 

---
Q:
> *ValueChanged 不能使用 async task*
> 
> 内部逻辑如此，你有什么业务需要这么做？

A: 因为分步加载和✔勾选有冲突 所以打算自己做分布加载 现在可以不用管了

---
Q:
> *OnInput和ValueChanged 冲突问题*
> 
> 下周会修复。

A: 好的 Value对我没说其实没用 更需要List<Item> 但是OnInput没法重置 ✔勾选
