### ISSUE TITLE
[Bug Report]: Datatable的item渲染颜色失效

### ISSUE THREAD

**Issue by 88pmbfs88** [masastack/MASA.Blazor#1810]
### Masa.Blazor version

1.3.4

### Describe the bug

![image](https://github.com/masastack/MASA.Blazor/assets/32048227/f827866b-83b7-4640-a203-68658a446ccb)
![image](https://github.com/masastack/MASA.Blazor/assets/32048227/93ac0526-286c-41f2-aa20-df98bbc45060)
查询后，正常显示颜色
![image](https://github.com/masastack/MASA.Blazor/assets/32048227/b8cacb2a-f909-4efe-bd9f-b7cac3e939d6)

过滤查询，不显示红色
![image](https://github.com/masastack/MASA.Blazor/assets/32048227/3f8086b3-44c1-43de-967b-0a602eb6a413)

调试显示没有进入GetColor函数

### .NET version

8.0.203

**Comment by capdiem** [comment]
@88pmbfs88 过滤查询只是更改了items吗？

**Comment by 88pmbfs88** [comment]
> @88pmbfs88 过滤查询只是更改了items吗？

是的，调用了异步请求更新pageListResult，然后调用了StateHasChanged()

**Comment by capdiem** [comment]
@88pmbfs88 无法复现，请提供最小复现demo。

**Comment by 88pmbfs88** [comment]
> @88pmbfs88 无法复现，请提供最小复现demo。

https://github.com/88pmbfs88/MasaTest.git      你好，我写了demo，发现Mselect 无法选择和渲染没有颜色，麻烦看下是否我的工程配置有问题，谢谢了大佬

**Comment by capdiem** [comment]
@88pmbfs88 布局不对，需要根节点需要是 MApp。
```razor 
<MApp>
    <MMain> 
        @Body
    </MMain>
</MApp>
```
