### ISSUE TITLE
[Bug Report]: 官网无限滚动示例无法查看

### ISSUE THREAD

**Issue by Yu-Core** [masastack/MASA.Blazor#1820]
### Masa.Blazor version

1.4.0-beta.5

### Describe the bug

![2024-04-05_165545](https://github.com/masastack/MASA.Blazor/assets/96511239/3d333ddc-6317-4c45-a933-28b19655a9d8)
![2024-04-05_165647](https://github.com/masastack/MASA.Blazor/assets/96511239/7fd88f89-0538-4b39-95eb-bd59e00d5363)

https://docs.masastack.com/blazor/components/infinite-scroll

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Additional context

Ctrl+f5没有效果

**Comment by capdiem** [comment]
https://github.com/dotnet/aspnetcore/issues/15187, https://github.com/dotnet/aspnetcore/issues/16821

看来 ElementReference 不太合适作为参数传递给子组件，因为ElementReference.Id赋值后并不会通知子组件刷新，而且也不是引用类型，子组件无法在NextTick里拿到最新值~ 组件层不太好解决

**Comment by capdiem** [comment]
@Yu-Core 请使用Id或类选择器作为`Parent`的值。

**Comment by Yu-Core** [comment]
ok，谢谢
