### ISSUE TITLE
Pagination（分页）需要一个初始化事件

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1829]
分页初始化事件能否提供？现在只有前进后退 还有input时候事件？我需要一个刚展现时候的事件 就是初始化第一页时候

**Comment by capdiem** [comment]
@huxinshuo 有什么作用或者使用场景？

**Comment by huxinshuo** [comment]
if (first) {
需要类似这里first的事件
}
if (!first) 
{
}
如果有first 可以实现进入就展示 代码统一
如果没有first 需要点击按钮才能展示  然后翻页 这个体验很不好

**Comment by capdiem** [comment]
@huxinshuo 我还是不理解你的需求，Pagination组件默认是展示的。

**Comment by capdiem** [comment]
@huxinshuo 你说的是查询吗？可以在OnInit或OnAfterRender的fisrtRender里做查询。

**Comment by huxinshuo** [comment]
> @huxinshuo 你说的是查询吗？可以在OnInit或OnAfterRender的fisrtRender里做查询。

我试试看 ，就是能在Pagination里面加一个Initial事件是最好的。 现在是Pagination的翻页事件时候能查询 就缺少个Pagination自身的Initial事件 用于查询  。
  （OnInit或OnAfterRender的fisrtRender 这个是总页面初始化 时候）

**Comment by capdiem** [comment]
@huxinshuo 我们不会支持这样的东西，一般来说初始化查询都是放在oninit和onafterrender里，页面和自定义component都有这些事件。

**Comment by huxinshuo** [comment]
finished
