### ISSUE TITLE
Cards needs a Ondblclick="" 

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1837]
Cards needs a Ondblclick="" 
卡片需要一个双击事件，一般卡片包含图片和一些信息，点击一下可能只是选中然后复制文字什么的。  期望能够添加一个双击事件，以便跳转到其他界面以便查看详情。

**Comment by capdiem** [comment]
@huxinshuo `<MCard @ondblclick=""></MCard>` 就行了。
