### ISSUE TITLE
How to close the  Tab and it'sTabsItem easily？

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1839]
示例是可以删除最后一个的，因为不可能总是依次删除的，能否加个删除**当前选中选项卡**的快捷方式 ，如doubleClick？或者加个嵌入式删除按钮？
![微信截图_20240411142041](https://github.com/masastack/MASA.Blazor/assets/40190013/7a797e07-bb84-44b3-b7a6-b841d51c99b9)

**Comment by capdiem** [comment]
duplicate of #1434
