### ISSUE TITLE
Please update the code part of Tabs  what‘s in the Official website

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1842]
帮忙更新下官网Tabs的code部分，视图更新了 但是code还是旧的~ 感谢~
![微信截图_20240412103203](https://github.com/masastack/MASA.Blazor/assets/40190013/697d1fff-3908-4f1e-b448-c1e23a742306)

**Comment by capdiem** [comment]
@huxinshuo 奇怪，应该是cdn缓存问题，你可以先看 https://github.com/masastack/MASA.Blazor/blob/main/docs/Masa.Blazor.Docs/Examples/components/tabs/DynamicTabs.razor

**Comment by huxinshuo** [comment]
It is more perfect now!👍
