### ISSUE TITLE
Dose the MASA.Blazor have  imagebrowser component？

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1845]
MASA.Blazor有没有没有图片浏览组件呢？不是image组件。在文档里面好像没找到，就是像可以查看图片详情一样全屏，黑色背景的，可以放大、缩小、旋转之类的。

**Comment by capdiem** [comment]
@huxinshuo Sorry, there is currently no such component available.

**Comment by capdiem** [comment]
Open this until we add the component.
