### ISSUE TITLE
How to control Slider action of  of Mtabitem  of Tabs by hand

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1847]
能否提供开关以便手动控制Mtabitem的内容切换时候是不是滑动出现，正常情况下滑动是很好（比如初次展示），但是来回切换已经展现过的Mtabitem，不想让内容滑动出现。

**Comment by capdiem** [comment]
@huxinshuo MTabItem 设置 `Transition=""` 关闭动画。

**Comment by huxinshuo** [comment]
Thanks! It works.
