### ISSUE TITLE
How to keep the appbar distance fixed and remove the line of card？

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1856]
你好！
1，怎么让appbar的高度固定而不是自动？
2，怎么去除card的隐性线条（好像是title位置）？
谢谢！
![微信截图_20240417201928](https://github.com/masastack/MASA.Blazor/assets/40190013/a56b42d2-174e-4db5-aab1-ba022c4f1044)

**Comment by capdiem** [comment]
@huxinshuo 你是指AppBar高度固定还是位置固定？Card没有隐形线条，你查看html排查下吧。

**Comment by huxinshuo** [comment]
是想让appbar的高度固定，现在情况是：如果下面的conten比较少，appbar会向下拉伸。想让appbar不要拉伸， 一直保持固定高度这样的。
card的解决了 是html问题

**Comment by capdiem** [comment]
@huxinshuo appbar拉伸估计用了flex样式的问题，父元素也会影响的。正常的布局不会如此，你不是用模板生成的项目？有关基本布局：https://docs.masastack.com/blazor/components/application#
