### ISSUE TITLE
Can Textareas provide placeholder function？

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1859]
在例子里面是个value，能不能提供placeholder，就是灰色的提示，如果有文本那么placeholder会消失，不影响用户的输入。现在如果用户粘贴文本，value的内容会滞留在文本框。

**Comment by capdiem** [comment]
@huxinshuo 不明白你的意思，Textarea有Placeholder属性啊

**Comment by huxinshuo** [comment]
没问题了， 我看的是示例。api是有Placeholder的
