### ISSUE TITLE
Selects 有没有接受用户输入，然后动态提供下拉选项的功能？

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1869]
Selects 有没有接受用户输入然后动态提供下拉选项的功能？看了示例都是固定的下拉选项。 比如输入 一个字，然后返回可用的选项。

**Comment by capdiem** [comment]
@huxinshuo 有Autocomplete组件。

**Comment by huxinshuo** [comment]
我在事件里面加了MessageBox.Show(v); 没有任何提示会查出所有items :我先输入“山” 会显示“山”的内容 MessageBox也会提示“山”，然后重新点控件  MessageBox没有任何提示，却显示全部items ，说明没经过事件就查出了所有items ？
 private async Task QuerySelections(string v)
 {
     if (string.IsNullOrEmpty(v) || v == _select || v.Trim(' ') == "")
     {
     return;
     }

     _loading = true;
     MessageBox.Show(v);
     await Task.Delay(500);

**Comment by huxinshuo** [comment]
就是如果是“”会查出所有items  可是事件也没提示。 “”这个是不是输入的瞬间产生的？

**Comment by capdiem** [comment]
@huxinshuo 请提供完整的代码~

**Comment by huxinshuo** [comment]
private bool _loading;
 private List<string> items = new List<string>();
 private string _select;

 private async Task QuerySelections(string v)
 {
     if (string.IsNullOrEmpty(v) || v == _select || v.Trim(' ') == "")
     {
     return;
     }

     _loading = true;
     MessageBox.Show(v);
     await Task.Delay(500);
     items =ListFromDB(_select);
     _loading = false;
 }

**Comment by capdiem** [comment]
@huxinshuo 谁调的QuerySelections我也不知道呀 = =

**Comment by huxinshuo** [comment]
没事了，是调用错了~😂
