### ISSUE TITLE
Something about MBadge

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1871]
`<MButton  Style="margin:15px;"><MBadge Color="green" Content="66666666">测试</MBadge></MButton>`
嵌入在按钮内部时候 按钮长度没有伸缩
![QQ截图20240428051444](https://github.com/masastack/MASA.Blazor/assets/40190013/7f824a71-c502-42a0-9177-26161a74f997)

Content显示是stringnumber 却不支持string
![QQ截图20240428051754](https://github.com/masastack/MASA.Blazor/assets/40190013/618e39b4-cf3c-455c-9444-18aa0762eafa)

**Comment by capdiem** [comment]
@huxinshuo 正常，badge是绝对定位，你可以把它放外面，然后微调(Offset)。

**Comment by huxinshuo** [comment]
帮忙看下这个Content显示是stringnumber 却不支持string。

**Comment by capdiem** [comment]
@huxinshuo `Content="@("string")"`

**Comment by huxinshuo** [comment]
thanks
