### ISSUE TITLE
Color of Tabs

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1872]
现在的tab 颜色没法设置 ，默认是透明的
![QQ截图20240428060328](https://github.com/masastack/MASA.Blazor/assets/40190013/4c2104d6-e0b7-4382-b6ae-cf982e29e686)

能否单独设置Tab的颜色 这样辨识度就高了。

**Comment by capdiem** [comment]
@huxinshuo  Tabs 上试试设置 SliderColor、Color、BackgroundColor。

**Comment by huxinshuo** [comment]
好的
