### ISSUE TITLE
How to change the Editor's Theme by Switch？

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1885]
Editor（富文本编辑器）呈现后怎么切换样式？初始时候可以设置样式，呈现后可以切换样式吗？
`if (ThemeStyle == "snow") 
{
    ThemeStyle = "bubble";
}
else if
    (ThemeStyle == "bubble")
{
    ThemeStyle = "snow";
}`
这个好像无效

**Comment by capdiem** [comment]
@huxinshuo quilljs 好像不止动态更改 theme，你通过 @key 强制组件重新加载。`<MEditor @key="@ThemeStyle"/>`。

**Comment by huxinshuo** [comment]
Thanks
