### ISSUE TITLE
Carousels‘ content turn to blank if leave few Minutes then back to Carousels。

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1891]
如果离开几分钟 再回到包含Carousels的视图，Carousels的内容会变白色，过1分钟左右才重新展现出来。
![微信截图_20240506184603](https://github.com/masastack/MASA.Blazor/assets/40190013/4880ece6-abd0-4972-8fd8-184fb07de9ec)

**Comment by capdiem** [comment]
@huxinshuo Server吗？

**Comment by huxinshuo** [comment]
wpf+masa

**Comment by capdiem** [comment]
@huxinshuo 你使用的图片是本地图片还是远程地址图片？如果是远程地址且可能来自外网，感觉是一分钟请求完成图片是可能的~

**Comment by huxinshuo** [comment]
远程图片，刚生成的时候很快  是在taps里面切换的。 一开始是立刻生成的， 然后切换到其他tabs一会，再切换回来就会延迟加载

**Comment by capdiem** [comment]
@huxinshuo tabitems的元素包括图片一旦加载就会缓存在dom，理论上不会出现重新加载的情况。提供下可复现的代码吧。

**Comment by huxinshuo** [comment]
@capdiem 
    @code
    {
        private string[] items = new[]
        {
    "https://cdn.masastack.com/stack/images/website/masa-blazor/carousel/bird.jpg",
    "https://cdn.masastack.com/stack/images/website/masa-blazor/carousel/planet.jpg",
    };
    }
    <MCard Class="mx-auto" MaxWidth=1450 Style="margin:20px 0px; ">

    <MContainer Fluid Style="margin-left:5px">

                        <MCard  Tile=false Style="margin-left:5px">
                    <MCarousel Height="350" Cycle>
                        @foreach (var item in items)
                        {
                            <MCarouselItem Src="@item"
                                           ReverseTransition="fade-transition"
                                           Transition="fade-transition">
                            </MCarouselItem>
                        }
                    </MCarousel>
                </MCard>

 
    </MContainer>

</MCard>
放在2个razor里面 切换试试

**Comment by capdiem** [comment]
@huxinshuo 此代码我已经在WPF中试过了 没有复现

**Comment by huxinshuo** [comment]
@capdiem  好的 我再试试。
