### ISSUE TITLE
[Bug Report]: MSortable在BlazorWebView中无法通过鼠标拖动

### ISSUE THREAD

**Issue by zjgg888** [masastack/MASA.Blazor#1895]
### Masa.Blazor version

1.5.0

### Describe the bug

如题，在WebAssembly或Server下，都可以正常拖放，唯独在Windows下的BlazorWebView中，无法正常拖放（Mobile中也是可以的）

**Comment by capdiem** [comment]
@zjgg888 你好，我在WPF中测试没有问题。

**Comment by zjgg888** [comment]
是在MAUI项目中，Windows Platform，会出现这个问题。

**Comment by capdiem** [comment]
@zjgg888 https://github.com/dotnet/maui/issues/2205

**Comment by zjgg888** [comment]
所以是要等Microsoft.WindowsAppSDK 1.6才能解决这个问题是吧？

**Comment by capdiem** [comment]
@zjgg888 是的
