### ISSUE TITLE
怎么设置tabs 未激活项的文字颜色？

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1914]
激活的能看清楚，未激活的文字颜色怎么设置？“标题”2个字几乎看不到了
![微信截图_20240515131306](https://github.com/masastack/MASA.Blazor/assets/40190013/4ea66ca9-e473-4e86-8de4-a21d698d8788)

**Comment by capdiem** [comment]
@huxinshuo 默认下暗主题文字是白色，你可能设置了暗主题？但你的截图看起来是用了亮主题，不激活的文字应该是黑色的。
