### ISSUE TITLE
MSelect控件的ValueChanged事件怎么使用？

### ISSUE THREAD

**Issue by purvisdevgit** [masastack/MASA.Blazor#1922]
您好，我刚接触Blazor  

`        <MSelect @bind-Value="sVal"
                 ValueChanged="BusSelectChange"
                 Items="X.lVal"
                 ItemText="item => item"
                 ItemValue="item => item"
                 Color="pink"
                 Label="数据：">
@code{
  public void BusSelectChange()
  {
  }
}
`

    关于MSelect 控件的ValueChanged 事件如何实现文档不太清楚我没有搞明白，请问可以给个例子说明一下吗?

**Comment by capdiem** [comment]
@purvisdevgit @bind-Value 是 Value 和 ValueChanged 的简写方式。你这样写是重复了。你需要拿Value还是拿Item，其实你只需要用 OnSelect 事件就行了。

```razor
<MSelect TValue="string"
         TItem="string"
         TItemValue="string"
         @bind-Value="sVal"
         OnSelect="tuple => BusSelectChanged(tuple.Item)"
/>
```
