### ISSUE TITLE
How to use PConfirm?

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1923]
PConfirm 这个无效了 应该怎么使用？ 就是使用简单的msgbox。IPopupService 感觉混合在一起了，不是很明白。
官网上写 移除了该组件，请使用 IPopupService 服务的 ConfirmAsync方法。

**Comment by capdiem** [comment]
@huxinshuo PConfirm很早就删除了，大多数场景适用 [PopupService](https://docs.masastack.com/blazor/components/popup-service#) 就行了，自定义程度很高就用Dialog，也可以使用 PopupService 的高级方案弹出你自己的 Dialog。

**Comment by huxinshuo** [comment]
好的 感谢
