### ISSUE TITLE
MImage  can‘t display image

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1924]
`<MCard Style="margin-left:50px;margin-right:50px;margin-top:20px;">
<MRow Dense>
    <MCol Cols=4 >
             <MImage Src="https://q4.itc.cn/images01/20240517/13f999a20f6e4c308237b32acaa91af5.png" Height=180>
            </MImage>
    </MCol>
</MRow>
 </MCard>`    
![微信截图_20240519143423](https://github.com/masastack/MASA.Blazor/assets/40190013/7a280466-26cd-4257-b61a-bf341f66fb7d)
services 模式

**Comment by capdiem** [comment]
@huxinshuo Server模式无法复现。

**Comment by huxinshuo** [comment]
能否排查下`<img Src="https://q4.itc.cn/images01/20240517/13f999a20f6e4c308237b32acaa91af5.png" Height=160>`
换成原生的img 就能显示 
![微信截图_20240520071308](https://github.com/masastack/MASA.Blazor/assets/40190013/2d71b423-78c9-454c-b247-6d79db2543f5)

**Comment by capdiem** [comment]
@huxinshuo 我无法复现，你需要把可以复现的项目上传到github。
