### ISSUE TITLE
日期选择器能不能简化下？

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#1925]
日期选择器能不能简化下？
日期选择器有点太复杂 2个控件（文本框和日历）组成，然后还要转换 传值，能不能合并成一个简单的控件 日历能不能不要用户参与太多，不要用户去设置日历是怎么传到文本框的。

**Comment by capdiem** [comment]
@huxinshuo 目前没有进一步整合的计划，你可以在自己的项目里封装一下使用。
