### ISSUE TITLE
[Bug Report]: ErrorHandler Problem

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#1928]
### Masa.Blazor version

latest

### Describe the bug

![image](https://github.com/masastack/MASA.Blazor/assets/104096256/e96447a7-138c-483f-8fd0-cf2aee66b8b7)

When it's dark

**Comment by capdiem** [comment]
@wisamidris7 Thanks for reporting this issue, this is just a DEMO issue:
```diff
- ContentClass="white pa-4"
+ ContentClass="pa-4"
```
