### ISSUE TITLE
[REQUEST] Square icon-only button with background

### ISSUE THREAD

**Issue by IzaacJ** [masastack/MASA.Blazor#1931]
**Is your feature request related to a problem? Please describe.**
Square icon-only button without text that keeps the background

**Describe the solution you'd like**
A prop that enables the button to keep the background when using IconName and the button has no additional content

**Describe alternatives you've considered**
Button with LeftIconName and no text, Button with RightIconName and no text, but there is an offset added to the icon.

**Additional context**
Something like this would be great:
```
<MButton Background IconName="mdi-plus" />
```

**Comment by capdiem** [comment]
@IzaacJ Thanks for contacting us. I believe the style you described is not recommended by material design, so I think it is unreasonable to add a new prop to support it.  But you can do it with the following code:
```diff
- <MButton Color="pink" IconName="mdi-plus" />
+ <MButton Class="pink" IconName="mdi-plus" />
```

**Comment by IzaacJ** [comment]
Thanks! That led me to what I was after.

```
<MButton Class="pink white--text" IconName="mdi-plus" Style="border-radius: 4px;" />
```

**Comment by capdiem** [comment]
@IzaacJ border-radius also has built-int CSS:
```razor
<MButton Class="pink white--text rounded" ... />
```
