### ISSUE TITLE
[Bug Report]: DataTableHeader 列Width 样式值缺少 ‘PX’

### ISSUE THREAD

**Issue by MadCode1982** [masastack/MASA.Blazor#1935]
### Masa.Blazor version

1.5.2

### Describe the bug

![image](https://github.com/masastack/MASA.Blazor/assets/67041064/84ac4fa7-7c2b-42af-9843-9aed830afa60)

**Comment by capdiem** [comment]
@MadCode1982 如果值是数值类型会加上默认单位`px`，如果是字符串类型则不会，所以字符串你需要写全`300px`。
