### ISSUE TITLE
# 文档api注释 继承问题

### ISSUE THREAD

**Issue by Lee-Lily-Lea** [masastack/MASA.Blazor#2009]
组件之间存在继承关系  继承的参数属性的注释应当遵循父类组件的注释
当前并没有实现自动获取父类组件注释的功能

同时应当将每个组件的api的 lang.json 文件隔离开 而不是如下所示
![1719566219795](https://github.com/masastack/MASA.Blazor/assets/78075553/c0cd841b-11d3-45a9-8f2a-d61ea9f289a9)

**Comment by capdiem** [comment]
@Lee-Lily-Lea button-groups和button不是继承关系，textfield和select是继承关系。

**Comment by Lee-Lily-Lea** [comment]
> @Lee-Lily-Lea button-groups和button不是继承关系，textfield和select是继承关系。

。。两个问题
一个是继承问题
一个是JSON文件重复

**Comment by capdiem** [comment]
@Lee-Lily-Lea json重复用page-to-api就能解决 😂

**Comment by capdiem** [comment]
#2020 已解决。
