### ISSUE TITLE
文档中datepickers存在重复

### ISSUE THREAD

**Issue by Lee-Lily-Lea** [masastack/MASA.Blazor#2010]
日期选择器和月份选择器是同一个组件 但是文档目录结构以两个来考虑了
同一个组件api相同, 仅仅只是示例的侧重点不同
建议合并示例 两个page合成一个

![image](https://github.com/masastack/MASA.Blazor/assets/78075553/68c71103-0529-4629-94cc-ac54e0a11ef0)
![image](https://github.com/masastack/MASA.Blazor/assets/78075553/430c08f6-41c9-4fe7-b3eb-b636dc28f6ff)
![image](https://github.com/masastack/MASA.Blazor/assets/78075553/d456d722-0277-4a04-9cba-7b81596a93b3)
![image](https://github.com/masastack/MASA.Blazor/assets/78075553/dc4b151d-31dc-4fbe-b53b-5e77a7f3a9b4)

**Comment by capdiem** [comment]
@Lee-Lily-Lea 虽然是同一个组件，但是已有内容可以非常清晰地介绍各自的功能。如果删除现有的month文档，移入date页，会比较麻烦和混乱，所以决定不迁移。
