### ISSUE TITLE
Please include the copyright notice of AntDesign Blazor

### ISSUE THREAD

**Issue by ElderJames** [masastack/MASA.Blazor#2019]
Hello MASA Team,

Given that BlazorComponent was built on top of an earlier version of AntDesign Blazor, MASA.Blazor recently [merged BlazorComponent code](https://github.com/masastack/MASA.Blazor/pull/1936), according to MIT license, please include the copyright notice of AntDesign Blazor in MASA.Blazor.

The license is as follows:
https://github.com/ant-design-blazor/ant-design-blazor/blob/master/LICENSE

Best regards,
James Yeung

**Comment by capdiem** [comment]
@ElderJames 

Thank you for reminding us about the licensing issues regarding AntDesign Blazor. After careful evaluation, we have found that the MASA.Blazor codebase has diverged significantly from the original ant-design-blazor code, with very little direct use of the original work.

Nonetheless, our team has decided to include the AntDesign Blazor copyright notice in MASA.Blazor. We believe this better reflects our respect and appreciation for the original work.

We place great value on intellectual property rights and open-source contributions, and we aim to continue the development of MASA.Blazor in a legally compliant manner. If you have any other opinions or suggestions, please feel free to let us know.

Wishing you all the best!

Best regards,
The MASA Team
