### ISSUE TITLE
表格可以实现行的双击事件（或者列类型是按钮） 以便查看对应行数据的功能吗？

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#2045]
表格可以实现行的双击事件（或者列类型是按钮） 以便查看对应行数据的功能吗？ 比如表格只是简单的展示标题，双击该行（可以跳转到其他页面查看详情，这里需要双击事件 同时能获取到当前选择的第几行）。

**Comment by capdiem** [comment]
@huxinshuo 请查看文档API事件的内容，我相信是有双击事件的。

**Comment by huxinshuo** [comment]
@capdiem  😊看到了
