### ISSUE TITLE
怎么获取Data tables当前行的数据集合（Dessert） 或者 当前行的序号？

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#2049]
怎么获取Data tables当前行的数据集合（Dessert） 或者 当前行的序号？
看api有value | IEnumerable<TItem> 但是绑定了说不能指定什么的，能方便的获取到当前行的数据集合或者当前行的序号吗？

**Comment by capdiem** [comment]
@huxinshuo 什么操作下去获取呢？

**Comment by huxinshuo** [comment]
@capdiem 双击行操作-> 想获得当前行的数据

**Comment by capdiem** [comment]
![image](https://github.com/user-attachments/assets/741c43b3-8f8d-4e8d-9bd1-d05a52e4468f)

**Comment by capdiem** [comment]
@capdiem 文档不是有吗 = =

**Comment by huxinshuo** [comment]
MDataTable Stripe @ondblclick="()=>showDetail()"
        Headers="_headers"
                Items="_desserts"
                Width="@("120%")"
                ItemKey="r => r.Name"
                Class="elevation-1">
 </MDataTable>

private async Task showDetail()
{
MessageBox.Show(**<TItem>Item.ElementAt(0).Name**);
}

帮忙看下 不知道回调的item是怎么写 加粗的部分
下面的好像也不行
DataTableRowMouseEventArgs<TItem>

**Comment by capdiem** [comment]
@huxinshuo 
OnDblClick 不是 @ondblclick

**Comment by huxinshuo** [comment]
@capdiem 主要不是上面那个 上面事件没问题的  那个是blazor带的@ 在这个会自动加粗
加粗是下面的_Item.Name_ 这个应该怎么写。

**Comment by capdiem** [comment]
@huxinshuo 被你误导了，不是OnDblClick，而是OnRowDblClick，API的名称和类型我都截图了。
``` cs
private void OnRowDblClick(DataTableRowMouseEventArgs<替换成你的Item类型> args)
{
    // args.Item
}
```

**Comment by huxinshuo** [comment]
@capdiem 
<MDataTable Stripe OnRowDblClick="*******"
    Headers="_headers"
这个****里面该怎么写 下面这个函数怎么填入里面
private void OnRowDblClick(DataTableRowMouseEventArgs<替换成你的Item类型> args)
{
    // args.Item
}
![QQ截图20240718183330](https://github.com/user-attachments/assets/311b2930-e112-4d4b-84d8-aa179c5e3e44)

**Comment by huxinshuo** [comment]
能否提供像context.Item.Name 这中简单的当前item  可惜这context.Item 只能在 <ItemColContent>内使用

**Comment by capdiem** [comment]
@huxinshuo EventCallback<T> 不知道怎么赋值吗？
```razor
<MDataTable OnRowDblClick="(args) => Href(args.Item.Name)" />
```

**Comment by huxinshuo** [comment]
@capdiem 感谢，可以了。👍

**Comment by huxinshuo** [comment]
@capdiem 感谢，可以了。👍
