### ISSUE TITLE
Data tables可以隐藏列吗？ShowSelect后续怎么获得选择的行数据？

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#2050]
1 Data tables可以隐藏列吗？
因为查询明细数据需要ID  显示ID有时候不美观  可以隐藏列吗？如果再按行号去另外一个list查ID 也不是很友好。

2 行选择功能 ShowSelect后续怎么获得选择的行数据？
示例有：@bind-Value="_selected"
  private IEnumerable<Dessert> _selected = new List<Dessert>();
  }

关键如何获得选中的行数据的集合呢？
选中了 后续还是要对数据进一步处理的。

**Comment by capdiem** [comment]
@huxinshuo 没说类的所有属性你都要显示啊，headers你设置了什么就显示什么。@bind-Value 是拿到ItemKey的 Key的集合。API里不是有个OnItemSelect的事件吗？

**Comment by huxinshuo** [comment]
@capdiem  意思是选中行变化时 bind-Value会自动更新 对吗？

**Comment by capdiem** [comment]
@huxinshuo 是的

**Comment by huxinshuo** [comment]
好的，感谢！
