### ISSUE TITLE
页面堆栈缺少返回回调

### ISSUE THREAD

**Issue by Lee-Lily-Lea** [masastack/MASA.Blazor#2051]
当使用页面堆栈时

从page/tab A push到pageB时

当B返回A的时候  无法通知A

例如A作为列表页
B作为列表某项详情页, 在B页面包含对该项的数据修改
修改后返回A时 A无法主动更新

**Comment by capdiem** [comment]
PageA 可以继承PStackPageBase后重写OnPageActivated做到。Tab 页暂时没有内置的可行方式。
