### ISSUE TITLE
[Bug Report]: Page stack 使用data-page-stack-strategy点击自动入堆栈时快速点击多次会重复打开。

### ISSUE THREAD

**Issue by Leo0216** [masastack/MASA.Blazor#2053]
### Masa.Blazor version

1.6.1

### Describe the bug

`<MButton IconName="mdi-cog-outline"
         Width="32"
         Height="32"
         Href="@($"/sensorconfig/1")"
         data-page-stack-strategy="push" />`

使用堆栈页面，如上代码打开新的页面时，如果重复点击（点击过快）会导致页面一次性打开多个，如何解决这个问题？

### Expected Behavior

点击按钮后，直到新页面打开之前，重复点击不生效。

### .NET version

.net 8

**Comment by capdiem** [comment]
@Leo0216 暂时没有办法在原生的a标签上做到防抖，引入了一个新的组件 PPageStackLink，用法和a标签一直，但不用写 data-page-stack-strategy 了
