### ISSUE TITLE
datatable列的宽度能否自动和加一个可以调整列宽的功能

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#2056]
1 datatable列的宽度如果没设置能否自动宽度?
2 datatable能否加一个可以调整列宽的功能？
3 datatable 有时候太宽了 能否在底部加一个滚动条

![微信截图_20240719223812](https://github.com/user-attachments/assets/b3235dc5-9460-440f-a9dd-78d8eb7f8f8b)

**Comment by capdiem** [comment]
@huxinshuo 默认是根据单元格内容自动宽度。调整列宽文档有示例。滚动条simpletable也有示例。

**Comment by huxinshuo** [comment]
@capdiem

**Comment by capdiem** [comment]
@huxinshuo 文档都有
