### ISSUE TITLE
MPagination增加`MiniVariant`属性 实现迷你模式

### ISSUE THREAD

**Issue by Lee-Lily-Lea** [masastack/MASA.Blazor#2069]
效果如下图
![image](https://github.com/user-attachments/assets/8cd23107-b1cb-4d37-9dd5-30b87b4c00f3)
![image](https://github.com/user-attachments/assets/1e6841a1-ca12-496e-87c9-43266da1cf8f)

额外
- 开放插槽 `x-Content`
不提供Value等参数, 因为本身就是外部提供的
- 开放插槽位置的class及style `x-Class` `x-Style`
和插槽二选一
- 提供`AutoMini`属性 类型`Breakpoints?`
根据输入的Breakpoints, 在对应断点自动切换成MiniVariant=true
默认值null, 即不控制

---
# pr by me @Lee-Lily-Lea 
@capdiem

**Comment by capdiem** [comment]
@Lee-Lily-Lea Where is PR?

**Comment by capdiem** [comment]
@Lee-Lily-Lea 
- 不用插槽
- 不用Class Style，你给新增的元素加class就行了
```html
<div class="m-pagination__mini">
  <span class="m-pagination__current"></span>
  <span class="m-pagination__separator">/</span>
  <span class="m-pagination__total"></span>
</div>
```
- AutoMini的功能不急，加的话建议默认支持而不是新加属性。

**Comment by Lee-Lily-Lea** [comment]
> @Lee-Lily-Lea 
> - 不用插槽
> - 不用Class Style，你给新增的元素加class就行了
> ```html
> <div class="m-pagination__mini">
>   <span class="m-pagination__current"></span>
>   <span class="m-pagination__separator">/</span>
>   <span class="m-pagination__total"></span>
> </div>
> ```
> - AutoMini的功能不急，加的话建议默认支持而不是新加属性。

👌🏻

**Comment by capdiem** [comment]
#2072
