### ISSUE TITLE
[Bug Report]: Every like 50 seconds to 100 seconds it says this issue

### ISSUE THREAD

**Issue by wisamidris7** [masastack/MASA.Blazor#2076]
### Masa.Blazor version

1.6.6

### Describe the bug

When I'm using my application a error appears that failed to fetch and when I checked the Network tab this is the issue

![image](https://github.com/user-attachments/assets/ff07d858-5285-4993-902d-c8f3692358fa)
![image](https://github.com/user-attachments/assets/bc128e91-5a42-4281-bb1b-bb818de4b39a)

And this problem appear in both

![image](https://github.com/user-attachments/assets/afa0a70f-a8d1-4eb4-91cc-55eb7e86e553)

And this problem appear in ouside-click.js
![image](https://github.com/user-attachments/assets/6f5a692b-3330-4e36-b21a-a537730aaf52)

And transilition.js
![image](https://github.com/user-attachments/assets/537a41aa-484a-40a5-8135-23315c33ec8c)

### What browsers are you seeing the problem on?

Chrome

**Comment by capdiem** [comment]
@wisamidris7 This issue could occur due to your program crashing or other factors. The information provided is currently insufficient to confirm if it is a bug in the component library.

**Comment by wisamidris7** [comment]
It seem this problem only appears on OutOfMemory exception thanks!
