### ISSUE TITLE
[Bug Report]: MAUI Blazor iOS和Mac OS发布时Minput报错Attempting to JIT compile method, while running in aot-only mode

### ISSUE THREAD

**Issue by byte-book** [masastack/MASA.Blazor#2082]
### Masa.Blazor version

1.6.5

### Describe the bug

1、Winform blazor、MAUI Blazor  Android不存在问题。
2、MAUI Blazor iOS 或Mac OS 在Release模式下运行时存在问题，而Debug模式则不存在问题。
出现问题的组件，MTextField或MSelect表单输入组件，只要UI不显示这些控件则没有问题。

![IMG_0067 2](https://github.com/user-attachments/assets/5456d54c-371a-4b66-9edb-32ce20c78537)

### Reproduction code

```razor
<MTextField Filled Dense Type="number" @bind-Value="@Value"/>

@code
{
    public int Value {get;set;} = 8;
}
```

### .NET version

dotnet 8.0

**Comment by capdiem** [comment]
@byte-book 我查找了下类似的问题，可能有两种方式可以解决此问题：

1. https://github.com/MudBlazor/MudBlazor/issues/6558 中提到的

```xml
<PropertyGroup>
   <MtouchLink>None</MtouchLink>
   <UseInterpreter>True</UseInterpreter> 
</PropertyGroup>
```
2. 使用 .NET 8.0.7

**Comment by byte-book** [comment]
> @byte-book 我查找了下类似的问题，可能有两种方式可以解决此问题：
> 
> 1. [[Solution] MudBlazor not working with MAUI Blazor on iOS MudBlazor/MudBlazor#6558](https://github.com/MudBlazor/MudBlazor/issues/6558) 中提到的
> 
> ```
> <PropertyGroup>
>    <MtouchLink>None</MtouchLink>
>    <UseInterpreter>True</UseInterpreter> 
> </PropertyGroup>
> ```
> 
> 2. 使用 .NET 8.0.7

之前使用的就是 .NET 8.0.7，使用方法1解决了，现在IOS和Mac OS都不报错了
