### ISSUE TITLE
[ECharts] add support for candlestick data

### ISSUE THREAD

**Issue by karuzzo** [masastack/MASA.Blazor#2109]
Unfortunately, when I try to add candlestick data to the chart, I get an error. This data type is probably not currently supported.I'll be looking forward to the implementation, thank you!
![Снимок экрана 2024-08-21 014619](https://github.com/user-attachments/assets/4a812590-7ee4-4e99-baa9-4cc6c7876f20)

**Comment by capdiem** [comment]
@karuzzo Hello, I believe there might be a syntax error in your code!

```cs
Data = new List<int[]>
{
    new int[] { 100, 200, 10, 150 },
    new int[] { 150, 220, 70, 150 },
    new int[] { 200, 250, 150, 200 },
    new int[] { 300, 350, 250, 300 },
    new int[] { 200, 300, 180, 200 },
    new int[] { 100, 200, 80, 100 }
}
```

**Comment by karuzzo** [comment]
You are right, thank you!
