### ISSUE TITLE
[Bug Report]: 关于MBaiduMap组件，添加Marker

### ISSUE THREAD

**Issue by daipeng0809** [masastack/MASA.Blazor#2125]
### Masa.Blazor version

1.7.0

### Describe the bug

我使用MBaiduMap组件，按照实例子中的方式，添加Marker点，无反应，怎么办？
顺便问一下，Marker能不能自定义图标？？
`<MBaiduMap Height="540" @ref=_map`
           `DarkThemeId="9828881e7efb0182edb48236a3b53293"`
           `Style="width:90%; left:5%"`
           `Zoom="15" EnableScrollWheelZoom`
           `Center="new(116.403622f,39.918145f)">`
`</MBaiduMap>`

`@code {`
   ` private MBaiduMap? _map;`
   ` private MBaiduMarker? _addExampleMarker;`
    `private async Task AddMarker()`
    `{`
       ` if (_addExampleMarker is null)`
          `  _addExampleMarker = new()`
          ` {`
              `  Point = new(116.403874f, 39.911919f),`
              `  Title = "天安门",`
            `};`
      `  if (await _map.ContainsOverlayAsync(_addExampleMarker))`
           ` return;`
       ` await _map.AddOverlayAsync(_addExampleMarker);`
   ` }`
`}`

**Comment by capdiem** [comment]
@daipeng0809 添加marker确实报错了，多谢反馈。
