### ISSUE TITLE
[Bug Report]: MAppBarNavIcon 给IconName值会出现两个图标

### ISSUE THREAD

**Issue by TAnsz** [masastack/MASA.Blazor#2145]
### Masa.Blazor version

1.7.2

### Describe the bug

![1726016091426](https://github.com/user-attachments/assets/6d163f8d-3d36-4786-9712-983c9e6fd5f3)

### Reproduction code

```razor
<MCard Class="overflow-hidden">
    <MAppBar>
        <MAppBarNavIcon IconName="mdi-home"></MAppBarNavIcon>
    </MAppBar>
    <MSheet Class="overflow-y-auto" MaxHeight="600" Id="scrolling-techniques-6">
        <MContainer Style="height: 1000px;"></MContainer>
    </MSheet>
</MCard>
```

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by capdiem** [comment]
@TAnsz 是有点问题，虽然AppBarNavIcon的意义就是给切换导航用的，并没有太多其他意义。你可以使用`<MButton IconName="mdi-home" />`。后续会发v1.7.3解决此问题。
