### ISSUE TITLE
DrawFlow组件的扩展

### ISSUE THREAD

**Issue by Naoki326** [masastack/MASA.Blazor#2148]
原先的drawflow组件有很多局限性，我在原drawflow的基础上写了一个状态机工具
[代码地址]((https://github.com/Naoki326/AnotherFSM))
[demo地址](https://naoki326.github.io/AnotherFSM)

**Comment by capdiem** [comment]
@Naoki326 非常棒的项目！这个组件之前是打算用来做工作流的，后面那个项目暂停了就没有进一步地深入开发了。你需要我在文档上给你的 https://github.com/Naoki326/AnotherFSM 项目引流吗？

**Comment by Naoki326** [comment]
好的呀
