### ISSUE TITLE
[Bug Report]: MIcon与之相关的程序错误

### ISSUE THREAD

**Issue by zdp120** [masastack/MASA.Blazor#2155]
### Masa.Blazor version

1.72

### Describe the bug

Multiple constructors accepting all given argument types have been found in type 'Masa.Blazor.ToggleableTransitionElement'.
只要调用与icon相关的标签，都显示程序报错，用的是.net 9 rc1的版本。当退回到。net8.0，程序就可以正常工作了。

### .NET version

9.0 rc1

**Comment by capdiem** [comment]
It seems to be a breaking change in .NET 9. https://github.com/dotnet/aspnetcore/issues/57231
