### ISSUE TITLE
[Bug Report]: 在Ppage stack里面用MPagination组件翻不了页是怎么回事啊

### ISSUE THREAD

**Issue by zdp120** [masastack/MASA.Blazor#2169]
### Masa.Blazor version

1.7.3

### Describe the bug

<MPagination @bind-Value="pageIndex" TotalVisible="5" Length="pageCount" @onclick="Pagination" Circle ></MPagination>
layout用的是ppagestack，没有办法翻页，报错找不到页面。

### .NET version

9.0 rc1

**Comment by capdiem** [comment]
@zdp120 你的代码里用的是 `@OnClick` 而不是 `OnClick`？可能因此报错刷新了？
