### ISSUE TITLE
DrawFlow那块，节点拖拽优化

### ISSUE THREAD

**Issue by cc3w** [masastack/MASA.Blazor#2170]
将节点拖拽到画布上，单击节点，触发其他事件比如对话框、模态框等，再点击关闭对话框、模态框之后，节点将瞬间出现在鼠标位置，情况就是鼠标自动选中了节点，节点跟随鼠标的移动而移动。我尝试了以下方案均没有效果：
①关闭对话框或者模态框的时候取消节点的选中。
②尝试改变节点触发对话框方式，双击触发对话框。

**Comment by capdiem** [comment]
@cc3w 能提供复现的代码或项目吗？

https://github.com/masastack/MASA.Workflow/blob/32c813f80a2db1e571f00a9b512a001217f8deae/src/Web/Masa.Workflow.ActivityCore/Components/ActivityNode/ActivityNode.razor#L14
我这有个很久之前的项目，没有出现这种问题，当然它使用的 Masa.Blazor 版本也是比较旧的版本。

**Comment by cc3w** [comment]
照着DrawFlow提供的实例改的，节点用的是MDrag
<div class="d-flex mb-4">
    @for (int i = 0; i < s_colors.Length; i++)
    {
        var color = s_colors[i];
        <MDrag DataValue="@($"{color}")" Class="@($"example-drawflow-node {color}")">
            @ColorNodeType[color].FirstOrDefault().Value
        </MDrag>  
    }


    <div class="d-flex align-center ml-auto">
        <MButton Color="primary" MinWidth=80 Height=32 Class="mr-3" OnClick="@SaveAsync">
            保存
        </MButton>
        <MButton Color="error" MinWidth=80 Height=32 Class="mr-3" OnClick="@ClearAsync">
            清空
        </MButton>
        <MButton Color="warning" MinWidth=80 Height=32 Class="mr-3" OnClick="@OpenImportDialog">
            导入
        </MButton>
        <MButton Color="warning" MinWidth=80 Height=32 Class="mr-3" OnClick="@ExportAsync">
            导出
        </MButton>
    </div>

</div>

<MDrawflow Class="example-drawflow-workspace"
           Mode="DrawflowEditorMode.Edit"
           OnDrop="@DropAsync"
           OnNodeDataChanged="@NodeDataChange"
           OnNodeSelected="@OnNodeSelectedAsync"
           OnNodeUnselected="@NodeUnSelectAsync"
           @ref="_drawflow">
</MDrawflow>



<PModal @bind-Value="isOpenFlowNode"
        FormModel="addOrUpdateFlowNodeDTO"
        Title="编辑节点流转条件"
        Width="350"
        Persistent="true"
        CancelText="取消"
        SaveText="保存"
        OnSave="SaveFlowNode"
        OnCancel="CancelSaveFlowNode"
        class="modal-right-centered">

    <MRow>
        <MCol Cols="12">
            <MTextField @bind-Value="addOrUpdateFlowNodeDTO.CurrNodeInfoId" Dense Outlined Required/>
        </MCol>
        <MCol Cols="12">
            <MTextField @bind-Value="addOrUpdateFlowNodeDTO.NextNodeInfoId" Dense Outlined Required/>
        </MCol>
        <MCol Cols="12">
            <MTextField @bind-Value="addOrUpdateFlowNodeDTO.FlowCondition" Dense Outlined />
        </MCol>
        <MCol Cols="12">
            <MTextField @bind-Value="addOrUpdateFlowNodeDTO.Description" Dense Outlined />
        </MCol>
    </MRow>
</PModal>

**Comment by capdiem** [comment]
@cc3w workflow项目里的Node组件只是包了一层MDrag，MDrag组件没文档，跟着示例固定用法就行。PDrawer文档里有，搜Drawer。你提供的代码我不知道你是怎么触发Modal弹出来的。workflow项目我是用了[最佳实践](https://docs.masastack.com/blazor/labs/drawflow#section-67004f735b9e8df5)的自定义元素生成节点的。

**Comment by cc3w** [comment]
绑定了<MDrawflow>组件的这个OnNodeSelected="@OnNodeSelectedAsync"，在OnNodeSelectedAsync方法中给isOpenFlowNode 赋值为true，即打开模态框

**Comment by capdiem** [comment]
@cc3w ok 我会尝试复现看看

**Comment by cc3w** [comment]
> @cc3w workflow项目里的Node组件只是包了一层MDrag，MDrag组件没文档，跟着示例固定用法就行。PDrawer文档里有，搜Drawer。你提供的代码我不知道你是怎么触发Modal弹出来的。workflow项目我是用了[最佳实践](https://docs.masastack.com/blazor/labs/drawflow#section-67004f735b9e8df5)的自定义元素生成节点的。

如图所示，并没有PDrawer相关信息，[[文档地址](https://docs.masastack.com/blazor/labs/)](https://docs.masastack.com/blazor/labs/)
![image](https://github.com/user-attachments/assets/0894484d-abd4-4fb0-8161-048cdfdc3802)

**Comment by cc3w** [comment]
好的，这件事说来话长，总的来说，我后面在触发OnNodeSelected事件里面，加个了StateHasChanged()方法，鼠标自动选中节点的问题得到解决。
另外我之前尝试使用最佳实践的推荐方式，发现给自定义组件的参数赋不上值，想问一下最佳实践使用的是Microsoft.AspNetCore.Components.CustomElements是哪个版本，我看了 Microsoft.AspNetCore.Components.CustomElements
正式版支持的最低是.net7

**Comment by capdiem** [comment]
@cc3w Microsoft.AspNetCore.Components.CustomElements 跟着你的.net 版本走就行了。最佳实践里的代码复制粘贴也不能生效吗？
