### ISSUE TITLE
[Bug Report]: .net maui blazor应用开发，PPageStak组件使用时，导致页面不能下拉到底，时不时的卡住

### ISSUE THREAD

**Issue by zdp120** [masastack/MASA.Blazor#2172]
### Masa.Blazor version

1.7.3

### Describe the bug

`
<PPageStack TabbedPatterns="@(["^/$","/tj","/hq","/shipan","/rank","/account","/d"])"  FallbackUri="/"
                         SelfPatterns="@(["/rank"])" >
                @Body    
            </PPageStack>
`

我用这个做母模版的时候，很多页面继承过来后，/tj页面会卡死不能拖拽到底部，比如，放一个MSimpleTable进来后，点击进来后会发现页面拖拽不动，就是不能往下拉，点击其他页面后再点回来，就又可以了，不知道为什么会出现这种情况。

### .NET version

9.0 rc1

**Comment by capdiem** [comment]
@zdp120 可能是这个stackpage下存在嵌套的两个滚动容器，simpletable内容可能有个滚动条，然后外部也有个滚动条，当你的焦点在table时，外面就滚动不了了。

**Comment by zdp120** [comment]
但是通过别的页面点回来，就好了，经常发生，再有，你说的这个情况应该怎么避免

**Comment by zdp120** [comment]
就是没有浏览器啊，要是能在浏览器上就好调试了，这里也贴不了代码

**Comment by zdp120** [comment]
@capdiem 用DevTools打开查看，有个异常，masa-blazor.js:1  [MTab] the element of slider wrapper is not found，是这个引起的吗

**Comment by capdiem** [comment]
@zdp120 你用了tabs？不一定是这个问题。源码如果可以公开的话，可以上传github或gitee。

**Comment by zdp120** [comment]
@capdiem 好的，我来专为这个弄个小Demo，其实，我仔细看了一下，就是右侧的页面滚动条不工作了

**Comment by zdp120** [comment]
查出来问题了，具体的情况是这样的，/hq页面是受到用户名保护的，只有登录的用户才可以用，在跳转到登录/login页面登录后，原来用的是  navigationManager.NavigateTo("/"); 跳转到首页，这样就出现这种情况了，如果改成navigationManager.NavigateTo("/",true);强制刷新，就没有问题了，欢聚话说，如果我整站都采用了PPageStack进行包裹的话，但凡有一处用到了navigationManager.navigateto("")没有采用强制刷新，都可能出现异常，我不知道这个是不是你们程序的bug

**Comment by capdiem** [comment]
@zdp120 你的情况我目前也分析不出来为什么，我们的APP也没有遇到这样的问题。           https://github.com/masastack/Masa.Blazor.MauiDemo/tree/main/Masa.Blazor.MauiDemo.Rcl/Shared 这个Demo，登录和未登录是两个Layout。

**Comment by capdiem** [comment]
@zdp120 href="" 和 navigateTo("", false) 一样，blazor是单页面应用，一般不用强刷。
