### ISSUE TITLE
[Bug Report]: BlazorApp下路由到Server页面时提示Not found

### ISSUE THREAD

**Issue by kx500** [masastack/MASA.Blazor#2174]
### Masa.Blazor version

1.7.4

### Describe the bug

能够正常路由到Server页面，但是过1秒钟左右会提示Not found，路由到WebAssembly页面不会出现问题。
为了测试这个问题处在哪里我专门创建了一个新的BlazorApp项目测试，发现使用Masa.Blazor后就会出现上面的问题。

### .NET version

8.0

### What browsers are you seeing the problem on?

Microsoft Edge

**Comment by kx500** [comment]
发现是使用了InteractiveAuto导致的，新项目自带的是RenderModeForPage也就是访问Account相关路由时使用null
//
private IComponentRenderMode? RenderModeForPage => HttpContext.Request.Path.StartsWithSegments("/Account") ? null : InteractiveAuto;

**Comment by capdiem** [comment]
@kx500 请提供最小可复现的项目。

**Comment by kx500** [comment]
> @kx500 请提供最小可复现的项目。

我找到问题了，就是因为渲染模式不能使用空interactive
