### ISSUE TITLE
[Bug Report]: 使用Data tables（数据表格）设置ItemsPerPage感觉不对

### ISSUE THREAD

**Issue by daipeng0809** [masastack/MASA.Blazor#2175]
### Masa.Blazor version

1.7.3

### Describe the bug

<img width="431" alt="image" src="https://github.com/user-attachments/assets/ad7f6c50-0c5f-44ab-bf9a-21feb8018849">
<img width="471" alt="image" src="https://github.com/user-attachments/assets/9591f593-a97e-4d6e-afc9-f75cf5380d14">

默认ItemsPerPage是5，翻页这里是5，10，15没有问题。
但当我把ItemsPerPage改成13以后，翻页这里还是5，10，15我觉得不对，他应该变成26，39，42这样翻倍呀。

<img width="475" alt="image" src="https://github.com/user-attachments/assets/8f570414-0a33-424b-b20e-365939d77c26">
<img width="647" alt="image" src="https://github.com/user-attachments/assets/56f1777b-9bd0-4d29-b410-3b11f9a738c6">
<img width="587" alt="image" src="https://github.com/user-attachments/assets/68b205d4-c231-475c-8cf0-9c72dba8aba2">

当我点击5以后，页面就变成了5条，回不到我设置的13条了。

还有一个问题，网站介绍里面是中文。

<img width="481" alt="image" src="https://github.com/user-attachments/assets/c453b2c0-6718-405d-b406-931723714a2f">

而使用组件的时候变成英文了，还是我没找到设置的地方啊？

<img width="467" alt="image" src="https://github.com/user-attachments/assets/1c1558ca-ac48-4bf4-97c7-3b193f57f1b5">

**Comment by capdiem** [comment]
@daipeng0809 默认可选 5,10,15,-1，你需要传这里面的数字之一。你可通过 `FooterProps="p => p.ItemsPerPageOptions = new List<OneOf<int, DataItemsPerPageOption>>(){5, 10, 15, -1}` 修改可选值。
