### ISSUE TITLE
[Bug Report]: 空interactive渲染模式下功能无效

### ISSUE THREAD

**Issue by kx500** [masastack/MASA.Blazor#2177]
### Masa.Blazor version

1.7.4

### Describe the bug

rendermode InteractiveServer和rendermode InteractiveAuto 下都正常，interactive为空的时候UI正常但是功能无效，包括表单验证也无效，其他没测试

### .NET version

8.0

**Comment by capdiem** [comment]
@kx500 表单验证、任何事件都需要开启交互。

**Comment by kx500** [comment]
> @kx500 表单验证、任何事件都需要开启交互。

但是有个问题啊，如果使用非静态渲染模式，在Blazor App下无法路由到BlazorServer里的页面，会提示Not Found

**Comment by capdiem** [comment]
@kx500 提供复现项目吧，交互的概念多少有点坑，一句话也说不清楚。

**Comment by kx500** [comment]
> @kx500 提供复现项目吧，交互的概念多少有点坑，一句话也说不清楚。

在Blazor App下无法路由到BlazorServer里的页面，会提示Not Found

这个不是你们的问题，是Blazor本身的问题，在新创建的项目里也是这样 ，你随便新创建一个Blazor Web App项目，然后访问（ 域名/Error）试试就知道了

**Comment by capdiem** [comment]
@kx500 总之交互的模式最好是按着blazor文档来，有些规则我也不清楚，不是masablazor的问题我就关闭此issue了。
