### ISSUE TITLE
希望日期选择器能出周视图

### ISSUE THREAD

**Issue by Ousniba** [masastack/MASA.Blazor#2180]
我想在页面上按周显示日历，目前Date Pickers好像不支持按周显示。
希望能出个周视图，Header显示年月、今年第几周，有左右图标切换上下周，日历主体第一行显示星期几，第二行显示当日所在的周。

如果能尽快出，那就太棒了！
![微信截图_20240930121415](https://github.com/user-attachments/assets/41ac342f-b6a4-4f46-8f12-deb4a70dd596)

**Comment by capdiem** [comment]
![image](https://github.com/user-attachments/assets/0bc65dab-65c0-4437-88c7-1689177c2f06)

**Comment by capdiem** [comment]
@Ousniba 是这个吗？

**Comment by Ousniba** [comment]
你是说CanlendarWeekRulesh属性吗？我想在MASA Try里面试的，结果有报错。
还是说，我只能在代码里试？需要把NuGet包更新到最新版本吗？

**Comment by Ousniba** [comment]
@capdiem

**Comment by capdiem** [comment]
@Ousniba 你本地项目跑 try有些报错跟代码无关

**Comment by Ousniba** [comment]
> @Ousniba 你本地项目跑 try有些报错跟代码无关

我回去再试试，谢谢你！

**Comment by capdiem** [comment]
@Ousniba 目前没有计划做类似的组件，我认为只做周的话还是比较简单的，你可以尝试自己写写看👀

**Comment by Ousniba** [comment]
> @Ousniba 目前没有计划做类似的组件，我认为只做周的话还是比较简单的，你可以尝试自己写写看👀

这样啊，那我试试吧，谢谢你
