### ISSUE TITLE
[Bug Report]:  MFileInput 组件无法使用

### ISSUE THREAD

**Issue by kx500** [masastack/MASA.Blazor#2183]
### Masa.Blazor version

1.7.4

### Describe the bug

最近在项目中使用了MASA.Blazor发现还存在着太多的问题了，很多组件直接用官网示例运行都报错，包括MTextField 组件，

       <MFileInput @bind-Value="_files"  AppendIcon="mdi-camera">
           <LabelContent>上传图片</LabelContent>
       </MFileInput>

@code{
private List<IBrowserFile> _files = new();
}

上面用法哪里有问题？就是报错：
InvalidStateError: Failed to set the 'value' property on 'HTMLInputElement': This input element accepts a filename, which may only be programmatically set to the empty string.

### .NET version

8.0

**Comment by capdiem** [comment]
@kx500 你的代码我无法复现，如果是多个文件，你需要加 `Multiple` 属性。
