### ISSUE TITLE
add swipe navigation to PageStack

### ISSUE THREAD

**Issue by charleypeng** [masastack/MASA.Blazor#2184]
like normal mobile apps,  user can swipe from left to right to navigate back to the last page, i've seen some webview based app did this and i am looking for some resolution, any first idea and hints on how to implement in masa blazor?

**Comment by capdiem** [comment]
@charleypeng Thank you for your usage. According to the standard PR process, you can first fork the repository and then submit a PR. We will review it and decide whether to merge it into the repository.

**Comment by charleypeng** [comment]
> @charleypeng Thank you for your usage. According to the standard PR process, you can first fork the repository and then submit a PR. We will review it and decide whether to merge it into the repository.

hi. i need help there. i have added the swipe area as a component, the question is i can not wrap the ppageitem in it, it is not woking ,  however when i wrap it in other normal page it works just fine

**Comment by charleypeng** [comment]
feature repo :  https://github.com/charleypeng/MASA.Blazor/tree/feat/swipearea
feature folder: https://github.com/charleypeng/MASA.Blazor/tree/feat/swipearea/src/Masa.Blazor/Components/Swiper
taget razor component: https://github.com/charleypeng/MASA.Blazor/blob/feat/swipearea/src/Masa.Blazor/Presets/PageStack/PPageStackItem.razor

**Comment by capdiem** [comment]
@charleypeng I understand. You have added a swipearea component. For the pagestack component, we plan to implement a similar feature that allows for a draggable effect, rather than just swiping to trigger open or close actions.

**Comment by charleypeng** [comment]
> @charleypeng I understand. You have added a swipearea component. For the pagestack component, we plan to implement a similar feature that allows for a draggable effect, rather than just swiping to trigger open or close actions.

cool then
