### ISSUE TITLE
[Bug Report]: Data Tables组件FixedHeader属性和ResizeMode属性冲突，设置ResizeMode后FixedHeader失效

### ISSUE THREAD

**Issue by 0xf0pfp183** [masastack/MASA.Blazor#2203]
### Masa.Blazor version

1.7.7

### Hosting model

Blazor Server

### Describe the bug

Data Tables组件同时设置FixedHeader和ResizeMode属性时，FixedHeader失效，表头无法固定，不设置ResizeMode属性则正常固定。

### .NET version

8.0.401

**Comment by capdiem** [comment]
Duplicate of #1722
