### ISSUE TITLE
[Bug Report]: NavigationManager.RegisterLocationChangingHandler后导致go back路由异常

### ISSUE THREAD

**Issue by Memoyu** [masastack/MASA.Blazor#2211]
### Masa.Blazor version

1.7.8

### Hosting model

Blazor Server

### Describe the bug

将Masa.Blazor升级至最新1.7.8后，打开Todo页面会触发NavigationManager.RegisterLocationChangingHandler，后再到User页面跳转页面，再返回时出现页面跳转未按预先路径回退
![masa-bug](https://github.com/user-attachments/assets/f3181781-1220-4448-aabb-13002eb62fee)

关联：[Masa.Blazor.MauiDemo #4](https://github.com/masastack/Masa.Blazor.MauiDemo/issues/4)

### Steps To Reproduce

1. 升级Masa.Blazor 至 1.7.8
2. 启动项目后先点击Todo页面
3. 再到User页面，再进行页面跳转：设置 -> Dark-mode或About us 
4. 点击顶部导航栏返回

### .NET version

.NET 8

**Comment by capdiem** [comment]
@Memoyu 调查了下，RegisterLocationChangingHandler 注册后会导致PageStack组件内部的Popstate一直调用，这块暂时没有找到解决的方案。1.7.8会出现这个问题是因为之前有个js异常修复了，没有阻碍blazor内部的JS正常执行。

解决办法只有找个时机去把RegisterLocationChangingHandler释放掉。

**Comment by Memoyu** [comment]
> @Memoyu 调查了下，RegisterLocationChangingHandler 注册后会导致PageStack组件内部的Popstate一直调用，这块暂时没有找到解决的方案。1.7.8会出现这个问题是因为之前有个js异常修复了，没有阻碍blazor内部的JS正常执行。
> 
> 解决办法只有找个时机去把RegisterLocationChangingHandler释放掉。

get🙌我想个办法规避一下

**Comment by capdiem** [comment]
@Memoyu v1.8.0 会添加当前激活tab更改的事件，这样就不需要使用 RegisterLocationChangingHandler 了。
