### ISSUE TITLE
[Bug Report]: MAppBar: ElevateOnScroll只会被js触发 未在初始化时处理

### ISSUE THREAD

**Issue by VleaStwo** [masastack/MASA.Blazor#2232]
### Masa.Blazor version

1.7.8

### Hosting model

Interactive Server

### Describe the bug

ElevateOnScroll=true 时 理想状态当页面top>0时 显示海拔 反之海拔=0

在一些情况下 页面初始时 top>0 此时并不会生效, 需要滚动或window.resize触发

需要初始时判断 `top is 0` 

### .NET version

net 9.0

**Comment by capdiem** [comment]
https://github.com/dotnet/aspnetcore/issues/51646

blazor web app的增强导航导致的，正常来说刷新后滚动条应该是在顶部。现在只需要在初始化时判断一下滚动条的位置。

**Comment by VleaStwo** [comment]
> https://github.com/dotnet/aspnetcore/issues/51646
> 
> blazor web app的增强导航导致的，正常来说刷新后滚动条应该是在顶部。现在只需要在初始化时判断一下滚动条的位置。

我也觉得是
