### ISSUE TITLE
Dialog打开时是否可以不聚焦

### ISSUE THREAD

**Issue by Yu-Core** [masastack/MASA.Blazor#2259]
**Is your feature request related to a problem? Please describe.**
Dialog打开时，会获取焦点。某些场景时，比如移动端的文本框，想要软键盘一直保持打开，而Dialog获取焦点会使软键盘收起。

**Describe the solution you'd like**
希望加一个可以控制是否获取焦点的属性

**Describe alternatives you've considered**

**Additional context**
看起来与这里有关 https://github.com/masastack/MASA.Blazor/blob/1.8.0-rc.3/src/Masa.Blazor/Components/Dialog/MDialog.razor.cs#L136

**Comment by capdiem** [comment]
@Yu-Core 文本框启用了autofocus的时候也有这个问题吗？

**Comment by Yu-Core** [comment]
与autofocus无关
Dialog打开时会聚焦，焦点就不在原来的输入框了，软键盘也就收起了

```
<MRow>
    <MTextField TValue="string"></MTextField>
</MRow>
<MRow Justify="JustifyTypes.Center">
    <MButton Color="primary"
             Dark
             OnClickStopPropagation
             OnClick="()=> dialog = true"
             __internal_preventDefault_onmousedown>
        Open Dialog
    </MButton>

    <MDialog @bind-Value="dialog"
             MaxWidth="290">
        <MCard>
            <MCardTitle Class="text-h5">
                Use Google's location service?
            </MCardTitle>

            <MCardText>
                Let Google help apps determine location. This means sending anonymous location data to Google, even when no apps are running.
            </MCardText>

            <MCardActions>
                <MSpacer></MSpacer>

                <MButton Color="green darken-1"
                         Text
                         OnClick="()=> dialog = false">
                    Disagree
                </MButton>

                <MButton Color="green darken-1"
                         Text
                         OnClick="()=> dialog = false">
                    Agree
                </MButton>
            </MCardActions>
        </MCard>
    </MDialog>
</MRow>

@code {
    bool dialog = false;
}
```
https://github.com/user-attachments/assets/1e2e6d32-ea3d-442e-a712-9b5e218dae2b

如果我将这一块代码注释掉，它就可以了
![image](https://github.com/user-attachments/assets/67602e68-25e4-4a0e-8f10-cde90529ea6c)


https://github.com/user-attachments/assets/731b94eb-97e8-4f57-9c99-94bc4a21e103

**Comment by capdiem** [comment]
@Yu-Core 你的DEMO我能看懂，只是我不知道什么场景下dialog出来后要把上一个场景的输入法留下来。dialog自动聚焦的功能其实我也不确定有什么场景，可能是聚焦后可以用tab键等键盘操作，移动端应该没这个必要。

**Comment by Yu-Core** [comment]
就像他这个应用的这种场景。如果软键盘起起落落，体验很不好。

https://github.com/user-attachments/assets/2080715d-9b60-4f9c-9031-a922daaec016


应该不算bug，属于功能请求，我的理解是dialog本身就是要打断当前操作的。保持原有焦点这种情况算是少数。添加一个属性控制一下就可以了。
