### ISSUE TITLE
DataTable 对于 datetime列 能不能显示自定义格式？

### ISSUE THREAD

**Issue by huxinshuo** [masastack/MASA.Blazor#2281]
### Proposal and motivation

DataTable 对于 datetime 列能不能自定义格式？
比如只显示日期不显示 时间？ 日期格式定义为年-月-日之类的
好像C#没有单纯的日期格式 只有 datetime格式
所以DataTable 能不能支持对日期的一些自定义？

**Comment by huxinshuo** [comment]
表格里面显示格式是这样的：1/1/2024 12:00:00 AM .  能不能显示2024-01-01？

**Comment by capdiem** [comment]
@huxinshuo 文档有例子啊，使用ItemColContent或者CellRender。

**Comment by huxinshuo** [comment]
@capdiem 
CellRender = Tasks => Tasks.PayDate.ToString("yyyy-MM-dd")  这个好像无效 还是显示1/1/2024 12:00:00 AM  能否设置某个列的格式为日期格式？因为查看row信息在dialog要datetime格式。    
CellRender好像只是转换文本。

**Comment by capdiem** [comment]
@huxinshuo 你是不是已经用了ItemColContent？它和CellRender不能一起用。Dialog里格式再自己转换一下。
