### ISSUE TITLE
MAUI Blazor项目中

### ISSUE THREAD

**Issue by 239573049** [masastack/MASA.Blazor#632]
![D~$WEMLV 5LZ3TH CZ@28{8](https://user-images.githubusercontent.com/61819790/187979685-a5e13843-811a-4f0f-a64f-cd9c960c0b7a.png)
![HA3 JXK`T1X`M~4Q0${C5N2](https://user-images.githubusercontent.com/61819790/187979694-67bf8b86-db94-4486-a0a0-05cba63f7076.png)
![_543S25`JM_BEB(7%JI)AWS](https://user-images.githubusercontent.com/61819790/187979952-926d0601-41a2-4c9a-ab38-7de45feab51c.png)
在blazor的cs文件中写弹框是可以正常运行的
但是在调用service的服务中无法正常弹出
这个service是注入到容器中通过依赖注入拿到的服务

**Comment by 239573049** [comment]
![image](https://user-images.githubusercontent.com/61819790/187980139-54f4eeba-6105-4582-9979-929cb6ad5cdf.png)
这个blazor中的弹出框
正常运行了
但是方法的弹框无法运行

**Comment by 239573049** [comment]
并没有效果

**Comment by 239573049** [comment]
哪个服务？我自己的服务吗？

**Comment by capdiem** [comment]
@239573049 是的，看你的截图好像是蓝牙的那个Service。
