### ISSUE TITLE
Masa官网在4k屏幕下非常卡

### ISSUE THREAD

**Issue by LunarChild** [masastack/MASA.Blazor#647]
浏览器：Edge
操作系统：Windows10
配置简介：AMD 5900HS 16GB RAM
通过浏览器在4k分辨率屏幕上打开网址https://osc-dev.masastack.com/blazor 时 网站动画滚动等效果非常卡。当取消最大化将窗口缩小到等效1080P左右时恢复流畅。在此期间CPU占用率没有明显的变化，均在10%左右

**Comment by capdiem** [comment]
4K分辨率下会出现卡顿可能由于以下一些因素导致的：图像和媒体资源过大、复杂的CSS和动画效果、JavaScript执行效率低下和硬件限制。官网的内容大多数都是图片和文字，经过更新后现已4k下基本可用。
