### ISSUE TITLE
StringNumber is there

### ISSUE THREAD

**Issue by china-live** [masastack/MASA.Blazor#675]
？？？

**Comment by doddgu** [comment]
你想问什么？你可以中文来描述

**Comment by china-live** [comment]
找到了，按照文档操作，结果找不到StringNumber，翻了好久才在 BlazorComponent 下找到。
建议你们更新一下文档，全局引用 
 https://blazor.masastack.com/getting-started/installation

**Comment by doddgu** [comment]
是的，这个问题的确出现过几次了，我们将在文档重构时对文档内容进行重新梳理。预计在1.0完成所有工作。如果你也有兴趣参与到文档建设中来，欢迎与我们联系，谢谢。
