### ISSUE TITLE
支持模型类的本地化

### ISSUE THREAD

**Issue by whuanle** [masastack/MASA.Blazor#679]
对于模型类，我们需要在表格等位置使用到，我们希望其字段的显示名称可以根据本地化语言配置，在不同的语言回家下，显示不同的语言字符。
什么时候做一个支持模型类的 i18n 呀？

**Comment by doddgu** [comment]
这个不难，只需要在 ItemColContent 渲染过程中去介入即可。但问题是大多数场景可能需要自定义 ItemColContent 的渲染，这是模型类支持I18n就没有意义了。当然这的确是个不错的功能，反正只需要构建表达式树缓存将I18n与模型类中的属性关联起来，再给数据迭代器增加启用开关，最终在渲染时自动替换值即可。

但这个我个人认为目前不是1.0的主要功能，我们需要在年底前完成1.0的封版工作，当然我们欢迎有能力的同学可以给我们提供这个pr。

**Comment by whuanle** [comment]
考虑一下，将 i18n 组件，单独放出来，做一个 nuget 包

**Comment by doddgu** [comment]
如果有必要的话，后面考虑一下吧，暂时没精力。我们后面重构文档的压力比较大。

**Comment by capdiem** [comment]
没计划。
