### ISSUE TITLE
Editor . After uploading the image, the page loads

### ISSUE THREAD

**Issue by LazyEar0** [masastack/MASA.Blazor#692]
Server ：Web
 Ctrl + V 粘贴图片至编辑器内后，每操作一步页面都加载

https://user-images.githubusercontent.com/95004531/195002452-b8180790-9e64-472c-90bf-7b8cb56b1ec5.mp4

**Comment by capdiem** [comment]
@doddgu 在 Blazor Server 中，JS 互操作调用最大传入 SignalR 消息大小限制默认为32kb，但大小图片大于此值的时候就会发生此问题，虽然可以将值改大，但是无法控制用户传入多大的图片。也许可以开发一个功能，限制传入图片的大小。

**Comment by capdiem** [comment]
Server可以将SignalR 消息大小限制设置更大解决。
