### ISSUE TITLE
非本机网络问题的情况下官网莫名掉线

### ISSUE THREAD

**Issue by Caspersure** [masastack/MASA.Blazor#767]
官方网站经常突然断开连接显示尝试重连,刷新和重新输入网址跳转都进不去
浏览器开发者模式如下

![image](https://user-images.githubusercontent.com/62390646/200725570-cc87bbc6-1d61-455e-a31c-da7cdc1b7bd8.png)

![image](https://user-images.githubusercontent.com/62390646/200724227-bfc4635e-3a07-4f6f-a4da-5b22cbd88f10.png)

![image](https://user-images.githubusercontent.com/62390646/200725905-adf63efb-c047-4d75-9f99-7d93cb8613ca.png)

**Comment by doddgu** [comment]
通过观察，这并不是bug，由于最近在迁移云，造成原有服务不稳定。但因为迁移范围很广，可能一时半会没那么快解决。暂时建议先实用wasm站点。https://blazor-wasm.masastack.com
