### ISSUE TITLE
导航抽屉如何实现手势滑出？

### ISSUE THREAD

**Issue by swordream** [masastack/MASA.Blazor#829]
认真看了文档，没看到怎么在移动设备上通过左滑唤出。

**Comment by capdiem** [comment]
目前不支持，我们是参考vuetify v2做的，它到v3才支持的touch。

**Comment by swordream** [comment]
辛苦了！做的非常棒，用起来很舒服

**Comment by 239573049** [comment]
> 辛苦了！做的非常棒，用起来很舒服

可以参考这篇博客实现 也是基于masa Blazor 
https://www.cnblogs.com/hejiale010426/p/17065146.html
