### ISSUE TITLE
ItemGroup: Change the type of Value from `StringNumber` to `string`

### ISSUE THREAD

**Issue by capdiem** [masastack/MASA.Blazor#855]
**Is your feature request related to a problem? Please describe.**
一个重构计划。

**Describe the solution you'd like**
将 Value的类型从 `StringNumber` 改为 `string`，原因有以下两点：
1. `StringNumber`是一个类，Value是一个Parameter，类为类型的Parameter总会响应来自父组件的刷新请求，这是可避免的。
2. 每个值类型都可以ToString成为字符串。

有其他建议吗？

**Comment by doddgu** [comment]
2.0

**Comment by capdiem** [comment]
#492 应该等此issue完成后动工。

**Comment by doddgu** [comment]
那先不急
