### ISSUE TITLE
Docs文档渲染效果

### ISSUE THREAD

**Issue by 239573049** [masastack/MASA.Blazor#872]
参考 [semi](https://semi.design/zh-CN/input/cascader) 网站的样子
考虑他这种渲染效果 ，上面为组件实际渲染效果 下方编辑框是组件代码 然后怎么实现razor在浏览器中动态编译，效果跟这个网站一样在docs文档的网站中动态修改code去动态渲染效果

**Comment by capdiem** [comment]
1.0 的示例是用custom elements生成的，如何动态编译是个问题，期待你有可行的方案 😁
