### ISSUE TITLE
在车间工厂等没有外部网络的生产环境下,图标无法加载

### ISSUE THREAD

**Issue by Caspersure** [masastack/MASA.Blazor#918]
在无外网的生产环境下,图标不能正常加载,希望作者大大能扩展一下让程序可以用离线的方式加载图标,辛苦啦

**Comment by doddgu** [comment]
你可以安装我们的模板，然后通过MASA Blazor Pro的模板创建项目，过程中会有选项是否使用CDN，不勾选就是本地的。然后你就可以把里面的引用本地文件部分copy到你自己的项目里。

**Comment by capdiem** [comment]
@MayueCif masa.blazor.template 也支持下可以用本地字体？

**Comment by capdiem** [comment]
普通的模板也支持了静态资源：https://github.com/masastack/MASA.Templates/issues/18
