### ISSUE TITLE
MPagination组件elevation设置失效

### ISSUE THREAD

**Issue by mookeview** [masastack/MASA.Blazor#955]
我想让MPagination组件扁平化显示，但该组件目前未开放类似Flat或Eelevation属性，我尝试在Class中写入class=“elevation-0”，不起作用。

**Comment by capdiem** [comment]
Pagination的实现与Elevation无关，你需要覆盖样式：
```
.m-pagination__item { 
    box-shadow: none;
    border: 1px solid rgb(0 0 0 / 15%);
}
```

**Comment by mookeview** [comment]
谢谢，看来还是得学会变通啊。不过还是建议加上Elevation属性，这样操作更统一了。

**Comment by capdiem** [comment]
你说得对，我发现 [Vuetify 3.0](https://next.vuetifyjs.com/en/components/paginations/) 的 Pagination 已经改成这样了。短时间内不会跟进它的3.0。
