### ISSUE TITLE
InvariantGlobalization模式下屏蔽I18n设置CultureInfo功能

### ISSUE THREAD

**Issue by cqgis** [masastack/MASA.Blazor#974]
因为某种原因，需要在
`<InvariantGlobalization>true</InvariantGlobalization>`
模式下发布程序，这要求不能使用设置当前语言的功能。
目前版本下，在I18n构造函数中调用了相关方法，导致不能正确初始化，能否考虑将I18n构造函数中的代码移到单独的方法中，并将其标注为virtual，这样在不需要的时候，可以通过继续子类，对相关功能进行屏蔽。

受影响的方法还有 AddLocale()、   SetCulture() 希望都能标注为virtual

**Comment by doddgu** [comment]
@cqgis 感谢你的反馈。我们目前没有计划这样做，但长期规划里有将依赖逐渐拆分出去的撒算。所以我们创建了个新的repo：https://github.com/BlazorComponent/MASA.Blazor.Extensions
如果等待我们重构，这可能需要一些时间，如果你对此感兴趣，你也可以给我们pr。

**Comment by capdiem** [comment]
多谢关注，没计划
