### ISSUE TITLE
内存异常

### ISSUE THREAD

**Issue by bingbingtalk** [masastack/MASA.Blazor#992]
下载MASA.Blazor.Pro项目，发布后运行Masa.Blazor.Pro\bin\Release\net6.0\Masa.Blazor.Pro.exe，通过浏览器访问https://localhost:5001/。

此时多次切换各个菜单后，Masa.Blazor.Pro.exe占用内存迅速从45M上升至700M左右（到达700多M后进行相同操作内存基本不会再增高了），关闭TAB页甚至关闭浏览器后Masa.Blazor.Pro.exe占用内存也不下降。

然后分别切换到各个页面后多次按F5刷新页面，Masa.Blazor.Pro.exe占用内存又开始升高，最高升到1G后基本上不再增加了，关闭浏览器后Masa.Blazor.Pro.exe占用内存也不下降。
![image](https://user-images.githubusercontent.com/44472040/217541769-4fd5eabf-9347-455c-a80a-13748d19559d.png)

**Comment by doddgu** [comment]
有进展么

**Comment by LittleFish-233** [comment]
@bingbingtalk 可以尝试使用 `工作站 GC` 模式，可以观察到内存回落

![image](https://user-images.githubusercontent.com/53342258/222939417-c6866ecb-de15-4f4f-88f5-5f155776cc85.png)

> 下图显示使用工作站 GC 的低于 5K RPS 的内存配置文件。
> 
> ![image](https://user-images.githubusercontent.com/53342258/222939619-a0568442-fea6-441b-b634-f69764b9d2bd.png)
> 
> 此图表与服务器版本之间的差异十分显著：
> 
> >  工作集从 500 MB 下降到 70 MB。
> > GC 每秒（而不是每两秒）进行多次第 0 代回收。
> >  GC 从 300 MB 下降到 10 MB。
> 
> 在典型 Web 服务器环境中，CPU 使用率比内存更重要，因此服务器 GC 更好。 如果内存利用率较高而 CPU 使用率相对较低，则工作站 GC 可能性能更高。 例如，在内存短缺的情况下高密度托管多个 Web 应用。

具体参阅这篇文章：https://learn.microsoft.com/zh-cn/aspnet/core/performance/memory?view=aspnetcore-6.0

**Comment by doddgu** [comment]
工作站GC是可以将内存降下来，但点几次就飙升到700M感觉内存的使用还是过于夸张，可能还是要了解下是blazor本身的问题还是代码出了问题。

**Comment by capdiem** [comment]
Blazor Server下内存在用户操作下不可避免地会不断攀升，可以从以下三点优化：
1. 维持断开电路的数量从默认100调小到10
2. 还有维持的时间从默认3分钟调到1分钟
3. 框架升到net8.0
